### ISSUE TITLE
Question about OAuth2Configuration with Proxy for WebClient

### ISSUE THREAD

**Issue by GlittersGold** [reactor/reactor-netty#2879] opened 2023-08-27 05:09 UTC
Here is a minimal reproducer for my question:

Netty Version Utilized: 1.0.19
Anticipated Outcome:  Consistent successful calls to the proxy server using WebClient, similar to the previous RestClient instances.
Actual Outcome:          Sporadic success with WebClient calls.

Concurrently, I am attempting to extract two types of information and provide you asap:
1. Server logs indicating Premature Connection Close.
2. Wireshark/tcpdump logs for comparing WebClient and RestTemplate calls.

In the meanwhile, I would appreciate your expert review of my code to identify any glaring misconfigurations, so that I can modify the codebase accordingly and obtain the aforementioned information with greater relevance, and update in this Github Issue or make the new one for a more precise context.

WebClientOAuth2Configuration content:
```
import com.github.benmanes.caffeine.cache.Caffeine;
import java.util.Map;
import java.util.concurrent.TimeUnit;
import org.checkerframework.checker.nullness.qual.NonNull;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.json.GsonJsonParser;
import org.springframework.boot.json.JsonParseException;
import org.springframework.cache.CacheManager;
import org.springframework.cache.caffeine.CaffeineCacheManager;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Primary;
import org.springframework.http.client.reactive.ReactorClientHttpConnector;
import org.springframework.security.oauth2.client.AuthorizedClientServiceReactiveOAuth2AuthorizedClientManager;
import org.springframework.security.oauth2.client.InMemoryReactiveOAuth2AuthorizedClientService;
import org.springframework.security.oauth2.client.registration.ClientRegistrationRepository;
import org.springframework.security.oauth2.client.registration.InMemoryReactiveClientRegistrationRepository;
import org.springframework.security.oauth2.client.web.reactive.function.client.ServerOAuth2AuthorizedClientExchangeFilterFunction;
import org.springframework.web.reactive.function.client.ExchangeFilterFunction;
import org.springframework.web.reactive.function.client.WebClient;
import reactor.core.publisher.Mono;
import reactor.netty.http.client.HttpClient;
import reactor.netty.transport.ProxyProvider;

@Configuration
public class WebClientOAuth2Configuration {

  @Bean
  @ConditionalOnProperty(value = "proxy.enabled", matchIfMissing = true)
  HttpClient httpClientWithProxy() {
    String nonProxyHosts = System.getProperty("http.nonProxyHosts");
    String regexProxyList =
        nonProxyHosts
            .replaceAll("\\.", "\\\\.")
            .replaceAll("\\/", "\\\\/")
            .replaceAll("\\*", ".\\*");
    String proxyHost = System.getProperty("https.proxyHost");
    String proxyPort = System.getProperty("https.proxyPort");
    return HttpClient.create()
        .proxy(
            proxy ->
                proxy
                    .type(ProxyProvider.Proxy.HTTP)
                    .host(proxyHost)
                    .port(Integer.parseInt(proxyPort))
                    .nonProxyHosts(regexProxyList));
  }

  @Bean(NAME)
  public WebClient webClient(
      ClientRegistrationRepository clientRegistrations, HttpClient httpClient) {
    var registrationRepository =
        new InMemoryReactiveClientRegistrationRepository(
            clientRegistrations.findByRegistrationId("id1"));
    var clientService = new InMemoryReactiveOAuth2AuthorizedClientService(registrationRepository);
    var authorizedClientManager =
        new AuthorizedClientServiceReactiveOAuth2AuthorizedClientManager(
            registrationRepository, clientService);

    var oauth = new ServerOAuth2AuthorizedClientExchangeFilterFunction(authorizedClientManager);
    oauth.setDefaultClientRegistrationId("id1");

    return WebClient.builder()
        .filter(oauth)
        .filter(handleError())
        .clientConnector(new ReactorClientHttpConnector(httpClient))
        .build();
  }

  @Bean(CONFIG)
  public @NonNull Caffeine<Object, Object> caffeineConfig() {
    return Caffeine.newBuilder().expireAfterWrite(DURATION, TimeUnit.HOURS);
  }

  @Primary
  @Bean(CACHE_MANAGER)
  public CacheManager cacheManager(
      final @Qualifier(CONFIG) Caffeine<Object, Object> caffeine) {
    var cacheManager = new CaffeineCacheManager(CODES_CACHE);
    cacheManager.setCaffeine(caffeine);
    return cacheManager;
  }

  static ExchangeFilterFunction handleError() {
    return ExchangeFilterFunction.ofResponseProcessor(Mono::just);
  }
}
```

NewClient content:
```
import static org.apache.commons.lang3.builder.ReflectionToStringBuilder.toStringExclude;

import javax.validation.constraints.NotNull;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.http.HttpHeaders;
import org.springframework.stereotype.Component;
import org.springframework.web.reactive.function.client.WebClient;

@Component
public class NewClient {

  private WebClient webClient;
  
  public static final String url = "URL";

  public NewClient(@Qualifier(NAME) WebClient webClient) {
    this.webClient = webClient;
  }

  @Override
  @Cacheable(
      cacheManager = CACHE_MANAGER,
      cacheNames = CODES_CACHE,
      key = "#headers.ACCEPT")
  public ItemList getItems(HttpHeaders headers) {
    ItemList items =
        webClient
            .get()
            .uri(url)
            .headers(httpHeaders -> httpHeaders.addAll(headers))
            .retrieve()
            .bodyToMono(ItemList.class)
            .block();
    return items;
  }
}
```

**Comment by pderop** [comment] 2023-08-29 09:19
@GlittersGold ,

I cannot say much about the sample code you provided, the part that is specific to reactor-netty HttpClient seems good.

do you have some logs to show from the WebClient, when you are getting the occasional request failures ?

now, regarding your comment: 

> logs indicating Premature Connection Close

then did you check https://projectreactor.io/docs/netty/release/reference/index.html#faq.connection-closed ?

**Comment by pderop** [comment] 2023-08-29 17:33
@GlittersGold, in addition to the previous message, can you also upgrade to the latest reactor-netty version, which is 1.0.35 ?

**Comment by GlittersGold** [comment] 2023-08-29 22:26
@pderop Thanks so much for your advice, I've upgraded my reactor-netty version to 1.0.35. 
For better understanding, I believe sharing WebClient logs whenever sporadic requests fail, following the provided documentation link, would be beneficial. 

Is the current approach accurate, and any additional steps that can be taken? 
Would it be beneficial to provide a comparison of two requests— one utilizing RestTemplate consistently, and the other using WebClient with sporadic failures? Could this comparison yield valuable insights?

**Comment by GlittersGold** [comment] 2023-09-06 05:40
@pderop 
Some of my thinking, could you please consider, Piere:

I initially shared the cache configuration with you to give you full context for your review. While caching features like `@Cacheable` and WebClient functionality are usually independent of each other, I've recently been investigating some edge cases. These involve potential problems arising from the interaction between `@Cacheable` and WebClient, especially concerning connection failures.

For example, in my WebClient setup, exceptions are handled directly. However, since the method is also annotated with `@Cacheable`, there's a possibility that the exception and its corresponding handling mechanism could get cached. This may disrupt the expected behavior of future calls.

In addition, I'm employing WebClient for asynchronous operations using reactive types like `Mono` and `Flux`. When these methods are annotated with `@Cacheable`, it's the `Mono` or `Flux` object that gets cached, not the actual data, leading to potential issues.

Given these complexities, what would be the most efficient testing approach? Should I first isolate `@Cacheable` from WebClient to debug and test them separately in phase one, and then proceed to test them together in phase two?

My goal is to streamline the debugging process and quickly resolve the intermittent connection issues, which are currently causing significant disruptions.

**Comment by pderop** [comment] 2023-09-06 09:04
good catch. I never used @Cacheable annotations, but Indeed, it seems that if the webClient is getting intermittent and temporary failures, then the failures will cascade to subsequent calls to getItems, even if the transient issue have been resolved. You could arrange to avoid caching errors or any thrown exceptions using something like `unless #result == null`, but your should try to reduce dependencies and complexity as much as possible in order to figure out the cause of the intermittent errors.

can you disable all caching ?

**Comment by GlittersGold** [comment] 2023-09-06 13:29
@pderop 
I'm deeply concerned about the intermittent failures we're observing. Whenever I've encountered such issues with HttpClient, they often stem from stateful components, even if my method is designed to be stateless. It's puzzling, but I'm starting to think there might be some underlying stateful behavior.

I see where you're coming from, and I'm open to exploring alternative approaches if they prove more efficient. I recognize that minimizing dependencies might simplify the debugging process. However, I'm hesitant. If the smaller problem doesn't actually exhibit the connection failure we're wary of, then we might end up wasting time on it, only to revert to adding @Cacheable and re-troubleshooting. Do you have any insights on how we can simultaneously investigate both scenarios? This would not only save us time but also provide a side-by-side analysis.

Certainly, I can toggle various settings for the sake of troubleshooting. But, I'm on the fence about whether we absolutely need to integrate certain features. I'll reach out to my teammate to see if our Thesis necessitates the Caching feature.

Meanwhile, I'll dive into my own troubleshooting for the issue and share any findings. Rest assured, I'm not shifting the onus of troubleshooting solely onto you. I'd much rather we collaborate and deepen our understanding together.

Does my line of thinking align with yours, Piere?

**Comment by pderop** [comment] 2023-09-06 13:58
in order to debug, it would be indeed useful to try to temporarily remove as much dependencies as possible (only for debugging of course).

Now, currently, there is not enough information in order to help. So, were you able to check the suggestions made from previous post (https://github.com/reactor/reactor-netty/issues/2879#issuecomment-1698724766) ?

**Comment by GlittersGold** [comment] 2023-09-06 15:48
@pderop 
I completely get it. 
I intend to act on all the suggestions mentioned in the comment and will furnish you with all the details at EOD. 
Once we have adequate information, let's collaborate further. 
Thank you so much.

**Comment by GlittersGold** [comment] 2023-09-07 07:48
@pderop 
Having successfully replicated the issue and meticulously reviewed the error logs, I have not discovered any substantial information beyond the error message below:
"Connection refused: login.microsoftonline.com/x.y.z.t:p; nested exception is io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: login.microsoftonline.com/x.y.z.t:p."

Our WebClient was employed solely for a demonstration involving SSO with Azure AD. At present, it appears that the primary concern lies elsewhere. Consequently, I have compiled a prioritized list of troubleshooting considerations, subject to my discretion:

1. **Firewall or Security Policies Rules**: The possibility exists that firewall regulations or security policies are either obstructing or limiting outbound requests to login.microsoftonline.com.

2. **DNS Resolution Misconfiguration**: Occasional setbacks may result from inaccuracies in DNS resolution settings, thereby complicating connectivity with login.microsoftonline.com.

3. **Azure Service Outages**: Potential disruptions in Azure services could potentially affect the accessibility of login.microsoftonline.com.

4. **Timeouts and Retries Mechanism**: Connection failures may materialize due to insufficient or ineffective timeout and retry mechanisms.

5. **SSL/TLS Configuration Issues**: Occasional handshake failures during connections to secure services such as Azure AD could be ascribed to flawed SSL/TLS configurations, certificate-related issues, or cipher suite disparities.

6. **Resource Constraints**: The possibility of sporadic and unreliable connections could be rooted in limitations pertaining to host resources.

7. **Concurrent Requests and Threads**: Mismanagement of concurrent requests and threads may give rise to resource conflicts and network-related complications, conceivably related to the @Cacheable matter.

8. **Proxy Settings/Server Issues**: Anomalies in connectivity may be traced back to inaccurately configured proxy settings or issues emanating from the proxy server itself.

9. **Azure AD Rate Limiting or Security Mechanisms**: Periodic connection failures might be triggered by rate-limiting measures or security protocols enforced by Azure AD.

10. **Load Balancing and IP Changes**: The likelihood of irregular connectivity issues may escalate if DNS records are not updated promptly, particularly in the event of load balancing adjustments or IP alterations on the Microsoft front.

I would greatly appreciate your guidance, Piere, in examining this list and identifying any items that could be reasonably disregarded or necessitate reordering in terms of priority. Your invaluable assistance is deeply appreciated.

**Comment by pderop** [comment] 2023-09-07 13:20
some suggestions:

1)
>  I have not discovered any substantial information beyond the error message below:
> "Connection refused: login.microsoftonline.com/x.y.z.t:p; nested exception is io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: login.microsoftonline.com/x.y.z.t:p."

So, is this exception coming from the WebClient JVM ?  If so, it seems that the WebClient is trying to connect to `login.microsoftonline.com` directly (not through the proxy). So, is it expected ? Maybe the WebClient shoudl actually reach this address through the proxy, in this case, maybe `login.microsoftonline.com` is matched (but should not be) by the non proxy hosts that are configured in the `http.nonProxyHosts` system property ? 
So maybe it's worth to try to check if the  `http.nonProxyHosts` configuration is correct ?

2)
Can you try to `curl` command from the host where the WebClient JVM is running in order to check if the `login.microsoftonline.com` can be reached.

3) 

Is this connection failure intermittent or permanent ? if intermittent, maybe there is a DNS issue ? Then did you try to use `nslookup` or `dig` in order to verify DNS resolution ?

4) 

is it the proxy or the WebClient jvm which cannot connect to `login.microsoftonline.com` ? If it's the proxy, can you try to use curl from the proxy host in order to check if login.microsoftonline.com is reachable from the proxy host ?

**Comment by GlittersGold** [comment] 2023-09-07 13:54
@pderop 
I have another point to consider, Piere. Presently, RestTemplate is functioning flawlessly without encountering any issues. Hence, I believe it's possible that this issue could be resolved, either within the WebClient codebase or through adjustments in our network settings. Given our time constraints, waiting for a new release, while potentially more robust, may not be feasible. Therefore, our immediate focus should be on examining and fine-tuning our network settings.

However, I also have a concern regarding the investigation I conducted. I noticed that the requests made by RestTemplate and WebClient differ significantly. While I didn't delve deeply into the asynchronous strategy, I vaguely recall encountering discussions about differences in the HTTP request structures. Although these differences may not be highly significant, I acknowledge that they offer opportunities for improvement by the Netty team and other contributors.

Is it possible that our network settings, which seem to work seamlessly with RestTemplate, could intermittently fail when used with our new WebClient, particularly in an asynchronous context? I'd like to stress that this is just my personal perspective, and it's entirely possible that I may be mistaken or that my viewpoint doesn't align with the principles behind the implementation of this WebClient. I'm eager to learn more about this matter.

Thank you for your consideration.

**Comment by GlittersGold** [comment] 2023-09-08 14:15
@pderop 
I want to clarify that my current focus is on collaborating with my university's IT team to adjust network settings and resolve the issue at hand. This effort doesn't imply any reliance on your team, Netty. My commitment to my thesis and working with my teammates remains unchanged.

I believe that the root cause of the problem does not originate from your WebClient codebase. Your team's support has been appreciated, but I see it more as a gesture of assistance rather than an acknowledgment of any issue with your codebase.

I will continue to work on my end to resolve the issue in collaboration with the IT team. Once the problem is completely resolved, I will provide insights gained from this experience. This will benefit not only me but also future users who may encounter a similar issue. My initial intention was to contribute to troubleshooting resources, not solely to address my own problem. I understand that I serve as a dedicated and unpaid end-user tester for your team, and I take pride in that role.

If you have any feedback or comments, please don't hesitate to share them. I apologize for any inconvenience caused when I provided inaccurate information or noise that may have led to a misunderstanding about the root cause. Nevertheless, we have gained valuable insights into caching with @Cacheable, which I believe adds value to our work.

I want to express my gratitude for all the support, Piere.

**Comment by GlittersGold** [comment] 2023-09-08 14:32
@pderop 
If I have misconstrued any aspect of this situation, and there exists a possibility of rectifying this issue through adjustments to your WebClient core, I would greatly appreciate your guidance.

From the outset, my attention has not been directed towards initiating any alterations to the codebase. My perspective aligns with the belief that the issue at hand is rooted in network-related challenges, as indicated by the error message above.

While I hold the view that our configurations are without fault, I acknowledge that this is a subjective assessment. Should you identify any potential misconfigurations that I may address, I kindly request your insights, guided by the error details I have provided.

Should it become imperative to initiate a new release, we find ourselves in a situation where time constraints do not permit waiting for the update to be reflected in the artifactory. In such a scenario, it may be feasible for me to implement a temporary patch utilizing a build from your hotfix-branch. However, it is my firm belief that your intervention or changes may not be necessary.

I eagerly anticipate your input on this matter, Piere. Your guidance will help us stay on course and address this issue promptly, aligning with any commitments I have made to my teammates.

**Comment by pderop** [comment] 2023-09-08 14:44
@GlittersGold , 

thanks for your message; it feels like this issue would be better suited to [Gitter](https://gitter.im/reactor/reactor-netty). As mentioned in [README](https://github.com/reactor/reactor-netty/#getting-help), we prefer to use GitHub issues only for bugs and enhancements. So, I will close this issue and I suggest that you continue on Gitter if you need to ask general questions about reactor-netty. Of course, if you think you have found a bug somewhere in reactor-netty, don't hesitate to get back to here and open a new GH issue.

thank you.

**Closed by pderop** 2023-09-08 14:44 UTC
Labels: for/user-attention

**Comment by GlittersGold** [comment] 2023-09-12 13:58
Here is our wiretap logs. As of now, there are no occurrences of PrematureCloseExceptions.

`[OUT] "className" : "org.apache.tomcat.util.threads.TaskThread$WrappingRunnable",1
[OUT] "nativeMethod" : false
[OUT] }, {
[OUT] "classLoaderName" : null,
[OUT] "moduleName" : "java.base",
[OUT] "moduleVersion" : "11.0.20",
[OUT] "methodName" : "run",
[OUT] "fileName" : null,
[OUT] "lineNumber" : -1,
[OUT] "className" : "java.lang.Thread",
[OUT] "nativeMethod" : false
[OUT] } ],
[OUT] "message" : "#block terminated with an error",
[OUT] "suppressed" : [ ],
[OUT] "localizedMessage" : "#block terminated with an error"
[OUT] } ],
[OUT] "localizedMessage" : "finishConnect(..) failed: Connection refused: login.microsoftonline.com/0.0.0.0:443; nested exception is io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: login.microsoftonline.com/0.0.0.0:443"`

We must do all troubleshooting on our side. Nevertheless, your feature-owner ideas is valuable, also my feedback could help Netty improve. We could find the root cause more quickly from network settings, my code, and Netty codebase concurrently. Network guys believe there would be proxy server issues. I could override the new code change even if the issue stems from our current reactor-netty.
