### ISSUE TITLE
SSLEngine closed already

### ISSUE THREAD

**Issue by sandeepbyathagururajarao** [reactor/reactor-netty#1318] opened 2020-10-01 16:38 UTC
I have writing a SpringBoot WebFlux app (WebClient) which is talking to another external application by making http calls.
I see many errors in my log files during load testing which says its a warning, don't know if it is.
This issue simulates only after 3-4 hrs of continuous load on the application.
All the errors are on same id "0x86e4c395"

Environment: 
**Spring boot - 2.3.3.RELEASE
spring-boot-starter-reactor-netty - 2.3.3.RELEASE
reactor-netty - 0.9.11.RELEASE
reactor-pool - 0.1.6.RELEASE
reactor-core - 3.3.9.RELEASE**

**Code used to make calls to external application**

```
SslContext sslContext;
ExchangeStrategies exchangeStrategies;
HttpClient httpClient;

exchangeStrategies = ExchangeStrategies.builder()
				.codecs(configurer -> configurer.defaultCodecs().maxInMemorySize(20 * 1024 * 1024)).build();

httpClient = HttpClient.create().tcpConfiguration(tcpClient -> {
				tcpClient = tcpClient.option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 60000);
				tcpClient = tcpClient.doOnConnected(
						conn -> conn.addHandlerLast(new ReadTimeoutHandler(60000, TimeUnit.MILLISECONDS)));
				return tcpClient;
			});
sslContext = SslContextBuilder.forClient().trustManager(InsecureTrustManagerFactory.INSTANCE).build();
httpClient.secure(t -> t.sslContext(sslContext));
WebClient.builder().clientConnector(new ReactorClientHttpConnector(httpClient))
					.exchangeStrategies(exchangeStrategies).build();
```

**The stack trace is as mentioned below.**

2020-10-01T21:35:30.564+0530	0	reactor-http-nio-5		reactor.netty.http.client.HttpClientConnect	WARN	[id: **0x86e4c395**, L:/169.254.0.2:60726 - R:psi-titan/169.254.0.2:443] The connection observed an error
**javax.net.ssl.SSLException: SSLEngine closed already**
	at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:854)
	at io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:811)
	at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:792)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.flush(CombinedChannelDuplexHandler.java:531)
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:125)
	at io.netty.channel.CombinedChannelDuplexHandler.flush(CombinedChannelDuplexHandler.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728)
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:127)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:765)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
	at reactor.netty.http.HttpOperations.lambda$send$0(HttpOperations.java:123)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:96)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2344)
	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.request(FluxContextStart.java:125)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:162)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:103)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:90)
	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onSubscribe(FluxContextStart.java:90)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4213)
	at reactor.core.publisher.FluxConcatIterable$ConcatIterableSubscriber.onComplete(FluxConcatIterable.java:146)
	at reactor.core.publisher.FluxConcatIterable.subscribe(FluxConcatIterable.java:60)
	at reactor.core.publisher.MonoFromFluxOperator.subscribe(MonoFromFluxOperator.java:81)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:171)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:144)
	at reactor.core.publisher.FluxJust$WeakScalarSubscription.request(FluxJust.java:101)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:162)
	at reactor.core.publisher.MonoSingle$SingleSubscriber.request(MonoSingle.java:94)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2152)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2026)
	at reactor.core.publisher.MonoSingle$SingleSubscriber.onSubscribe(MonoSingle.java:114)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:90)
	at reactor.core.publisher.FluxJust.subscribe(FluxJust.java:70)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.netty.http.client.HttpClientConnect$HttpIOHandlerObserver.onStateChange(HttpClientConnect.java:442)
	at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:518)
	at reactor.netty.resources.PooledConnectionProvider$DisposableAcquire.run(PooledConnectionProvider.java:633)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by violetagg** [comment] 2020-10-01 17:19
@sandeepbyathagururajarao What's the purpose of

```
tcpClient = tcpClient.doOnConnected(
	conn -> conn.addHandlerLast(new ReadTimeoutHandler(60000, TimeUnit.MILLISECONDS)));
```

for handling response timeout, connection idle in the pool or else ....

**Comment by sandeepbyathagururajarao** [comment] 2020-10-02 04:50
Yes, The idea behind the code is to handle read and connection timeouts.

**Comment by violetagg** [comment] 2020-10-02 07:09
@sandeepbyathagururajarao Connect timeout you already specified with `.option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 60000);`

for response timeout I would recommend you to use the new API that we exposed `HttpClient.responseTimeout` (#1159)

Another question is there a possibility that the target server closes the connection on some let say configured keep alive timeout?

**Comment by sandeepbyathagururajarao** [comment] 2020-10-02 09:09
@violetagg We are not closing any connection programatically. We are using embedded tomcat as our server
Thanks for the suggestion related to responseTimeout. I will use the same in my code.

**Comment by violetagg** [comment] 2020-10-02 09:16
@sandeepbyathagururajarao If you use Tomcat then you should know that `connectionTimeout` value is applied to `keepAliveTimeout` setting also

http://tomcat.apache.org/tomcat-9.0-doc/config/http.html#Standard_Implementation

```

connectionTimeout | The number of milliseconds this Connector will wait, after accepting a connection, for the request URI line to be presented. Use a value of -1 to indicate no (i.e. infinite) timeout. The default value is 60000 (i.e. 60 seconds) but note that the standard server.xml that ships with Tomcat sets this to 20000 (i.e. 20 seconds). Unless disableUploadTimeout is set to false, this timeout will also be used when reading the request body (if any).
```

```
keepAliveTimeout | The number of milliseconds this Connector will wait for another HTTP request before closing the connection. The default value is to use the value that has been set for the connectionTimeout attribute. Use a value of -1 to indicate no (i.e. infinite) timeout.
```

**Comment by sandeepbyathagururajarao** [comment] 2020-10-02 09:51
@violetagg Do you suggest me not to use connectionTimeout in embedded tomcat of my SpringBoot app. Or should i set it to -1?

**Comment by violetagg** [comment] 2020-10-02 11:02
@sandeepbyathagururajarao 
> Is keepAliveTimeout auto value setting impacting the application and giving "SSLEngine closed already" error?

Yes, having `keepAliveTimeout`, Tomcat closes the connection asynchronous i.e. even when we obtain the connection from the pool and it is not closed, in the next moment it might be closed by Tomcat because of that setting.

So you have two solutions:
If you decide to stay with the default `keepAliveTimeout` or any other value different than `-1`, then you have to configure the `maxIdleTime` on the Reactor Netty's connection pool to be less than the value on the server.
If you decide to configure `keepAliveTimeout` with `-1` then you are OK and no need to configure the connection pool.

**Comment by sandeepbyathagururajarao** [comment] 2020-10-02 11:56
@violetagg Thank you. Will try the changes and keep you posted.

**Comment by sandeepbyathagururajarao** [comment] 2020-10-05 08:39
@violetagg How to set value of maxIdleTime in a spring boot application?

**Comment by violetagg** [comment] 2020-10-05 08:49
@sandeepbyathagururajarao The easiest way is via system property
https://projectreactor.io/docs/netty/release/reference/index.html#_connection_pool

`reactor.netty.pool.maxIdleTime`

**Comment by sandeepbyathagururajarao** [comment] 2020-10-05 09:16
> @sandeepbyathagururajarao The easiest way is via system property
> https://projectreactor.io/docs/netty/release/reference/index.html#_connection_pool
> 
> `reactor.netty.pool.maxIdleTime`

@violetagg 
Will try this change and test. Thanks for reply.

**Comment by sandeepbyathagururajarao** [comment] 2020-10-05 09:39
@violetagg 
I have set -Dreactor.netty.pool.maxIdleTime=6000. This is 6 sec and tomcat connection timeout is set to 60000 (1 min)
Still facing same issue.

**Comment by violetagg** [comment] 2020-10-05 12:26
@sandeepbyathagururajarao Can you provide some reproducible example?

**Comment by sandeepbyathagururajarao** [comment] 2020-10-07 07:43
@violetagg Looks like your suggestion is working out. I have not observed the issue since 2 days. Will observe more and update you. Thanks a lot in helping me fix the issue.

**Comment by violetagg** [comment] 2020-10-20 05:51
@sandeepbyathagururajarao I'm closing this. If there are issues with the proposed solution, we can reopen it.

**Closed by violetagg** 2020-10-20 05:51 UTC
Labels: for/stackoverflow, for/user-attention

**Comment by Tkhengare** [comment] 2021-09-30 19:30
I have writing a SpringBoot (WebClient) which is talking to another external application by making http calls.
Exception : 
[...] The connection observed an error

io.netty.handler.timeout.ReadTimeoutException: null
 I have set System.setproperty("reactor.netty.pool.maxIdelTime", "5000" But didn't resolve the issue.
