### ISSUE TITLE
The number of TCP connections still increase after update spring boot version unless restart spring gateway.

### ISSUE THREAD

**Issue by hcl78184889** [reactor/reactor-netty#1358] opened 2020-10-29 15:56 UTC
spring boot 2.3.3
spring cloud Hoxton.SR7

![tcp connections](https://user-images.githubusercontent.com/6574953/97598875-60da1200-1a42-11eb-821f-6efd7447c236.png)

Source code:

[gateway.zip](https://github.com/reactor/reactor-netty/files/5459663/gateway.zip)

It looks like be the react netty issue，also can refer to  below issue for detail:
https://github.com/spring-projects/spring-boot/issues/23967#issue-732408186

**Comment by violetagg** [comment] 2020-10-29 16:13
@hcl78184889 I see the `gateway` project but how this can be reproduced?

**Comment by hcl78184889** [comment] 2020-10-29 16:19
When many people visit, greater than 10000 connections every day. On our prod env, this issue occur.

**Comment by hcl78184889** [comment] 2020-10-29 16:21
What other information do you need. Let me try to provide

**Comment by violetagg** [comment] 2020-10-29 16:29
> When many people visit, greater than 10000 connections every day. On our prod env, this issue occur.

By default Reactor Netty runs with a connection pool per remote address with a limit with max connections 500 and I do not see any http client configuration.

In one of the other issues that you opened you mention the code below (https://github.com/spring-projects/spring-boot/issues/22245#issue-652170800). Is this still relevant?

```
The test code:
@RestController
@slf4j
public class WebClientController {

@Autowired
private WebClient.Builder webClientBuilder;

@PostMapping(value = "/wb")
public Mono<String> wbTest(@PathVariable(required = false) String action) {
    return webClientBuilder.build().get().uri("http://remoteIP:remotePort/privaters/jwks/pub")
            .retrieve()
            .bodyToMono(String.class);
}
}
```

**Comment by hcl78184889** [comment] 2020-10-29 16:48
We use JS(vue) link the gateway server on prod. Before only a test code

**Comment by hcl78184889** [comment] 2020-10-29 16:57
self.$http.post('/sms/verifyIdyCode', params).then(function (res) {
            if("0000" === res.data.code){
              self.loginApply(params);
            }else{
              self.topTips= 'top:555px';
              self.errorTips = '验证码错误';
            }
          }).catch(function (err) {
            self.topTips= 'top:555px';
            self.errorTips = err && err.data && err.data.desc || '验证码错误';
          });

**Comment by violetagg** [comment] 2020-10-29 17:16
>  10000 connections every day

Should not be an issue and we have tests that test for connection leaks.
Most probably your use case is different or the issue is somewhere else. In order to investigate further we need a reproducible example.

**Comment by hcl78184889** [comment] 2020-10-29 18:37
If my filters has some issue or yml config?

**Comment by hcl78184889** [comment] 2020-10-29 18:45
Maybe the issue is the websocket. Could you check websocket.

**Comment by hcl78184889** [comment] 2020-10-29 18:46
On my prod env, websocket gateway has many tcp connections.

**Comment by hcl78184889** [comment] 2020-10-29 18:49
Below is the test code:
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>websocket通讯</title>
</head>
<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.js"></script>
<script>
    var socket;
    function openSocket() {
        if(typeof(WebSocket) == "undefined") {
            console.log("您的浏览器不支持WebSocket");
        }else{
            console.log("您的浏览器支持WebSocket");
			var socketUrl = "ws://localhost:8667/websocket/app";
            socket = new WebSocket(socketUrl,['eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZSI6IjEzMzMzMzMzMzMzIiwiYXBwTG9naW4iOiJ0cnVlIiwibG9naW5OYW1lIjoia20wMTAxIiwiaWQiOiIxMjM1IiwidGltZSI6MTU5NTIxMTg2ODY2NCwiaWF0IjoxNTk1MjExODY4fQ.ZXeeYrWt39CZUEvrYsJIyEQ4u1MfiwgAn40CDCOEWLI']);
			//打开事件
            socket.onopen = function() {
                console.log("websocket已打开");
                //socket.send("这是来自客户端的消息" + location.href + new Date());
            };
            //获得消息事件
            socket.onmessage = function(msg) {
                console.log(msg.data);
                //发现消息进入    开始处理前端触发逻辑
            };
            //关闭事件
            socket.onclose = function(event) {
                console.log("websocket已关闭");
            };
            //发生了错误事件
            socket.onerror = function(event) {
                console.log("websocket发生了错误，"+event);
            }
        }
    }
    function sendMessage() {
        if(typeof(WebSocket) == "undefined") {
            console.log("您的浏览器不支持WebSocket");
        }else {
            console.log("您的浏览器支持WebSocket");
            console.log('{"toUserId":"'+$("#toUserId").val()+'","contentText":"'+$("#contentText").val()+'"}');
            socket.send('{"toUserId":"'+$("#toUserId").val()+'","contentText":"'+$("#contentText").val()+'"}');
        }
    }
</script>
<body>

<p>【toUserId】：<div><input id="toUserId" name="toUserId" type="text" value="1235"></div>
<p>【toUserId】：<div><input id="contentText" name="contentText" type="text" value="hello websocket"></div>
<p>【操作】：<div><a onclick="openSocket()">开启socket</a></div>
<p>【操作】：<div><a onclick="sendMessage()">发送消息</a></div>
</body>

</html>

**Comment by gonwan** [comment] 2020-11-02 12:40
@hcl78184889 Will you try the workaround here? https://github.com/spring-cloud/spring-cloud-gateway/issues/1985

**Comment by violetagg** [comment] 2020-11-02 19:34
@hcl78184889 Please specify which TCP connections are increasing - TCP1 or TCP2?

client --TCP1--> Spring Gateway --TCP2--> target service

**Comment by hcl78184889** [comment] 2020-11-03 01:30
TCP1

**Comment by hcl78184889** [comment] 2020-11-03 05:25
@gonwan ，thanks，这个问题困扰太久了

**Comment by violetagg** [comment] 2020-11-03 07:50
@hcl78184889 Then apply the configuration from https://github.com/spring-cloud/spring-cloud-gateway/issues/1985 and tell us the result

**Comment by hcl78184889** [comment] 2020-11-03 07:55
@violetagg ，OK, thanks. Let me try.

**Comment by hcl78184889** [comment] 2020-11-04 00:34
![image](https://user-images.githubusercontent.com/6574953/98055339-3b04a100-1e78-11eb-8cf7-bf83ccca2971.png)
@violetagg @gonwan , now, I think the issue is solved. Very thanks.

**Comment by violetagg** [comment] 2020-11-04 06:52
@hcl78184889 Thanks. I'm closing this issue as duplicate to #1345. I'll try to schedule #1345 for next 0.9.x release.

**Closed by violetagg** 2020-11-04 06:52 UTC
Labels: for/user-attention, type/bug

**Comment by hcl78184889** [comment] 2020-11-04 06:54
@violetagg , OK
