### ISSUE TITLE
HTTP/2 streams leak after new HTTP/2 pool implementation in 1.0.14

### ISSUE THREAD

**Issue by conet** [reactor/reactor-netty#2018] opened 2022-02-04 14:33 UTC
We have a spring boot application doing a lot of HTTP/2 calls and once we upgraded to the version that brought in `reactor-netty:1.0.14` we noticed pool acquire timeouts after a few hours of operation. Reverting to `reactor-netty:1.0.13` fixed the problem so we started suspecting the new HTTP/2 connection implementation [released in 1.0.14](https://github.com/reactor/reactor-netty/releases/tag/v1.0.14).

While the above information is pretty weak for such a bug report we did manage to do a [demo spring boot project](https://github.com/conet/spring-webflux-sample) that reproduces the problem.

## Expected Behavior
The HTTP/2 connection pool should be stable and should not leak HTTP/2 streams. 

## Actual Behavior
The HTTP/2 connection pool leaks HTTP/2 streams eventually resulting in `reactor.netty.internal.shaded.reactor.pool.PoolAcquireTimeoutException` (when configured). 

## Steps to Reproduce
The [demo spring boot project](https://github.com/conet/spring-webflux-sample) contains the steps, just start the app, then do some http calls that end up doing WebClient calls and monitor the pool metrics in the meantime.

[WebClient is used](https://github.com/conet/spring-webflux-sample/blob/master/src/main/java/com/sample/webflux/controller/Http2TestController.java#L28) in a manner that some requests timeout, maybe the issue is not in `reactor-netty` but as far as I can tell it's pretty straight forward usage without anything special, it should not bring down the HTTP/2 connection pool.

These are leaked streams I think because they are not reclaimed even after the `maxLifeTime` setting:
```
{
    "availableTags": [
        {
            "tag": "name",
            "values": [
                "http2.http2test"
            ]
        },
        {
            "tag": "remote.address",
            "values": [
                "httpbin.org:443"
            ]
        },
        {
            "tag": "id",
            "values": [
                "1435426863"
            ]
        }
    ],
    "baseUnit": null,
    "description": "The number of the active HTTP/2 streams",
    "measurements": [
        {
            "statistic": "VALUE",
            "value": 398.0
        }
    ],
    "name": "reactor.netty.connection.provider.active.streams"
}
```

I also see this in the logs:
```
org.springframework.web.reactive.function.client.WebClientRequestException: Pool#acquire(Duration) has been pending for more than the configured timeout of 1000ms; nested exception is reactor.netty.internal.shaded.reactor.pool.PoolAcquireTimeoutException: Pool#acquire(Duration) has been pending for more than the configured timeout of 1000ms
	at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:141) ~[spring-webflux-5.3.15.jar:5.3.15]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ Request to GET https://httpbin.org/delay/3 [DefaultWebClient]
Original Stack Trace:
		at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:141) ~[spring-webflux-5.3.15.jar:5.3.15]
		at reactor.core.publisher.MonoErrorSupplied.subscribe(MonoErrorSupplied.java:55) ~[reactor-core-3.4.14.jar:3.4.14]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4400) ~[reactor-core-3.4.14.jar:3.4.14]
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103) ~[reactor-core-3.4.14.jar:3.4.14]
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222) ~[reactor-core-3.4.14.jar:3.4.14]
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222) ~[reactor-core-3.4.14.jar:3.4.14]
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222) ~[reactor-core-3.4.14.jar:3.4.14]
		at reactor.core.publisher.MonoNext$NextSubscriber.onError(MonoNext.java:93) ~[reactor-core-3.4.14.jar:3.4.14]
		at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onError(MonoFlatMapMany.java:204) ~[reactor-core-3.4.14.jar:3.4.14]
		at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124) ~[reactor-core-3.4.14.jar:3.4.14]
		at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.whenError(FluxRetryWhen.java:225) ~[reactor-core-3.4.14.jar:3.4.14]
		at reactor.core.publisher.FluxRetryWhen$RetryWhenOtherSubscriber.onError(FluxRetryWhen.java:274) ~[reactor-core-3.4.14.jar:3.4.14]
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:415) ~[reactor-core-3.4.14.jar:3.4.14]
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:251) ~[reactor-core-3.4.14.jar:3.4.14]
		at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:491) ~[reactor-core-3.4.14.jar:3.4.14]
		at reactor.core.publisher.EmitterProcessor.tryEmitNext(EmitterProcessor.java:299) ~[reactor-core-3.4.14.jar:3.4.14]
		at reactor.core.publisher.SinkManySerialized.tryEmitNext(SinkManySerialized.java:100) ~[reactor-core-3.4.14.jar:3.4.14]
		at reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:27) ~[reactor-core-3.4.14.jar:3.4.14]
		at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onError(FluxRetryWhen.java:190) ~[reactor-core-3.4.14.jar:3.4.14]
		at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:194) ~[reactor-core-3.4.14.jar:3.4.14]
		at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect$ClientTransportSubscriber.onError(HttpClientConnect.java:304) ~[reactor-netty-http-1.0.15.jar:1.0.15]
		at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:194) ~[reactor-core-3.4.14.jar:3.4.14]
		at reactor.netty.http.client.Http2ConnectionProvider$DisposableAcquire.onError(Http2ConnectionProvider.java:251) ~[reactor-netty-http-1.0.15.jar:1.0.15]
		at reactor.netty.http.client.Http2Pool$Borrower.run(Http2Pool.java:565) ~[reactor-netty-http-1.0.15.jar:1.0.15]
		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.4.14.jar:3.4.14]
		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.4.14.jar:3.4.14]
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
		at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
Caused by: reactor.netty.internal.shaded.reactor.pool.PoolAcquireTimeoutException: Pool#acquire(Duration) has been pending for more than the configured timeout of 1000ms
	at reactor.netty.http.client.Http2Pool$Borrower.run(Http2Pool.java:565) ~[reactor-netty-http-1.0.15.jar:1.0.15]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.4.14.jar:3.4.14]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.4.14.jar:3.4.14]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
```

## Your Environment

* Reactor version(s) used: `1.0.15`
* Other relevant libraries versions (eg. `netty`, ...): spring boot `2.6.3`
* JVM version (`java -version`):
```
$ java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
```
* OS and version (eg. `uname -a`): `Darwin MacBook-Pro 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64`

**Comment by pderop** [comment] 2022-02-04 15:31
Hi @conet ,

Thanks for your reproducer scenario, I tested it, but using latest 1.0.16-SNAPSHOT the problem is not reproduced anymore. It's most likely a duplicate of the PR #2014 which @violetagg just fixed very recently.

I'm closing this one, but feel free to reopen if necessary.

**Closed by pderop** 2022-02-04 15:31 UTC
Labels: type/bug, status/need-triage
