### ISSUE TITLE
Http2Pool acquire leaks

### ISSUE THREAD

**Issue by knuclechan** [reactor/reactor-netty#2828] opened 2023-06-09 08:53 UTC
When using httpClient, the acquire variable at Http2Pool does not drop after use. This occurs in concurrent situation, while does not occur in non-concurrent one.
And also the maxConnections seems not respected (See the image below. The acquired number goes sky rocket high, but things keeps running). But it seems there's no noticeable memory leak.

Running on Linux server
![Pic](https://github.com/reactor/reactor-netty/assets/62231462/7f04692b-a65d-428b-9213-880351dc3459)

Runnng on local PC (debugger state after 10,000 requests)
![Pic](https://github.com/reactor/reactor-netty/assets/62231462/68247d93-b21d-4698-8123-c2359b04bbf1)

Since the inactivity of a pool is depending on the acquire size. The pool will never be disposed as well.
```java
	public boolean isInactiveForMoreThan(Duration duration) {
		return pendingAcquireSize() == 0 && allocatedSize() == 0
				&& secondsSinceLastInteraction() >= duration.getSeconds();
	}
```

Another observation is that the leak will slow down if the slot number (connection) increases

## Expected Behavior
acquired should be back to 0 after all requests is done

## Actual Behavior
acquired does not drop

## Steps to Reproduce

Simply fire concurrent request to a http2 server.
I set the idle / inactive time short in order to show that the high acquire number is not because of connection keep alive.

```java
	public static void main(String[] args) throws Exception {
		NettyMeterRegistrar meterRegistrar = new NettyMeterRegistrar(); // this is the statistic collector written by me

		ConnectionProvider connProvider = ConnectionProvider.builder("internalHttpClient")
				.maxConnections(100)
				.maxIdleTime(Duration.ofSeconds(1L))
				.maxLifeTime(Duration.ofMinutes(10L))
				.evictInBackground(Duration.ofSeconds(1L))
				.pendingAcquireMaxCount(-1)
				.pendingAcquireTimeout(Duration.ofSeconds(5L))
				.disposeInactivePoolsInBackground(Duration.ofSeconds(1L), Duration.ofSeconds(1L)) // in order to dispose the pool
				.disposeTimeout(Duration.ofSeconds(1L))
				.metrics(true)
				.build();
		
		HttpClient httpClient = HttpClient.create(connProvider)
				.secure()
				.compress(true)
				.protocol(HttpProtocol.H2, HttpProtocol.HTTP11)
				.responseTimeout(Duration.ofMillis(10000L))
				.option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 5000);

		URI uri = URI.create("https://SOME_URL_FOR_TESTING");
		
		Flux.range(0, 1000) //fires 1000 requests
			.flatMap((i) -> {
				return httpClient
					.get()
					.uri(uri)
					.response()
					.doOnNext((i) -> {
						ConnectionPoolMetrics metric = meterRegistrar.getAggregatedMetrics();
						System.out.println("Allocated: " + metric.allocatedSize() + ", Acquired: " + metric.acquiredSize());
					});
			}, 10) //concurrency
			.then()
			.subscribeOn(Schedulers.boundedElastic())
			.block();
		
		Thread.sleep(3000L); // wait for evictation
		
		ConnectionPoolMetrics metric = meterRegistrar.getAggregatedMetrics();
		System.out.println("FINAL Allocated: " + metric.allocatedSize() + ", Acquired: " + metric.acquiredSize());
	}
```

```java
public class NettyMeterRegistrar implements MeterRegistrar {

	private final Queue<ConnectionPoolMetrics> metricsList = new ConcurrentLinkedQueue<>();
	
	
	@Override
	public void registerMetrics(String poolName, String id, SocketAddress remoteAddress, ConnectionPoolMetrics metrics) {
		metricsList.add(metrics);
	}
	
	public MyConnectionPoolMetrics getAggregatedMetrics() {
		return new MyConnectionPoolMetrics(metricsList);
	}
	
	
	
	public class MyConnectionPoolMetricsimplements ConnectionPoolMetrics {

		private int pendingAcquire;
		private int allocated;
		private int acquired;
		
		public MyConnectionPoolMetrics(Queue<ConnectionPoolMetrics> metricsList) {
			for (ConnectionPoolMetrics metric : metricsList) {
				pendingAcquire += metric.pendingAcquireSize();
				allocated += metric.allocatedSize();
				acquired += metric.acquiredSize();
			}
		}

		public int pendingAcquireSize() {
			return pendingAcquire;
		}
		
		public int maxPendingAcquireSize() {
			return -1;
		}
		
		public int maxAllocatedSize() {
			return -1;
		}
		
		public int idleSize() {
			return allocated - acquired;
		}
		
		public int allocatedSize() {
			return allocated;
		}
		
		public int acquiredSize() {
			return acquired;
		}
	}
}
```

## Your Environment
Tried on both PC and Linux, Openjdk 17
4.1.72.Final  (Also tried 4.1.93.Final)

**Comment by violetagg** [comment] 2023-06-09 16:48
@knuclechan You are specifying Netty version 4.1.72.Final/4.1.93.Final, what about Reactor Netty version? Which one are you using for testing?

**Comment by violetagg** [comment] 2023-06-09 18:49
@knuclechan I tested with the latest Reactor Netty version 1.0.32/1.1.7 and I cannot reproduce the issue.

**Comment by violetagg** [comment] 2023-06-13 11:50
@knuclechan Nice! I'm closing this one.

**Closed by violetagg** 2023-06-13 11:50 UTC
Labels: type/bug, for/user-attention
