### ISSUE TITLE
Additional Empty Dataframe in response for all HTTP Verbs

### ISSUE THREAD

**Issue by joyfulnikhil** [reactor/reactor-netty#2569] opened 2022-11-09 10:34 UTC
**Dependencies**
Spring Cloud Gateway - 3.0.7
Spring Boot - 2.7.6
Reactor netty - 1.0.24
Netty - 4.1.84.Final
OS - Cent OS / Linux

We are using Spring cloud Gateway and it is observed that the response from the SCG contains 2 Data Frames(First with Data, endStream=false, and second with No Data, endStream=true). This happens for all HTTP Verbs, when the backend sends a response.
For logging purposes, I have overridden the Http2FrameCodec#write method with some system outs.
Line No 301:  System.out.println("Data frame: "+dataFrame);
Line No 306: System.out.println("Header frame: "+headersFrame);

This is the output when a response is sent back from SCG .

Header frame: DefaultHttp2HeadersFrame(stream=1, headers=DefaultHttp2Headers[:status: 202, accept: */*, content-type: application/json, x-request-id: 9909005184, hop-by-hop-id: xyz, user-agent: PCF-10.75.175.222:0417 fqdn, forwarded: proto=http;host="localhost:8088";for="127.0.0.1:55809", x-forwarded-for: 127.0.0.1, x-forwarded-proto: http, x-forwarded-port: 8088, x-forwarded-host: localhost:8088, content-length: 457, x-custom-header: Jojo], endStream=false, padding=0)

**Data frame: DefaultHttp2DataFrame(stream=1, content=UnpooledSlicedByteBuf(ridx: 0, widx: 457, cap: 457/457, unwrapped: PooledUnsafeDirectByteBuf(ridx: 754, widx: 754, cap: 2048)), endStream=false, padding=0)**

**Data frame: DefaultHttp2DataFrame(stream=1, content=EmptyByteBufBE, endStream=true, padding=0)**

Request your assistance to understand whether this is expected behavior or not. The clients invoking SCG are breaking due to 
an additional DataFrame being sent.

Information Regarding the project:
The destination for SCG has been configured in application.yaml. 
It contains 2 Global filters to add some headers.
The overridden Http2FrameCodec can be found in io.netty.handler.codec.http2 folder under the java package.

Attaching the SCG Project for reference

[demo-test.zip](https://github.com/reactor/reactor-netty/files/9970012/demo-test.zip)

**Comment by pderop** [comment] 2022-11-10 15:41
Hi @joyfulnikhil ,

Thanks for the reproducer, I could reproduce easily. it seems that what happens is the following:

- the GW receives a full response from the upstream destination server
- at this point, the GW writes the full response to the client with a **Flux**, not a Mono (even if the response is full)
- So, because a Flux is used, then  when the Flux completes, an empty DATA frame header will be sent to the client (with END_STREAM flag). This is done like this because when a response is sent using a Flux, the only way to know when the last response chunk is sent is when the Flux completes, so at this point, reactor-netty sends the empty DATA frame.

Let me give a concrete example: say you have a server that responds to the client using a Mono, like this:

```
		disposableServer =
				createServer()
						.protocol(HttpProtocol.H2C)
						.port(9999)
						.handle((req, res) -> res.send(ByteBufMono.fromString(Mono.just("test"))))
						.bindNow(Duration.ofSeconds(30));
``` 
Then in this case, the following message will be returned to the client, without an empty DATA frame message (it's because a Mono is used, when a Mono is used reactor-netty knows that a full response can be sent, so , no need to send an empty DATA frame message. Pay attention to the packet 13: a full response is sent to the client, and the END_STREAM flag is present in the DATA frame of the response body ("test"):

<img width="1728" alt="Screenshot 2022-11-10 at 16 17 20" src="https://user-images.githubusercontent.com/650758/201133852-2caa32fd-4850-4cac-953a-c1dde2f9c52d.png">


Now, let's consider a use case where a response is sent to the client using a Flux, not a Mono:

```
		disposableServer =
				createServer()
						.protocol(HttpProtocol.H2C)
						.port(9999)
						.handle((req, res) -> res.send(ByteBufFlux.fromString(Mono.just("test"))))
						.bindNow(Duration.ofSeconds(30));

```
In this case, the following message will be returned: pay attention to the packet 17, this is an empty DATA frame with END_STREAM flag which is sent when the Flux completes:

<img width="1727" alt="Screenshot 2022-11-10 at 16 21 29" src="https://user-images.githubusercontent.com/650758/201134752-10e2e86f-e62f-4116-b302-7c743b659b25.png">

So, in the Spring Cloud Gateway, it's likely that the gateway is sending a response to the client **always** using a Flux, and not a Mono. For example here: in the GW version 3.0.7, in [NettyWriteResponseFilter.filter](https://github.com/spring-cloud/spring-cloud-gateway/blob/v3.0.7/spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/filter/NettyWriteResponseFilter.java#L84) method, then we see that a Flux is always used. So, now, I'm not sure if sending an empty DATA frame header is violating the spec, maybe, I did not check, but I suggest that you create a new issue for the GW team, and ask them to try to check if the response is full before sending it to the client; and in this case, use a Mono instead of a Flux. That will avoid any last empty DATA frame to be sent.

I'm closing this issue, but don't hesitate to reopen if discussion must be continued here.

thanks !

**Comment by pderop** [comment] 2022-11-10 15:42
closing this one, of course reopen if you need, thank you.

**Closed** 2022-11-10 15:42 UTC
Labels: status/invalid, for/spring-cloud-gateway

**Comment by pderop** [comment] 2022-11-10 15:45
it's possible that this issue is a duplicate on this unresolved old issue: 
https://github.com/reactor/reactor-netty/issues/2309
