### ISSUE TITLE
Intermittent PrematureCloseException occurs with HTTP client

### ISSUE THREAD

**Issue by ukayani** [reactor/reactor-netty#1331] opened 2020-10-09 20:18 UTC
In our production service we are seeing intermittent PrematureCloseException when using the HTTP client.

The request being made is a simple HTTP GET request, however we also see this for POST requests as well:

```
16:06:21.213 [id: A, L:/yyy - R:xxx] Channel acquired, now 291 active connections and 85 inactive connections
16:06:21.213 [id: A, L:/yyy - R:xxx] onStateChange(GET{uri=/api/test, connection=PooledConnection{channel=[id: A, L:/yyy - R:xxx]}}, [request_prepared])
16:06:23.105 [id: A, L:/yyy - R:xxx] onStateChange(GET{uri=/api/test, connection=PooledConnection{channel=[id: A, L:/yyy - R:xxx]}}, [request_sent])
16:06:23.108 [id: A, L:/yyy ! R:xxx] Channel closed, now 441 active connections and 13 inactive connections
16:06:23.814 [id: A, L:/yyy ! R:xxx] onStateChange(GET{uri=/api/test, connection=PooledConnection{channel=[id: A, L:/yyy ! R:xxx]}}, [response_incomplete])
16:06:23.814 [id: A, L:/yyy ! R:xxx] The connection observed an error
reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
```

In the logs what i see is:

1. connection is used for a successful exchange
1. connection is released back to pool
1. connection is acquired again (within a few hundred microseconds)
1. request is prepared for the connection
1. request is sent via connection
1. connection is closed (within a few hundred microseconds)
1. response incomplete state
1. connection premature close exception

Initially, i suspected that the peer (a load balancer) was initiating the connection close but looking at the tcp dump this does not seem to be the case.

#### Close with FIN
In **Dump A** below, is an exchange which resulted in reactor logs outputting a `PrematureCloseException`
`yyy` denotes the service
`xxx` denotes the Load balancer

You can see several successful exchanges and at the end you can see (snippet from dump A):

```
2020-10-09 11:50:53.991144 IP yyy.46348 > xxx.http: Flags [P.], seq 366918:368165, ack 1113622, win 1384, options [nop,nop,TS val 3964685472 ecr 60968415], length 1247: HTTP: GET /api/test?a=g&c=i HTTP/1.1
2020-10-09 11:50:53.994771 IP yyy.46348 > xxx.http: Flags [F.], seq 368165, ack 1113622, win 1384, options [nop,nop,TS val 3964685476 ecr 60968415], length 0
2020-10-09 11:50:53.995161 IP xxx.http > yyy.46348: Flags [F.], seq 1113622, ack 368166, win 422, options [nop,nop,TS val 60968427 ecr 3964685472], length 0
2020-10-09 11:50:53.995169 IP yyy.46348 > xxx.http: Flags [.], ack 1113623, win 1384, options [nop,nop,TS val 3964685476 ecr 60968427], length 0
```

1. reactor client sends a GET
1. reactor sends a FIN ack
1. LB responds with a FIN ack
1. reactor responds with ack

#### Close with RST

In **Dump B** below, similarly there are several successful exchanges before a close

1. reactor client sends a POST with a body
1. LB responds with ack
1. reactor sends a FIN ack
1. LB responds with an HTTP 201 with a body (json)
1. reactor sends a RST
1. LB responds with a FIN
1. reactor sends a RST again

**DUMP A**

```
2020-10-09 11:50:53.453652 IP yyy.46348 > xxx.http: Flags [P.], seq 359483:360698, ack 1089852, win 1384, options [nop,nop,TS val 3964684935 ecr 60968277], length 1215: HTTP: GET /api/test?a=b&c=d HTTP/1.1
2020-10-09 11:50:53.458571 IP xxx.http > yyy.46348: Flags [P.], seq 1089852:1095705, ack 360698, win 422, options [nop,nop,TS val 60968293 ecr 3964684935], length 5853: HTTP: HTTP/1.1 200 OK
2020-10-09 11:50:53.458587 IP xxx.http > yyy.46348: Flags [P.], seq 1095705:1096237, ack 360698, win 422, options [nop,nop,TS val 60968293 ecr 3964684935], length 532: HTTP
2020-10-09 11:50:53.458610 IP yyy.46348 > xxx.http: Flags [.], ack 1096237, win 1384, options [nop,nop,TS val 3964684940 ecr 60968293], length 0
2020-10-09 11:50:53.587931 IP yyy.46348 > xxx.http: Flags [P.], seq 360698:361902, ack 1096237, win 1384, options [nop,nop,TS val 3964685069 ecr 60968293], length 1204: HTTP: POST /api/test HTTP/1.1
2020-10-09 11:50:53.588057 IP yyy.46348 > xxx.http: Flags [P.], seq 361902:361955, ack 1096237, win 1384, options [nop,nop,TS val 3964685069 ecr 60968293], length 53: HTTP
2020-10-09 11:50:53.588402 IP xxx.http > yyy.46348: Flags [.], ack 361955, win 422, options [nop,nop,TS val 60968325 ecr 3964685069], length 0
2020-10-09 11:50:53.604656 IP xxx.http > yyy.46348: Flags [P.], seq 1096237:1096405, ack 361955, win 422, options [nop,nop,TS val 60968329 ecr 3964685069], length 168: HTTP: HTTP/1.1 201 Created
2020-10-09 11:50:53.645536 IP yyy.46348 > xxx.http: Flags [.], ack 1096405, win 1384, options [nop,nop,TS val 3964685127 ecr 60968329], length 0
2020-10-09 11:50:53.711131 IP yyy.46348 > xxx.http: Flags [P.], seq 361955:363210, ack 1096405, win 1384, options [nop,nop,TS val 3964685192 ecr 60968329], length 1255: HTTP: GET /api/test?a=c&c=e HTTP/1.1
2020-10-09 11:50:53.716045 IP xxx.http > yyy.46348: Flags [P.], seq 1096405:1097072, ack 363210, win 422, options [nop,nop,TS val 60968357 ecr 3964685192], length 667: HTTP: HTTP/1.1 200 OK
2020-10-09 11:50:53.716068 IP yyy.46348 > xxx.http: Flags [.], ack 1097072, win 1384, options [nop,nop,TS val 3964685197 ecr 60968357], length 0
2020-10-09 11:50:53.841469 IP yyy.46348 > xxx.http: Flags [P.], seq 363210:364428, ack 1097072, win 1384, options [nop,nop,TS val 3964685323 ecr 60968357], length 1218: HTTP: GET /api/test?a=d&c=f HTTP/1.1
2020-10-09 11:50:53.850991 IP xxx.http > yyy.46348: Flags [P.], seq 1097072:1100329, ack 364428, win 422, options [nop,nop,TS val 60968391 ecr 3964685323], length 3257: HTTP: HTTP/1.1 200 OK
2020-10-09 11:50:53.851023 IP yyy.46348 > xxx.http: Flags [.], ack 1100329, win 1384, options [nop,nop,TS val 3964685332 ecr 60968391], length 0
2020-10-09 11:50:53.900388 IP yyy.46348 > xxx.http: Flags [P.], seq 364428:365670, ack 1100329, win 1384, options [nop,nop,TS val 3964685382 ecr 60968391], length 1242: HTTP: GET /api/test?a=e&c=g HTTP/1.1
2020-10-09 11:50:53.906557 IP xxx.http > yyy.46348: Flags [P.], seq 1100329:1106456, ack 365670, win 422, options [nop,nop,TS val 60968405 ecr 3964685382], length 6127: HTTP: HTTP/1.1 200 OK
2020-10-09 11:50:53.906593 IP yyy.46348 > xxx.http: Flags [.], ack 1106456, win 1384, options [nop,nop,TS val 3964685388 ecr 60968405], length 0
2020-10-09 11:50:53.935284 IP yyy.46348 > xxx.http: Flags [P.], seq 365670:366918, ack 1106456, win 1384, options [nop,nop,TS val 3964685417 ecr 60968405], length 1248: HTTP: GET /api/test?a=f&c=h HTTP/1.1
2020-10-09 11:50:53.946045 IP xxx.http > yyy.46348: Flags [P.], seq 1106456:1113622, ack 366918, win 422, options [nop,nop,TS val 60968415 ecr 3964685417], length 7166: HTTP: HTTP/1.1 200 OK
2020-10-09 11:50:53.946078 IP yyy.46348 > xxx.http: Flags [.], ack 1113622, win 1384, options [nop,nop,TS val 3964685427 ecr 60968415], length 0
2020-10-09 11:50:53.991144 IP yyy.46348 > xxx.http: Flags [P.], seq 366918:368165, ack 1113622, win 1384, options [nop,nop,TS val 3964685472 ecr 60968415], length 1247: HTTP: GET /api/test?a=g&c=i HTTP/1.1
2020-10-09 11:50:53.994771 IP yyy.46348 > xxx.http: Flags [F.], seq 368165, ack 1113622, win 1384, options [nop,nop,TS val 3964685476 ecr 60968415], length 0
2020-10-09 11:50:53.995161 IP xxx.http > yyy.46348: Flags [F.], seq 1113622, ack 368166, win 422, options [nop,nop,TS val 60968427 ecr 3964685472], length 0
2020-10-09 11:50:53.995169 IP yyy.46348 > xxx.http: Flags [.], ack 1113623, win 1384, options [nop,nop,TS val 3964685476 ecr 60968427], length 0
```

**DUMP B**

```
2020-10-09 11:50:58.795051 IP yyy.42486 > xxx.http: Flags [P.], seq 309202:310491, ack 1024376, win 1384, options [nop,nop,TS val 3488328281 ecr 14229998], length 1289: HTTP: GET /api/test?a=1&b=2 HTTP/1.1
2020-10-09 11:50:58.800435 IP xxx.http > yyy.42486: Flags [P.], seq 1024376:1029202, ack 310491, win 422, options [nop,nop,TS val 14230013 ecr 3488328281], length 4826: HTTP: HTTP/1.1 200 OK
2020-10-09 11:50:58.800480 IP yyy.42486 > xxx.http: Flags [.], ack 1029202, win 1384, options [nop,nop,TS val 3488328287 ecr 14230013], length 0
2020-10-09 11:50:58.813705 IP yyy.42486 > xxx.http: Flags [P.], seq 310491:311702, ack 1029202, win 1384, options [nop,nop,TS val 3488328300 ecr 14230013], length 1211: HTTP: GET /api/test?a=1&b=2 HTTP/1.1
2020-10-09 11:50:58.818626 IP xxx.http > yyy.42486: Flags [P.], seq 1029202:1033769, ack 311702, win 422, options [nop,nop,TS val 14230018 ecr 3488328300], length 4567: HTTP: HTTP/1.1 200 OK
2020-10-09 11:50:58.818675 IP yyy.42486 > xxx.http: Flags [.], ack 1033769, win 1384, options [nop,nop,TS val 3488328305 ecr 14230018], length 0
2020-10-09 11:50:58.850787 IP yyy.42486 > xxx.http: Flags [P.], seq 311702:312872, ack 1033769, win 1384, options [nop,nop,TS val 3488328337 ecr 14230018], length 1170: HTTP: POST /api/test HTTP/1.1
2020-10-09 11:50:58.857359 IP yyy.42486 > xxx.http: Flags [P.], seq 312872:312925, ack 1033769, win 1384, options [nop,nop,TS val 3488328344 ecr 14230018], length 53: HTTP
2020-10-09 11:50:58.857791 IP xxx.http > yyy.42486: Flags [.], ack 312925, win 422, options [nop,nop,TS val 14230028 ecr 3488328337], length 0
2020-10-09 11:50:58.864387 IP xxx.http > yyy.42486: Flags [P.], seq 1033769:1033937, ack 312925, win 422, options [nop,nop,TS val 14230029 ecr 3488328337], length 168: HTTP: HTTP/1.1 201 Created
2020-10-09 11:50:58.905536 IP yyy.42486 > xxx.http: Flags [.], ack 1033937, win 1384, options [nop,nop,TS val 3488328392 ecr 14230029], length 0
2020-10-09 11:50:58.910198 IP yyy.42486 > xxx.http: Flags [P.], seq 312925:314211, ack 1033937, win 1384, options [nop,nop,TS val 3488328397 ecr 14230029], length 1286: HTTP: GET /api/test?a=1&b=2 HTTP/1.1
2020-10-09 11:50:58.917398 IP xxx.http > yyy.42486: Flags [P.], seq 1033937:1038503, ack 314211, win 422, options [nop,nop,TS val 14230042 ecr 3488328397], length 4566: HTTP: HTTP/1.1 200 OK
2020-10-09 11:50:58.919278 IP yyy.42486 > xxx.http: Flags [.], ack 1038503, win 1384, options [nop,nop,TS val 3488328406 ecr 14230042], length 0
2020-10-09 11:50:58.939246 IP yyy.42486 > xxx.http: Flags [P.], seq 314211:315420, ack 1038503, win 1384, options [nop,nop,TS val 3488328426 ecr 14230042], length 1209: HTTP: POST /api/test HTTP/1.1
2020-10-09 11:50:58.939411 IP yyy.42486 > xxx.http: Flags [P.], seq 315420:315473, ack 1038503, win 1384, options [nop,nop,TS val 3488328426 ecr 14230042], length 53: HTTP
2020-10-09 11:50:58.939837 IP xxx.http > yyy.42486: Flags [.], ack 315473, win 422, options [nop,nop,TS val 14230048 ecr 3488328426], length 0
2020-10-09 11:50:58.958746 IP yyy.42486 > xxx.http: Flags [F.], seq 315473, ack 1038503, win 1384, options [nop,nop,TS val 3488328445 ecr 14230048], length 0
2020-10-09 11:50:58.959108 IP xxx.http > yyy.42486: Flags [P.], seq 1038503:1038671, ack 315473, win 422, options [nop,nop,TS val 14230053 ecr 3488328426], length 168: HTTP: HTTP/1.1 201 Created
2020-10-09 11:50:58.959123 IP yyy.42486 > xxx.http: Flags [R], seq 515169552, win 0, length 0
2020-10-09 11:50:58.959169 IP xxx.http > yyy.42486: Flags [F.], seq 1038671, ack 315474, win 422, options [nop,nop,TS val 14230053 ecr 3488328445], length 0
2020-10-09 11:50:58.959175 IP yyy.42486 > xxx.http: Flags [R], seq 515169553, win 0, length 0
```

## Environment

The service in question is built with Spring Cloud Gateway. The request being made is a simple proxy request made by the gateway to a downstream service. An AWS ALB sits in front of the service and one also sits between the service and the downstream ones. All services are being run in AWS ECS.

[ALB] -> [SCG Service] -> [ALB] -> [Service X]

The ALBs both have a default idle timeout of 60 seconds.

The proxy connection pool has no upper bound
maxIdle = not set
maxLifetime = not set
lease strategy = fifo

I've also tested with a max idle set of 50 seconds + lifo strategy

- In debug logs and metrics, i've seen the pool reach over 300 active connections but i've seen the error occur at much lower level of active connections.

* Reactor netty version(s) used: 0.9.12 (Dysprosium-SR12) (also tested with 0.9.6)
* Other relevant libraries versions (eg. `netty`, ...): Netty 4.1.52, SCG 2.2.2
* JVM version: 11
* OS and version: Running in a docker container `openjdk:11-slim` debian:buster

**Comment by violetagg** [comment] 2020-10-18 14:27
@ukayani 

> 3. reactor sends a FIN ack
4. LB responds with an HTTP 201 with a body (json)

Why the LB responds with PSH?

**Comment by ukayani** [comment] 2020-10-18 16:26
> Why the LB responds with PSH?

Yeah i find that strange as well that it doesn't react to the FIN. The LB in question is an AWS ALB, so unfortunately its a black box. I can try reaching out to AWS support to find out why it behaves this way.

It's worth noting that the majority of the premature close events occur with the `Close with FIN` case rather than the `Close with RST` case (from above).

**Comment by violetagg** [comment] 2020-10-19 06:45
@ukayani 
> It's worth noting that the majority of the premature close events occur with the Close with FIN case rather than the Close with RST case (from above).

Can you provide also more detailed log related to `Close with FIN`?

In addition to Reactor Netty logs enable those for Spring Gateway.

This log is interesting because it will tell you the inbound and outbound connections
https://github.com/spring-cloud/spring-cloud-gateway/blob/4b6644f936dd94020a1ec8e749b765aa1de1f30e/spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/filter/NettyRoutingFilter.java#L138

You have the client closing the connection and this is interesting.

Do you have ReadTimeoutHandler/WriteTimeoutHandler?

`[ALB1] -> [SCG Service] -> [ALB2] -> [Service X]`
Is it possible that `ALB1` closes the connection?

**Comment by ukayani** [comment] 2020-10-19 16:07
> Can you provide also more detailed log related to `Close with FIN`?
> 
> In addition to Reactor Netty logs enable those for Spring Gateway.
> 
> This log is interesting because it will tell you the inbound and outbound connections
> https://github.com/spring-cloud/spring-cloud-gateway/blob/4b6644f936dd94020a1ec8e749b765aa1de1f30e/spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/filter/NettyRoutingFilter.java#L138

I will try to get these logs soon.

> You have the client closing the connection and this is interesting.

Yes, that is interesting. I did briefly look at the routing filter to see if there is some case where it would decide to terminate abruptly but i didn't see anything obvious.

> 
> Do you have `ReadTimeoutHandler`/`WriteTimeoutHandler` on the server/client (Spring Gateway)?

I'm not setting any explicit timeout handlers on the client that SCG is using to do the proxy calls. As for the SCG gateway server, i'm also not setting anything explicitly for that.

> 
> `[ALB1] -> [SCG Service] -> [ALB2] -> [Service X]`
> Is it possible that `ALB1` closes the connection?

I think that is certainly a possibility. Its a little hard for me to link that connection to the one from SCG -> ALB2 though via tcp dump. Maybe once i enable those logs above you mentioned i can take a look at the inbound connection corresponding to the outbound.

**Comment by ukayani** [comment] 2020-10-20 16:14
Hi @violetagg, sorry for the delay. 

I've capture some more detail regarding the inbound connection. Below are the logs from the premature close event which includes the trace for the NettyRoutingFilter.
 From what I see, the inbound connection does not close, it continues to be used even after this event.
 In the below logs: 
 - the inbound connection from ALB1 is `0x36a1b83b` (zzz port 4378)
 - the connection to ALB2 is `0xb1fd3f3d`

```
 14:49:44.924 DEBUG 9 --- [or-http-epoll-4] r.n.http.server.HttpServerOperations     : [id: 0x36a1b83b, L:/172.17.0.15:8080 - R:/ zzz:4378] Increasing pending responses, now 1
 14:49:44.924 DEBUG 9 --- [or-http-epoll-4] reactor.netty.http.server.HttpServer     : [id: 0x36a1b83b, L:/172.17.0.15:8080 - R:/ zzz:4378] Handler is being applied: org.springframework.http.server.reactive.ReactorHttpHandlerAdapter@51c440ea
 14:49:44.926 DEBUG 9 --- [or-http-epoll-1] r.n.resources.PooledConnectionProvider   : [id: 0xb1fd3f3d, L:/172.17.0.15:46724 - R: xxx:80] Channel acquired, now 1 active connections and 2 inactive connections
 14:49:44.926 DEBUG 9 --- [or-http-epoll-1] r.n.resources.PooledConnectionProvider   : [id: 0xb1fd3f3d, L:/172.17.0.15:46724 - R: xxx:80] onStateChange(GET{uri= /api/test?a=1, connection=PooledConnection{channel=[id: 0xb1fd3f3d, L:/172.17.0.15:46724 - R: /xxx:80]}}, [request_prepared])
 14:49:44.926 TRACE 9 --- [or-http-epoll-1] o.s.c.gateway.filter.NettyRoutingFilter  : outbound route: b1fd3f3d, inbound: [36a1b83b-1104424]
 14:49:44.926 DEBUG 9 --- [or-http-epoll-1] reactor.netty.channel.FluxReceive        : [id: 0x36a1b83b, L:/172.17.0.15:8080 - R:/ zzz:4378] FluxReceive{pending=0, cancelled=false, inboundDone=true, inboundError=null}: subscribing inbound receiver
 14:49:44.926 DEBUG 9 --- [or-http-epoll-1] r.n.resources.PooledConnectionProvider   : [id: 0xb1fd3f3d, L:/172.17.0.15:46724 - R: xxx:80] onStateChange(GET{uri= /api/test?a=1, connection=PooledConnection{channel=[id: 0xb1fd3f3d, L:/172.17.0.15:46724 - R: /xxx:80]}}, [request_sent])
 14:49:44.929 DEBUG 9 --- [or-http-epoll-1] r.n.resources.PooledConnectionProvider   : [id: 0xb1fd3f3d, L:/172.17.0.15:46724 ! R: xxx:80] Channel closed, now 0 active connections and 2 inactive connections
 14:49:44.929 DEBUG 9 --- [or-http-epoll-1] r.n.resources.PooledConnectionProvider   : [id: 0xb1fd3f3d, L:/172.17.0.15:46724 ! R: xxx:80] onStateChange(GET{uri= /api/test?a=1, connection=PooledConnection{channel=[id: 0xb1fd3f3d, L:/172.17.0.15:46724 ! R: /xxx:80]}}, [response_incomplete])
 14:49:44.929  WARN 9 --- [or-http-epoll-1] r.netty.http.client.HttpClientConnect    : [id: 0xb1fd3f3d, L:/172.17.0.15:46724 ! R: xxx:80] The connection observed an error

reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
 14:49:44.931 ERROR 9 --- [or-http-epoll-1] a.w.r.e.AbstractErrorWebExceptionHandler : [36a1b83b-1104424]  500 Server Error for HTTP GET "/api/test?a=1"

reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
	|_ checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ HTTP GET "/api/test?a=1" [ExceptionHandlingWebHandler]
Stack trace:
 14:49:44.931 DEBUG 9 --- [or-http-epoll-4] r.n.http.server.HttpServerOperations     : [id: 0x36a1b83b, L:/172.17.0.15:8080 - R:/ zzz:4378] Decreasing pending responses, now 0
 14:49:44.931 DEBUG 9 --- [or-http-epoll-4] r.n.http.server.HttpServerOperations     : [id: 0x36a1b83b, L:/172.17.0.15:8080 - R:/ zzz:4378] Last HTTP response frame
 14:49:44.931 DEBUG 9 --- [or-http-epoll-4] r.n.http.server.HttpServerOperations     : [id: 0x36a1b83b, L:/172.17.0.15:8080 - R:/ zzz:4378] Last HTTP packet was sent, terminating the channel
 ```

 Below is the corresponding tcpdump. 

The segment in the middle corresponds to the above reactor logs. 
You can see a request come in from `zzz aka ALB1` which gets proxied to `xxx ALB 2`.
We then see the connection be terminated via a FIN from the client, however the inbound connection is still active and ALB1 receives a 500 response from the reactor server. The same inbound connection is subsequently re-used for more successful requests.

 ```
 0-10-20 10:49:44.568230 IP 172.17.0.15.46724 > xxx.http: Flags [P.], seq 153273:154468, ack 394060, win 1384, options [nop,nop,TS val 3734315274 ecr 204762981], length 1195: HTTP: POST /api/gift HTTP/1.1
2020-10-20 10:49:44.568345 IP 172.17.0.15.46724 > xxx.http: Flags [P.], seq 154468:154521, ack 394060, win 1384, options [nop,nop,TS val 3734315274 ecr 204762981], length 53: HTTP
2020-10-20 10:49:44.568657 IP xxx.http > 172.17.0.15.46724: Flags [.], ack 154521, win 422, options [nop,nop,TS val 204763038 ecr 3734315274], length 0
2020-10-20 10:49:44.584076 IP xxx.http > 172.17.0.15.46724: Flags [P.], seq 394060:394228, ack 154521, win 422, options [nop,nop,TS val 204763042 ecr 3734315274], length 168: HTTP: HTTP/1.1 201 Created
2020-10-20 10:49:44.584086 IP 172.17.0.15.46724 > xxx.http: Flags [.], ack 394228, win 1384, options [nop,nop,TS val 3734315290 ecr 204763042], length 0
2020-10-20 10:49:44.704019 IP 172.17.0.15.46724 > xxx.http: Flags [P.], seq 154521:155760, ack 394228, win 1384, options [nop,nop,TS val 3734315410 ecr 204763042], length 1239: HTTP: GET /api/test?a=4 HTTP/1.1
2020-10-20 10:49:44.714398 IP xxx.http > 172.17.0.15.46724: Flags [P.], seq 394228:397236, ack 155760, win 422, options [nop,nop,TS val 204763074 ecr 3734315410], length 3008: HTTP: HTTP/1.1 200 OK
2020-10-20 10:49:44.714417 IP 172.17.0.15.46724 > xxx.http: Flags [.], ack 397236, win 1373, options [nop,nop,TS val 3734315420 ecr 204763074], length 0
2020-10-20 10:49:44.865239 IP 172.17.0.15.46724 > xxx.http: Flags [P.], seq 155760:157041, ack 397236, win 1384, options [nop,nop,TS val 3734315571 ecr 204763074], length 1281: HTTP: GET /api/test?a=5 HTTP/1.1
2020-10-20 10:49:44.878320 IP xxx.http > 172.17.0.15.46724: Flags [P.], seq 397236:403622, ack 157041, win 422, options [nop,nop,TS val 204763115 ecr 3734315571], length 6386: HTTP: HTTP/1.1 200 OK
2020-10-20 10:49:44.878338 IP 172.17.0.15.46724 > xxx.http: Flags [.], ack 403622, win 1352, options [nop,nop,TS val 3734315584 ecr 204763115], length 0

2020-10-20 10:49:44.924316 IP zzz.4378 > 172.17.0.15.http-alt: Flags [P.], seq 2351:3169, ack 13657, win 212, options [nop,nop,TS val 427342814 ecr 3862869734], length 818: HTTP: GET /gift/api/test?a=1 HTTP/1.1
2020-10-20 10:49:44.926341 IP 172.17.0.15.46724 > xxx.http: Flags [P.], seq 157041:158289, ack 403622, win 1384, options [nop,nop,TS val 3734315632 ecr 204763115], length 1248: HTTP: GET /api/test?a=1 HTTP/1.1
2020-10-20 10:49:44.929601 IP 172.17.0.15.46724 > xxx.http: Flags [F.], seq 158289, ack 403622, win 1384, options [nop,nop,TS val 3734315635 ecr 204763115], length 0
2020-10-20 10:49:44.929906 IP xxx.http > 172.17.0.15.46724: Flags [F.], seq 403622, ack 158290, win 422, options [nop,nop,TS val 204763128 ecr 3734315632], length 0
2020-10-20 10:49:44.929914 IP 172.17.0.15.46724 > xxx.http: Flags [.], ack 403623, win 1384, options [nop,nop,TS val 3734315636 ecr 204763128], length 0
2020-10-20 10:49:44.931729 IP 172.17.0.15.http-alt > zzz.4378: Flags [P.], seq 13657:14048, ack 3169, win 276, options [nop,nop,TS val 3862879828 ecr 427342814], length 391: HTTP: HTTP/1.1 500 Internal Server Error
2020-10-20 10:49:44.932302 IP zzz.4378 > 172.17.0.15.http-alt: Flags [.], ack 14048, win 224, options [nop,nop,TS val 427342816 ecr 3862879828], length 0

2020-10-20 10:49:59.171156 IP zzz.4378 > 172.17.0.15.http-alt: Flags [P.], seq 3169:4008, ack 14048, win 224, options [nop,nop,TS val 427346376 ecr 3862879828], length 839: HTTP: GET /gift/api/test?a=6 HTTP/1.1
2020-10-20 10:49:59.212446 IP 172.17.0.15.http-alt > zzz.4378: Flags [.], ack 4008, win 290, options [nop,nop,TS val 3862894109 ecr 427346376], length 0
2020-10-20 10:49:59.225876 IP 172.17.0.15.http-alt > zzz.4378: Flags [.], seq 14048:21288, ack 4008, win 290, options [nop,nop,TS val 3862894122 ecr 427346376], length 7240: HTTP: HTTP/1.1 200 OK
2020-10-20 10:49:59.225896 IP 172.17.0.15.http-alt > zzz.4378: Flags [P.], seq 21288:22365, ack 4008, win 290, options [nop,nop,TS val 3862894122 ecr 427346376], length 1077: HTTP
2020-10-20 10:49:59.226150 IP zzz.4378 > 172.17.0.15.http-alt: Flags [.], ack 22365, win 288, options [nop,nop,TS val 427346390 ecr 3862894122], length 0
2020-10-20 10:50:08.767619 IP zzz.4378 > 172.17.0.15.http-alt: Flags [P.], seq 4008:4805, ack 22365, win 288, options [nop,nop,TS val 427348775 ecr 3862894122], length 797: HTTP: GET /gift/api/test?a=7 HTTP/1.1
2020-10-20 10:50:08.767633 IP 172.17.0.15.http-alt > zzz.4378: Flags [.], ack 4805, win 303, options [nop,nop,TS val 3862903664 ecr 427348775], length 0
2020-10-20 10:50:08.806688 IP 172.17.0.15.http-alt > zzz.4378: Flags [P.], seq 22365:27515, ack 4805, win 303, options [nop,nop,TS val 3862903703 ecr 427348775], length 5150: HTTP: HTTP/1.1 200 OK
2020-10-20 10:50:08.806937 IP zzz.4378 > 172.17.0.15.http-alt: Flags [.], ack 27515, win 329, options [nop,nop,TS val 427348785 ecr 3862903703], length 0
 ```

**Comment by violetagg** [comment] 2020-10-21 13:07
@ukayani Do you have some custom filters? We need to understand what causes connection close.

**Comment by ukayani** [comment] 2020-10-22 13:53
@violetagg I do have some custom filters in the chain. There is one in particular that modifies the response body returned from ALB2. 

The flow goes as follows:
1. NettyRoutingFilter calls service X
2. Response returned is parsed into a JSON AST
3. Make some additional calls via a webclient to get data
4. Zip this data into the original response from service X
5. Response is written back to client via the NettyWriting filter

In step 3, we have a read and write timeout of 1 second. I'm using the Read/WriteTimeoutHandler for these. This webclient is not the same as the one used by NettyRoutingFilter though. Any errors returned by these calls result in the original response being returned to the client.

In most examples of the connection close event, it seems to happen before the response is returned by ALB2 so i'm not sure if this response modification filter plays a role.

The only other filters I have are some that inspect the request for various info and add some additional HTTP headers to the request. These filters aren't doing anything exotic.

I've tried to reproduce this issue locally by hitting the service with load but was unsuccessful so it would be hard to produce an example. I can try to do some more tests to see if i ever get it to occur locally.

**Comment by violetagg** [comment] 2020-11-06 10:32
@ukayani Excuse me for the delay here.

So you use `Mono.zip`
Which API do you use exactly?
https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Mono.html#zip-reactor.core.publisher.Mono-reactor.core.publisher.Mono-

Typically if some of the Publishers return `error` or `empty`
```
An error or empty completion of any source will cause other sources to be cancelled
```

Cancel in terms of WebClient call means closing the connection because we do not now in what kind of state is that connection.

**Comment by ukayani** [comment] 2020-11-06 18:14
No problem.

I'm actually not using the zip operator, sorry for the confusion. 
In step 4, what i mean is that i'm doing a logical zip in my code. 

For example:
I have a response with a list of user ids, i fetch data for all user ids (in a single batch call) and manually "zip" the additional data to each user. I also do a `.onErrorResume` operation to swallow any error signals and return the original response.

For the response modification filter, we supply a rewrite function with the following signature:
`BiFunction<ServerWebExchange, T, Publisher<R>>`, where T is the input type and R is the output type. The filter creates a wrapper around the exchange's response to transform it on the fly (when it is written downstream).

In my case, `T = R = ByteArrayResource`, so within my rewrite function i do something like the following:

```java
public Mono<ByteArrayResource> rewrite(ServerWebExchange ex, ByteArrayResource in) {
    var parsedResponse = parse(in.getInputStream());
    return userDataService
        .getUsersData(userIds)
        .map(userDataList -> convertToMap(userDataList))
        .map(userDataMap -> zipInToResponse(parsedResponse, userDataMap))
        .map(serializeToString)
        .map(ByteArrayResource::new)
        .onErrorResume(err -> Mono.just(in));
  }
```

The above code is simplified to make the logic clear. The Publisher returned by `.getUsersData` will return an empty list as an element rather than produce an empty completion signal. I also handle any errors during this process by just returning the original response.


Correct me if i'm wrong but given that in the tcp dump examples, we seeing a close being sent to the ALB **before** the response is returned, i'm assuming that rewrite function would not have been called at that point. It leads me to conclude that my response rewrite function probably doesn't play a part in this disconnect happening. Of course, that does not exclude bugs in the logic surrounding the setup of the response rewrite filter itself.

**Comment by violetagg** [comment] 2020-11-12 10:04
@ukayani I will need some reproducible example for further investigation or if you want to try to debug - we need to understand why connection close is invoked.

**Comment by ukayani** [comment] 2020-11-17 20:58
I understand, it is not easy to debug without a reproducible example. I did try reproducing this problem on a local machine but was unsuccessful. I haven't had time to dive deeper into this yet but i'll hopefully get some time to try and debug better. Do you have any suggestions for how to trace/debug the connection close? The debug logs don't tell me much in terms of why the close is triggered.

**Comment by violetagg** [comment] 2020-11-18 06:38
@ukayani Something that you might checked already but ... what about TCP keepalive? Can you check in the logs when the connection was created and closed and then the TCP keepalive value?

**Comment by violetagg** [comment] 2020-11-25 16:52
I think this is the same issue described here #1375 and #1201.

**Comment by ukayani** [comment] 2020-11-25 17:03
Thanks for the update @violetagg ! Hopefully a fix for that resolves the issue. In my case, the response body is not empty however.

**Comment by violetagg** [comment] 2020-11-25 17:10
So you never return `Mono.empty`?

**Comment by ukayani** [comment] 2020-11-25 17:24
> So you never return `Mono.empty`?

The responses from proxied services are not empty in the scenario where this exception occurs. As for returning mono.empty, i don't do that in my rewrite filter. The rest of the filter chain is the standard chain for SCG.

**Comment by AsCat** [comment] 2020-12-29 15:00
@ukayani 
Can you help test it with this [PR](https://github.com/spring-cloud/spring-cloud-gateway/pull/2093) ?

**Comment by ukayani** [comment] 2020-12-29 15:58
@AsCat i can give it a test in a few days.

**Comment by violetagg** [comment] 2021-01-12 16:42
The mentioned PR was applied to Spring Gateway.

**Comment by ukayani** [comment] 2021-01-12 16:47
I will update to latest and report back. Thanks for the update.

**Comment by violetagg** [comment] 2021-01-25 13:29
@ukayani I'm closing this issue, we can reopen it if the fix in Spring Cloud Gateway is not enough.

**Closed by violetagg** 2021-01-25 13:29 UTC
Labels: for/spring-cloud-gateway, type/bug
