### ISSUE TITLE
'io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1'

### ISSUE THREAD

**Issue by idikshit** [reactor/reactor-netty#2171] opened 2022-04-29 11:30 UTC
Hi,

We are sending GET requests to our application. We are encountering the issue mentioned below frequently.

Dependencies
Spring Cloud Gateway - 3.0.3
Spring Boot - 2.5.5
Spring webflux - 5.3.10
Reactor netty - 1.0.11
Netty - 4.1.63.Final
OS - Cent OS / Linux

`{"instant":{"epochSecond":1651180720,"nanoOfSecond":289955175},"thread":"ingress-h2c-epoll-3","level":"WARN","loggerName":"io.netty.channel.DefaultChannelPipeline","message":"An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.","thrown":{"commonElementCount":0,"localizedMessage":"refCnt: 0, decrement: 1","message":"refCnt: 0, decrement: 1","name":"io.netty.util.IllegalReferenceCountException","extendedStackTrace":[{"class":"io.netty.util.internal.ReferenceCountUpdater","method":"toLiveRealRefCnt","file":"ReferenceCountUpdater.java","line":74,"exact":false,"location":"netty-common-4.1.63.Final.jar!/","version":"4.1.63.Final"},{"class":"io.netty.util.internal.ReferenceCountUpdater","method":"release","file":"ReferenceCountUpdater.java","line":138,"exact":false,"location":"netty-common-4.1.63.Final.jar!/","version":"4.1.63.Final"},{"class":"io.netty.buffer.AbstractReferenceCountedByteBuf","method":"release","file":"AbstractReferenceCountedByteBuf.java","line":100,"exact":false,"location":"netty-buffer-4.1.63.Final.jar!/","version":"4.1.63.Final"},{"class":"io.netty.handler.codec.ByteToMessageDecoder","method":"channelRead","file":"ByteToMessageDecoder.java","line":285,"exact":false,"location":"netty-codec-4.1.63.Final.jar!/","version":"4.1.63.Final"},{"class":"io.netty.channel.AbstractChannelHandlerContext","method":"invokeChannelRead","file":"AbstractChannelHandlerContext.java","line":379,"exact":true,"location":"netty-transport-4.1.63.Final.jar!/","version":"4.1.63.Final"},{"class":"io.netty.channel.AbstractChannelHandlerContext","method":"invokeChannelRead","file":"AbstractChannelHandlerContext.java","line":365,"exact":true,"location":"netty-transport-4.1.63.Final.jar!/","version":"4.1.63.Final"},{"class":"io.netty.channel.AbstractChannelHandlerContext","method":"fireChannelRead","file":"AbstractChannelHandlerContext.java","line":357,"exact":true,"location":"netty-transport-4.1.63.Final.jar!/","version":"4.1.63.Final"},{"class":"io.netty.handler.logging.LoggingHandler","method":"channelRead","file":"LoggingHandler.java","line":271,"exact":true,"location":"netty-handler-4.1.63.Final.jar!/","version":"4.1.63.Final"},{"class":"io.netty.channel.AbstractChannelHandlerContext","method":"invokeChannelRead","file":"AbstractChannelHandlerContext.java","line":379,"exact":true,"location":"netty-transport-4.1.63.Final.jar!/","version":"4.1.63.Final"},{"class":"io.netty.channel.AbstractChannelHandlerContext","method":"invokeChannelRead","file":"AbstractChannelHandlerContext.java","line":365,"exact":true,"location":"netty-transport-4.1.63.Final.jar!/","version":"4.1.63.Final"},{"class":"io.netty.channel.AbstractChannelHandlerContext","method":"fireChannelRead","file":"AbstractChannelHandlerContext.java","line":357,"exact":true,"location":"netty-transport-4.1.63.Final.jar!/","version":"4.1.63.Final"},{"class":"io.netty.channel.ChannelInboundHandlerAdapter","method":"channelRead","file":"ChannelInboundHandlerAdapter.java","line":93,"exact":true,"location":"netty-transport-4.1.63.Final.jar!/","version":"4.1.63.Final"},{"class":"ocpm.cne.gateway.util.ConnectionCountHandler","method":"channelRead","file":"ConnectionCountHandler.java","line":46,"exact":true,"location":"classes!/","version":"?"},{"class":"io.netty.channel.AbstractChannelHandlerContext","method":"invokeChannelRead","file":"AbstractChannelHandlerContext.java","line":379,"exact":true,"location":"netty-transport-4.1.63.Final.jar!/","version":"4.1.63.Final"},{"class":"io.netty.channel.AbstractChannelHandlerContext","method":"invokeChannelRead","file":"AbstractChannelHandlerContext.java","line":365,"exact":true,"location":"netty-transport-4.1.63.Final.jar!/","version":"4.1.63.Final"},{"class":"io.netty.channel.AbstractChannelHandlerContext","method":"fireChannelRead","file":"AbstractChannelHandlerContext.java","line":357,"exact":true,"location":"netty-transport-4.1.63.Final.jar!/","version":"4.1.63.Final"},{"class":"io.netty.channel.DefaultChannelPipeline$HeadContext","method":"channelRead","file":"DefaultChannelPipeline.java","line":1410,"exact":true,"location":"netty-transport-4.1.63.Final.jar!/","version":"4.1.63.Final"},{"class":"io.netty.channel.AbstractChannelHandlerContext","method":"invokeChannelRead","file":"AbstractChannelHandlerContext.java","line":379,"exact":true,"location":"netty-transport-4.1.63.Final.jar!/","version":"4.1.63.Final"},{"class":"io.netty.channel.AbstractChannelHandlerContext","method":"invokeChannelRead","file":"AbstractChannelHandlerContext.java","line":365,"exact":true,"location":"netty-transport-4.1.63.Final.jar!/","version":"4.1.63.Final"},{"class":"io.netty.channel.DefaultChannelPipeline","method":"fireChannelRead","file":"DefaultChannelPipeline.java","line":919,"exact":true,"location":"netty-transport-4.1.63.Final.jar!/","version":"4.1.63.Final"},{"class":"io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe","method":"epollInReady","file":"AbstractEpollStreamChannel.java","line":795,"exact":true,"location":"netty-transport-native-epoll-4.1.63.Final-linux-x86_64.jar!/","version":"4.1.63.Final"},{"class":"io.netty.channel.epoll.EpollEventLoop","method":"processReady","file":"EpollEventLoop.java","line":480,"exact":true,"location":"netty-transport-native-epoll-4.1.63.Final-linux-x86_64.jar!/","version":"4.1.63.Final"},{"class":"io.netty.channel.epoll.EpollEventLoop","method":"run","file":"EpollEventLoop.java","line":378,"exact":true,"location":"netty-transport-native-epoll-4.1.63.Final-linux-x86_64.jar!/","version":"4.1.63.Final"},{"class":"io.netty.util.concurrent.SingleThreadEventExecutor$4","method":"run","file":"SingleThreadEventExecutor.java","line":989,"exact":true,"location":"netty-common-4.1.63.Final.jar!/","version":"4.1.63.Final"},{"class":"io.netty.util.internal.ThreadExecutorMap$2","method":"run","file":"ThreadExecutorMap.java","line":74,"exact":true,"location":"netty-common-4.1.63.Final.jar!/","version":"4.1.63.Final"},{"class":"io.netty.util.concurrent.FastThreadLocalRunnable","method":"run","file":"FastThreadLocalRunnable.java","line":30,"exact":true,"location":"netty-common-4.1.63.Final.jar!/","version":"4.1.63.Final"},{"class":"java.lang.Thread","method":"run","file":"Thread.java","line":833,"exact":true,"location":"?","version":"?"}]},"endOfBatch":false,"loggerFqcn":"io.netty.util.internal.logging.LocationAwareSlf4JLogger","contextMap":{},"threadId":104,"threadPriority":5,"messageTimestamp":"2022-04-28T21:18:40.289+0000","ocLogId":"${ctx:ocLogId}","pod":"${ctx:hostname}","processId":"1","instanceType":"prod","ingressTxId":"${ctx:ingressTxId}"}`

Please let us know how to resolve this issue?

**Comment by idikshit** [comment] 2022-04-29 11:47
@violetagg Which version of SCG has addressed this issue?

**Comment by violetagg** [comment] 2022-04-29 12:15
> @violetagg Could you please let us know which version of SCG has addressed this issue?

I did not say that there is a version addressing this issue but that the SCG version that you use is one year old.

**Comment by idikshit** [comment] 2022-04-29 12:30
@violetagg We came across a similar issue reported on this topic [https://github.com/reactor/reactor-netty/issues/1410]. The latest comment mentions the issue to be fixed in Spring 4.3.2. Could you please highlight which library of spring are we referring to here?

**Comment by violetagg** [comment] 2022-04-29 12:39
@idikshit This exception does not have only one concrete root cause ... however in your case I do not see any Reactor Netty related code in the stack trace so I cannot comment what might be the real root cause.

Spring 4 does not use Reactor Netty, only versions above Spring 5.

**Comment by violetagg** [comment] 2022-05-09 05:46
@idikshit I'm closing this one. If you are able to provide more information we can reopen it.

**Closed by violetagg** 2022-05-09 05:46 UTC
Labels: type/bug, for/user-attention
