### ISSUE TITLE
When responsebody is empty, Connection has been closed BEFORE response.

### ISSUE THREAD

**Issue by jayzch** [reactor/reactor-netty#1201] opened 2020-07-09 05:36 UTC
When responsebody is empty with  lot of pressure measurement,  then spring cloud gataway will throw Exception.
Connection has been closed BEFORE response.

```xml
        <dependency>
            <groupId>io.projectreactor.netty</groupId>
            <artifactId>reactor-netty</artifactId>
            <version>0.9.9.RELEASE</version>
        </dependency>

```

reactor.netty.http.client.PrematureCloseException: Connection has been closed BEFORE response, while sending request body 	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:  Error has been observed at the following site(s): 	\|_ checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain] 	\|_ checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain] 	\|_ checkpoint ⇢ HTTP POST "/api/open-api/ccs/upload" [ExceptionHandlingWebHandler] Stack trace:
--

**Comment by violetagg** [comment] 2020-07-09 05:45
@jayzch Please elaborate more on the scenario. Thanks.

**Comment by jayzch** [comment] 2020-07-09 05:59
when the http request response the empty body  with status 200, the error happens.

**Comment by violetagg** [comment] 2020-07-09 16:03
@jayzch So let me summarise:
1. you use Spring Gateway,
2. you issue a POST request (does this post request has a body?)
3. Gateway receives a response 200 OK as a result and the exception appears

Is that correct?

The exception above says the following: the connection was closed while still sending the request body. 

Did you check whether your endpoint consumed the request body?

**Comment by jayzch** [comment] 2020-07-10 06:22
> @jayzch So let me summarise:
> 
> 1. you use Spring Gateway,
> 2. you issue a POST request (does this post request has a body?)
> 3. Gateway receives a response 200 OK as a result and the exception appears
> 
> Is that correct?
> 
> The exception above says the following: the connection was closed while still sending the request body.
> 
> Did you check whether your endpoint consumed the request body?

1.Yes. Spring Cloud Gateway
2.HTTP POST ,request with body  but response empty
3. Gateway receives a response 200 OK  , then  Gateway receiveing  single thread is ok, but multithreading (100  thread) caused exception

**Comment by violetagg** [comment] 2020-07-10 06:51
@jayzch Are you able to provide some reproducible example? Do you have some timeout configured? Unfortunately I'm not able to reproduce the issue so it might be something specific for your use case.

**Comment by jayzch** [comment] 2020-07-10 06:58
When response with empty body  , Gateway receiveing  multithreading request caused exception


``````
    @PostMapping("upload")
    public ResponseEntity uploadData(@RequestBody UploadDataRequest uploadDataRequest) {
        StatusDTO statusDTO = dataReportService.reportData(uploadDataRequest);
        return new ResponseEntity<>(statusDTO, HttpStatus.OK);
    }
```````



When response with body ,It works well.
``````
    @PostMapping("upload")
    public ResponseEntity uploadData(@RequestBody UploadDataRequest uploadDataRequest) {
        StatusDTO statusDTO = dataReportService.reportData(uploadDataRequest);
        return new ResponseEntity<>(statusDTO, HttpStatus.OK);
    }
``````

**Comment by violetagg** [comment] 2020-07-10 07:11
@jayzch There is no difference in the two snippets above or?
What is inside `dataReportService.reportData(uploadDataRequest)`?
Is the request body consumed in every scenario?

By specification we have the following
https://tools.ietf.org/html/rfc7230#section-6.3

```
A server MUST read
   the entire request message body or close the connection after sending
   its response, since otherwise the remaining data on a persistent
   connection would be misinterpreted as the next request.
```

**Comment by jayzch** [comment] 2020-07-10 07:26
There is no difference in the two snippets.

I have try many times.

only difference is  empty response or not.


there are others   snippets   the same as the problem.



If response is empty, every now and them throw  exception.


logger_name: org.springframework.boot.autoconfigure.web.reactive.error.AbstractErrorWebExceptionHandler
message: [05bd2cff-148514]  500 Server Error for HTTP POST "/mult-upload"
port: 56680
stack_trace: reactor.netty.http.client.PrematureCloseException: Connection has been closed BEFORE response, while sending request body
  Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
  |_ checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
  |_ checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
  |_ checkpoint ⇢ HTTP POST "/api/open-api/hmcc/mult-upload" [ExceptionHandlingWebHandler]
Stack trace:

thread_name: reactor-http-epoll-2

**Comment by violetagg** [comment] 2020-07-10 07:34
and is the request body consumed in every scenario?

**Comment by jayzch** [comment] 2020-07-10 07:42
> and is the request body consumed in every scenario?

yes

**Comment by violetagg** [comment] 2020-07-10 10:31
@jayzch I'm trying to reproduce with this

**Spring Gateway app**

**application.yml**

```
server:
  port: 9090
spring:
  cloud:
    gateway:
      routes:
        - id: external
          uri: http://localhost:8080/upload
          predicates:
            - Path=/upload
```

**Application.java**

```
@SpringBootApplication
public class Application {

	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}

}
```

The target server is using Spring WebFlux

**Application.java**

```
@SpringBootApplication
public class Application {

	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}

}
```

**MyController.java**

```
@RestController
public class MyController {

	@PostMapping("upload")
	public ResponseEntity<String> post(@RequestBody String body) {
		System.out.println("BODY: " + body);
		return new ResponseEntity<>("", HttpStatus.OK);
	}
}
```

Then I use `wrk2` for generating load

**post.lua**

```
wrk.method = "POST"
wrk.body = "{\"firstKey\": 'somedata', \"secondKey\": 'somedata'}"
wrk.headers["Content-Type"] = "application/json"
```

```
wrk2 -t 2 -c 100 -d 30s -R 2000 http://localhost:9090/upload -s post.lua 
Running 30s test @ http://localhost:9090/upload
  2 threads and 100 connections
  Thread calibration: mean lat.: 6.079ms, rate sampling interval: 10ms
  Thread calibration: mean lat.: 7.269ms, rate sampling interval: 10ms
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.05ms  603.17us  10.25ms   73.12%
    Req/Sec     1.05k   173.40     1.90k    81.63%
  59800 requests in 30.00s, 4.45MB read
Requests/sec:   1993.31
Transfer/sec:    151.83KB
```

I do not see any exception in Spring Gateway

**Comment by jayzch** [comment] 2020-07-10 10:39
try this

MyController.java

@RestController
public class MyController {

	@PostMapping("upload")
	public ResponseEntity<String> post(@RequestBody String body) {
		System.out.println("BODY: " + body);
		return new ResponseEntity<>(HttpStatus.OK);
	}
}

**Comment by violetagg** [comment] 2020-07-10 10:42
@jayzch I don't get it

**Comment by jayzch** [comment] 2020-07-10 10:44
return new ResponseEntity<>(HttpStatus.OK);


		return new ResponseEntity<>("", HttpStatus.OK);

**Comment by jayzch** [comment] 2020-07-10 10:48
> When response with empty body , Gateway receiveing multithreading request caused exception
> 
> ```
>     @PostMapping("upload")
>     public ResponseEntity uploadData(@RequestBody UploadDataRequest uploadDataRequest) {
>         StatusDTO statusDTO = dataReportService.reportData(uploadDataRequest);
>         return new ResponseEntity<>(HttpStatus.OK);
>     }
> ```
> 
> When response with body ,It works well.
> 
> ```
>     @PostMapping("upload")
>     public ResponseEntity uploadData(@RequestBody UploadDataRequest uploadDataRequest) {
>         StatusDTO statusDTO = dataReportService.reportData(uploadDataRequest);
>         return new ResponseEntity<>(statusDTO, HttpStatus.OK);
>     }
> ```

@violetagg  sorry，I write  some mistake。I have correct it

**Comment by violetagg** [comment] 2020-07-10 10:50
@jayzch OK

With this change

```
@RestController
public class MyController {

	@PostMapping("upload")
	public ResponseEntity<String> post(@RequestBody String body) {
		System.out.println("BODY: " + body);
		//return new ResponseEntity<>("", HttpStatus.OK);
		return new ResponseEntity<>(HttpStatus.OK);
	}
}
```

I do not see issues

```
wrk2 -t 2 -c 100 -d 30s -R 2000 http://localhost:9090/upload -s ~/Downloads/post.lua
Running 30s test @ http://localhost:9090/upload
  2 threads and 100 connections
  Thread calibration: mean lat.: 26.066ms, rate sampling interval: 49ms
  Thread calibration: mean lat.: 26.627ms, rate sampling interval: 54ms
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.30ms  678.15us  11.50ms   74.63%
    Req/Sec     1.01k    28.91     1.21k    75.03%
  59802 requests in 30.00s, 2.17MB read
Requests/sec:   1993.22
Transfer/sec:     73.97KB
```

I'm using Java 8 on Mac OS

**Comment by violetagg** [comment] 2020-07-24 06:18
@jayzch I'm closing this. If you are able to provide a reproducible example we can reopen the issue.

**Comment by jayzch** [comment] 2020-08-14 02:18
https://github.com/reactor/reactor-netty/issues/1092#issuecomment-638632329

**Comment by dwlabcube** [comment] 2020-11-24 09:06
@jayzch 
i am experiencing the same issue. When the response body of the Server is empty, spring gateway throws prematurelyclosed exceptions. i am using java 11, spring 2.4.0, spring cloud gateway 2020.0.0-M5.

could you solve the issue somehow?

**Comment by violetagg** [comment] 2020-11-24 09:13
@dwlabcube Can you provide a reproducible example?

**Comment by dwlabcube** [comment] 2020-11-24 09:36
@violetagg 
sure.

azttached demo.zip
[demo.zip](https://github.com/reactor/reactor-netty/files/5588804/demo.zip)

use apache benchmark:
abs -kc 100 -t 30 http://localhost:8080/performance/test/get

I use 
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

**Comment by violetagg** [comment] 2020-11-25 16:49
Thanks I can reproduce it.

**Comment by jayzch** [comment] 2020-11-26 03:58
@violetagg Why did  not you reproduce it before ?  I just want to get the different point.

**Comment by AsCat** [comment] 2020-12-29 14:58
@jay

Can you help test it with this [PR](https://github.com/spring-cloud/spring-cloud-gateway/pull/2093)

**Comment by violetagg** [comment] 2021-01-12 16:41
The mentioned PR was applied to Spring Gateway.

**Comment by dwlabcube** [comment] 2021-01-25 09:09
hey mates
i don't want to be unpolite, but if the next milestone release with this fix included could be released as soon as possible i'd be super happy about it :-)

**Comment by violetagg** [comment] 2021-01-25 13:25
> hey mates
> i don't want to be unpolite, but if the next milestone release with this fix included could be released as soon as possible i'd be super happy about it :-)

@dwlabcube This issue is marked `for/spring-cloud-gateway` because the fix is in `Spring Cloud Gateway`.
https://github.com/spring-cloud/spring-cloud-gateway/pull/2093

Please communicate with Spring Cloud Gateway for the release dates.

I'm closing this issue.

**Closed by violetagg** 2021-01-25 13:25 UTC
Labels: for/spring-cloud-gateway, type/bug

**Comment by kanai0618** [comment] 2021-06-14 09:21
Hi @jayzch  i am also facing the same issue in spring cloud gateway. how did you fix this issue ? 

```
reactor.netty.channel.AbortedException: Connection has been closed BEFORE send operation
	at reactor.netty.channel.AbortedException.beforeSend(AbortedException.java:60)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ Handler org.springframework.boot.actuate.endpoint.web.reactive.AbstractWebFluxEndpointHandlerMapping$ReadOperationHandler#handle(ServerWebExchange) [DispatcherHandler]

```

**Comment by violetagg** [comment] 2021-06-14 10:49
@kanai0618 Your exception is a bit different 

`Connection has been closed BEFORE send operation`
vs.
`Connection has been closed BEFORE response`

**Comment by kanai0618** [comment] 2021-06-14 10:51
yeah @violetagg  sorry my bad. yeah could you help me ?
So i was getting 
```
Connection prematurely closed
```
before setting the max-idle time. once i set max-idle time i get 
```
Connection has been closed BEFORE send operation
```

**Comment by violetagg** [comment] 2021-06-14 10:57
@kanai0618 Would you like to move the discussion to [Gitter](https://gitter.im/reactor/reactor-netty)

**Comment by kanai0618** [comment] 2021-06-14 10:58
Sure thanks @violetagg  let me start the thread there.

**Comment by redysanin** [comment] 2024-01-05 07:52
Getting SslHandshakeTimeoutException , how to handle that 

handshake timed out after 10000ms; nested exception is io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 10000ms

Original Stack Trace:
		at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:141)
		at reactor.core.publisher.MonoErrorSupplied.subscribe(MonoErrorSupplied.java:55)
		at reactor.core.publisher.Mono.subscribe(Mono.java:4397)
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
		at reactor.core.publisher.MonoNext$NextSubscriber.onError(MonoNext.java:93)
		at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onError(MonoFlatMapMany.java:204)
		at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
		at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.whenError(FluxRetryWhen.java:225)
		at reactor.core.publisher.FluxRetryWhen$RetryWhenOtherSubscriber.onError(FluxRetryWhen.java:274)
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:415)
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:251)
		at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:537)
		at reactor.core.publisher.EmitterProcessor.tryEmitNext(EmitterProcessor.java:343)
		at reactor.core.publisher.SinkManySerialized.tryEmitNext(SinkManySerialized.java:100)
		at reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:27)
		at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onError(FluxRetryWhen.java:190)
		at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:201)
		at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect$ClientTransportSubscriber.onError(HttpClientConnect.java:308)
		at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:201)
		at reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.onUncaughtException(DefaultPooledConnectionProvider.java:204)
		at reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnection.onUncaughtException(DefaultPooledConnectionProvider.java:454)
		at reactor.netty.channel.ChannelOperationsHandler.exceptionCaught(ChannelOperationsHandler.java:129)
		at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
		at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
		at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
		at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireExceptionCaught(CombinedChannelDuplexHandler.java:424)
		at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:92)
		at io.netty.channel.CombinedChannelDuplexHandler$1.fireExceptionCaught(CombinedChannelDuplexHandler.java:145)
		at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:143)
		at io.netty.channel.CombinedChannelDuplexHandler.exceptionCaught(CombinedChannelDuplexHandler.java:231)
		at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
		at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
		at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
		at reactor.netty.tcp.SslProvider$SslReadHandler.userEventTriggered(SslProvider.java:850)
		at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:346)
		at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:332)
		at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:324)
		at io.netty.handler.ssl.SslUtils.handleHandshakeFailure(SslUtils.java:443)
		at io.netty.handler.ssl.SslHandler$7.run(SslHandler.java:2119)
		at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
		at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
		at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
		at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
		at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.lang.Thread.run(Thread.java:750)
Caused by: io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 10000ms
	at io.netty.handler.ssl.SslHandler$7.run(SslHandler.java:2115)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)
