### ISSUE TITLE
Netty HttpClient Connection Pool creates connection for every request

### ISSUE THREAD

**Issue by syedyusufh** [reactor/reactor-netty#3373] opened 2024-07-27 05:20 UTC
**Env:**

AWS EKS v1.29
OpenJdk v22
Spring Boot v3.3.2

**Observation Logs:**

```
SSL enabled using engine SSLEngine[....clusterIp]
Registering pool release on close event for channel
```

**Problem Statement:**

The above logs / behavior is seen ONLY when there is a pod to pod communication (K8s allocates different source port on every request), could that be a reason as this is NOT seen when the application runs as a standalone. The implication of this behavior is response slowness.

Referred the GH issue on the similar subject https://github.com/reactor/reactor-netty/issues/984, have verified the SSL Context to be a singleton bean and NOT created for every request. What else could be causing this behavior?

Kindly suggest.

**Comment by violetagg** [comment] 2024-07-29 06:34
@syedyusufh Check our documentation https://projectreactor.io/docs/netty/release/reference/index.html#_connection_pool

```
connection pool per remote host (a remote host implies the combination of a hostname and its associated port number) 
```

**Comment by syedyusufh** [comment] 2024-07-29 08:38
Hi @violetagg , the destination in this case remains same - same host (k8s clusterip as service) and port (clusterip port). Still we see the mentioned logs printed for every request

**Comment by violetagg** [comment] 2024-07-29 08:41
@syedyusufh then please provide your `HttpClient` configuration and the logs

**Comment by syedyusufh** [comment] 2024-07-29 08:59
Please find below,

```
var httpClient = HttpClient.create()
		            .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 10000)
		            .option(ChannelOption.TCP_NODELAY, tcpNoDelay)
		            .protocol(HttpProtocol.H2, HttpProtocol.HTTP11)
		            .doOnRequest((request, connection) -> connection.addHandlerFirst(customLogger))
		            .responseTimeout(Duration.ofSeconds(11))
		            .secure(nettySslConfig.sslProvider()); // bean reference
```


**Request 1:**

```
[9d227c9e, L:/xx.xx.xx.47:55162 - R:xxxxxx-clusterip.svc.cluster.local/xxx.xx.xxx.28:8443] Registering pool release on close event for channel
[9d227c9e, L:/xx.xx.xx.47:55162 - R:xxxxxx-clusterip.svc.cluster.local/xxx.xx.xxx.28:8443] Channel connected, now: 1 active connections, 0 inactive connections and 0 pending acquire requests.
[9d227c9e-1, L:/xx.xx.xx.47:55162 - R:xxxxxx-clusterip.svc.cluster.local/xxx.xx.xxx.28:8443] Channel activated
[9d227c9e-1, L:/xx.xx.xx.47:55162 - R:xxxxxx-clusterip.svc.cluster.local/xxx.xx.xxx.28:8443] Channel deactivated
[9d227c9e-1, L:/xx.xx.xx.47:55162 - R:xxxxxx-clusterip.svc.cluster.local/xxx.xx.xxx.28:8443] Channel removed from pool
....
....
[9d227c9e, L:/xx.xx.xx.47:55162 ! R:xxxxxx-clusterip.svc.cluster.local/xxx.xx.xxx.28:8443] Channel closed, now: 0 active connections, 0 inactive connections and 0 pending acquire requests.
```


**Request 2:**

```
[26ba9590, L:/xx.xx.xx.47:42648 - R:xxxxxx-clusterip.svc.cluster.local/xxx.xx.xxx.28:8443] Registering pool release on close event for channel
[26ba9590, L:/xx.xx.xx.47:42648 - R:xxxxxx-clusterip.svc.cluster.local/xxx.xx.xxx.28:8443] Channel connected, now: 1 active connections, 0 inactive connections and 0 pending acquire requests.
[26ba9590-1, L:/xx.xx.xx.47:42648 - R:xxxxxx-clusterip.svc.cluster.local/xxx.xx.xxx.28:8443] Channel activated
[26ba9590-1, L:/xx.xx.xx.47:42648 - R:xxxxxx-clusterip.svc.cluster.local/xxx.xx.xxx.28:8443] Channel deactivated
[26ba9590-1, L:/xx.xx.xx.47:42648 - R:xxxxxx-clusterip.svc.cluster.local/xxx.xx.xxx.28:8443] Channel removed from pool
```

**Comment by violetagg** [comment] 2024-07-29 10:36
@syedyusufh So this shows that you are using one and the same pool, the problem is that the connection is closed instead of reused. Can you check whether in request/response headers you have `Connection:close`. Basically you have to track why the connection is closed.

**Comment by syedyusufh** [comment] 2024-07-29 15:18
Thanks @violetagg , yes we found `Connection: close` when K8s clusterIp is used

**Comment by violetagg** [comment] 2024-07-29 15:36
Ok that explains why the connections in the pool are not reused. Closing the issue.

**Comment by syedyusufh** [comment] 2024-08-29 10:58
Sorry to reopen this issue.

Why would the log ```Registering pool release on close event for channel``` get printed even before the request is made. It is printed immediately along with the pool creation ```Creating a new [http2.http] client pool```

Earlier case was due to `Connection: close` after the response was received. In this case, right after the pool creation the channel is marked to be releases.

```
Creating a new [http2.http] client pool [PoolFactory{evictionInterval=PT0S, leasingStrategy=fifo, maxConnections=500, maxIdleTime=-1, maxLifeTime=-1, metricsEnabled=false, pendingAcquireMaxCount=-1, pendingAcquireTimeout=45000}] for [xxxx.xxxxx.xxxxxxx.xxxx.com/<unresolved>:443]

Creating a new [http] client pool [PoolFactory{evictionInterval=PT0S, leasingStrategy=fifo, maxConnections=500, maxIdleTime=-1, maxLifeTime=-1, metricsEnabled=false, pendingAcquireMaxCount=1000, pendingAcquireTimeout=45000}] for [xxxx.xxxxx.xxxxxxx.xxxx.com/<unresolved>:443]

[54a94dcb, L:/10.xx.xx.2xx:45332 - R:xxxx.xxxxx.xxxxxxx.xxxx.com/10.xx.xx.1xx:443] Registering pool release on close event for channel
```

**Comment by syedyusufh** [comment] 2024-08-31 05:42
@violetagg could you please reopen this? thanks

**Comment by violetagg** [comment] 2024-09-10 06:06
@syedyusufh 

> Why would the log Registering pool release on close event for channel get printed even before the request is made. It is printed immediately along with the pool creation Creating a new [http2.http] client pool

When we open a connection, we immediately start listening for a close event so that we can remove a closed connection from the connection pool.

**Comment by syedyusufh** [comment] 2024-09-10 07:54
Thanks @violetagg , makes sense.

Let us say, we have the below scenario,

https://abcd.com/uri1 with `ConnectTimeout` of 1s, `ResponseTimeout` of 2s
https://abcd.com/uri2 with `ConnectTimeout` of 1s, `ResponseTimeout` of 5s
https://abcd.com/uri3 with `ConnectTimeout` of 5s, `ResponseTimeout` of 10s
For the above scenario we are creating a total 3 `HttpClient` Pool as the `ConnectTimeout` and `ResponseTimeout` are different in all 3.

Is this a normal way to have 3 `ConnectionPools` for 3 different URLs? Or can they be controlled to share the same `ConnectionPool`?

Thanks

**Comment by violetagg** [comment] 2024-09-10 08:40
@syedyusufh you cannot share the connection pool because of the connect timeout. When you need to establish a new connection, which one of the three configurations, the connection pool should use?

**Comment by syedyusufh** [comment] 2024-09-10 09:27
> you cannot share the connection pool because of the connect timeout.

Thanks, we are with the same understanding

> When you need to establish a new connection, which one of the three configurations, the connection pool should use?

We are associating the `HttpClient` constructed with `WebClient` and using it specifically.

Everything is working as expected and mentioned in the Reactor Netty Documentation. Thanks a lot for your time and valuable help !! We can close this issue now.

**Closed** 2024-09-10 09:47 UTC
Labels: status/invalid
