### ISSUE TITLE
Brotli support in Reactor Netty

### ISSUE THREAD

**Issue by fbrisbart** [reactor/reactor-netty#2116] opened 2022-03-22 13:32 UTC
## Motivation

It's commonly accepted that **Brotli compression is more efficient than gzip**.

I'd like to use it with Reactor Netty to reduce my network payload and save a lot of transfer cost.

## Desired solution

When compression is enabled, only the default ones (gzip, deflate) are currently available  -- [see HttpServerOperations](https://github.com/reactor/reactor-netty/blob/67995d2384d830a404c14f0919d0e1e67f709ce3/reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java#L546)
It'll be great to be able to add **any desired CompressionOptions** to the compression handler.

This will allow to add Brotli and any new compression encoder (zstd for example)

**Comment by violetagg** [comment] 2022-03-22 14:55
@fbrisbart I'm adding this to `1.0.x` backlog.

**Comment by glennosss** [comment] 2022-03-25 00:42
@fbrisbart I researched doing this as well. What I found is you should never compress dynamic content using Brotli as it's _way way too slow_ - you should only ever use gzip for this.

Brotli is only really a good idea for _static content_ which you can compress in an _offline_ way before hand. I highly recommend minifying all your CSS/HTML/Javascript/etc then offline Brotli compressing them at maximum compression.


**[Unrelated but interesting]**

If you do go for offline compression, I'd highly recommend also offline converting all JPEG/PNG/GIF to WebP/AVIF and then based off the "Accept" header serving the smallest image format the browser supports.
```
       [Chrome ] Accept: ...image/avif, image/webp... <-- Chrome/Chromium browsers support both WebP/AVIF
       [Firefox] Accept: ...image/webp...             <-- All other browsers support WebP - which is normally about half the JPEG size.
```

**Comment by glennosss** [comment] 2022-03-25 01:09
> @fbrisbart I'm adding this to `1.0.x` backlog.

@violetagg I recommend removing this from the backlog. It's impractical. Consider adding something like https://github.com/lz4/lz4-java support instead.

**Comment by fbrisbart** [comment] 2022-03-25 09:00
I actually tested the brotli compression on our prod dynamic content with a WebServerConfiguration class.
I didn't impact the response time, but it didn't help on reducing the network payload significantly
NB: I used the default compression quality (4) + my average response content size are ~50/100k uncompressed

So, I somehow confirmed the "don't use brotli for dynamic content" assertion 

If anyone is still interested, here's the WebServerConfiguration class allowing to add any compressor (not only Brotli)
```
@Configuration
public class WebServerConfiguration {
    @Bean
    public ReactiveWebServerFactory reactiveWebServerFactory() {
        NettyReactiveWebServerFactory factory = new NettyReactiveWebServerFactory();
        factory.addServerCustomizers(builder -> builder.doOnChannelInit(
                (connectionObserver, channel, socketAddress) -> {
                    HttpContentCompressor handler = new HttpContentCompressor(gzip(), brotli(), deflate());
                    channel.pipeline().addBefore(HttpTrafficHandler, CompressionHandler, handler);
                }
        ));
        return factory;
    }
}
```

**Comment by violetagg** [comment] 2022-03-25 09:12
@glennosss @fbrisbart Thanks for the additional information. Let's close this with `has-workaround`.

**Closed by violetagg** 2022-03-25 09:12 UTC
Labels: status/has-workaround

**Comment by ohadgur** [comment] 2023-06-05 13:02
@fbrisbart sorry for bumping this thread after a year :)
Did you by any chance got it to work for http2 as well? It seems that `doOnChannelInit` isn't called for the streams' channels - not sure if by design.
It works perfectly for http1 btw

**Comment by fbrisbart** [comment] 2023-06-09 09:15
@ohadgur 
After testing Brotli, it appeared that the compression was no better than gzip in my case. So, I didn't go further and didn't try it for http2.

**Comment by ohadgur** [comment] 2023-06-11 08:09
@fbrisbart I see, thanks. BTW I looked at the current implementation of https://github.com/reactor/reactor-netty/blob/main/reactor-netty-http/src/main/java/reactor/netty/http/server/SimpleCompressionHandler.java and saw that brotli compression support was added, so hopefully, it would be much easier to integrate when the new version is out.

**Comment by ohadgur** [comment] 2023-06-29 06:30
@violetagg sorry I'm re-opening this - but is it possible to port the new `SimpleCompressionHandler` implementation (bascially calling the super constructor with a null array)  to versions 1.0.X ? we would really benefit from brotli in our springboot services, and it's considered a blocker for some teams to move to springboot.
Thanks! let me know if I should open an additional issue for that.

**Comment by violetagg** [comment] 2023-06-29 08:06
@ohadgur I backported the change to 1.0.34-SNAPSHOT

**Comment by ohadgur** [comment] 2023-07-04 12:21
@violetagg do you have any estimation for the new release?

**Comment by violetagg** [comment] 2023-07-04 12:58
@ohadgur The plan is next week.
