### ISSUE TITLE
Cancelling session.receive() causes the session termination 

### ISSUE THREAD

**Issue by sergiusz-n** [reactor/reactor-netty#967] opened 2020-01-21 14:35 UTC
After switching from _reactor-netty:0.8.x_ to _reactor-netty:0.9.x_ the aforementioned behaviour got changed.

Using `.take()`/ `.takeWhile()`/ `.takeUntil()` operator on inbound mesaages  cause canceling the Publisher signal, but the question is... 
Should cancelling `session.receive()` Flux cause the whole session termination immediately? 

In the given example, WebSocket handler on the server side expect to receive inbound messages and feed `someConsumer` with them (till some condition met), while independently sending back the outbound stream generated by `someProducer`.  The sessions is meant not to be cloded until _slower_ send operation is finished.   

#### ??? Expected Behaviour ???
*_I am unsure whether it is a bug or the result of the fix in 0.8.x version. But as the things are now both versions are inconsistent._*  

#### Actual Behaviour (since 0.9.0)
```
[or-http-epoll-3] r.n.http.server.HttpServerOperations     : [id: 0xa775493e, L:/127.0.0.1:8080 - R:/127.0.0.1:39055] Cancelling Websocket inbound. Closing Websocket
```

#### Steps to Reproduce
Sample WebSocket server implementation
```java
public class WSHandler implements WebSocketHandler {

    @Override
    public Mono<Void> handle(WebSocketSession session) {
        Flux<String> somePublisher = Flux.range(1,10)
                .map(i -> Integer.toString(i))
                .delayElements(Duration.ofSeconds(1));

        ReplayProcessor<String> someConsumer = ReplayProcessor.create();

        return Mono.when(
                session
                        .send(somePublisher.map(session::textMessage)),
                session
                        .receive()
                        .map(WebSocketMessage::getPayloadAsText)
                        .takeUntil(msg -> msg.equals("5"))
                        .subscribeWith(someConsumer)
                        .doOnDiscard(PooledDataBuffer.class, DataBufferUtils::release)
                        .then()
        );
    }
```
and the test:
```java
    @Test
    void givenSentMessagesWhenReceiveAllResponsesThenSendCloseToClient() {
        WebSocketClient client = new ReactorNettyWebSocketClient();

        ReplayProcessor<String> clientFlux = ReplayProcessor.create();

        Flux<String> toSend = Flux.range(1, 10).map(i -> Integer.toString(i));

        client.execute(
                    URI.create("ws://localhost:8080/test"),
                    session ->
                            Mono.when(
                                    session
                                            .send(toSend.map(session::textMessage)),
                                    session
                                            .receive()
                                            .map(WebSocketMessage::getPayloadAsText)
                                            .subscribeWith(clientFlux)
                                            .then()
                            )
                )
                .block(Duration.ofMillis(20000));

        StepVerifier.create(clientFlux)
                .expectNextCount(10)
                .verifyComplete();
    }
```

#### Your Environment

* Reactor version(s) used: reactor-netty:0.8.15 and reactor-netty:0.9.4
* JVM version (`javar -version`): 11
* OS and version (eg `uname -a`): Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64 GNU/Linux

**Comment by violetagg** [comment] 2020-01-21 14:52
@sergiusz-n Please provide a reproducible scenario only with Reactor Netty so that we can better isolate the component where the issue resides.

**Comment by sergiusz-n** [comment] 2020-01-21 22:22
@violetagg 
I _may_ try to provide you with Reactor Netty scenario, but meanwhile 
the version of Spring was the same (i.e. `'org.springframework.boot' version '2.2.0.RELEASE'`)` and the discrepancy was seen by just playing around with different versions of Reactor Netty (in my case they were `'io.projectreactor.netty:reactor-netty:0.8.15.RELEASE'` and  'io.projectreactor.netty:reactor-netty:0.9.4.RELEASE').

**Comment by violetagg** [comment] 2020-01-22 12:52
I came up with this and it reproduces your scenario

```
@Test
public void testIssue967() {
	Flux<String> somePublisher = Flux.range(1, 10)
	                                 .map(i -> Integer.toString(i))
	                                 .delayElements(Duration.ofSeconds(1));

	ReplayProcessor<String> someConsumer = ReplayProcessor.create();

	DisposableServer server =
			HttpServer.create()
			          .port(0)
			          .wiretap(true)
			          .handle((req, res) ->
			              res.sendWebsocket((in, out) ->
			                  out.sendString(somePublisher)
			                     .then(in.receiveFrames()
			                             .cast(TextWebSocketFrame.class)
			                             .map(TextWebSocketFrame::text)
			                             .takeUntil(msg -> msg.equals("5"))
			                             .subscribeWith(someConsumer)
			                             .then())))
			          .bindNow();

	ReplayProcessor<String> clientFlux = ReplayProcessor.create();

	Flux<String> toSend = Flux.range(1, 10)
	                          .map(i -> Integer.toString(i));

	HttpClient.create()
	          .port(server.port())
	          .wiretap(true)
	          .websocket()
	          .uri("/")
	          .handle((in, out) ->
	              out.sendString(toSend)
	                 .then(in.receiveFrames()
	                         .cast(TextWebSocketFrame.class)
	                         .map(TextWebSocketFrame::text)
	                         .subscribeWith(clientFlux)
	                         .then()))
	          .subscribe();

	StepVerifier.create(clientFlux)
	            .expectNextCount(10)
	            .verifyComplete();

	server.disposeNow();
}
```

**Comment by violetagg** [comment] 2020-01-22 13:53
This behaviour is caused by a fix in 0.9.x 
https://github.com/reactor/reactor-netty/commit/78950ac5d3032bd08c7e5e2b35d27e20253acbf6#diff-513b1db3a0b468f7712c0eb8fcb702f6R169-R176

If you want to take only some frames from the channel without closing it you can do something as the snippet below (note `.publish().autoConnect()`):

```
public class WSHandler implements WebSocketHandler {

    @Override
    public Mono<Void> handle(WebSocketSession session) {
        Flux<String> somePublisher = Flux.range(1,10)
                .map(i -> Integer.toString(i))
                .delayElements(Duration.ofSeconds(1));

        ReplayProcessor<String> someConsumer = ReplayProcessor.create();

        return Mono.when(
                session
                        .send(somePublisher.map(session::textMessage)),
                session
                        .receive()
                        .map(WebSocketMessage::getPayloadAsText)
                        .publish()
                        .autoConnect()
                        .takeUntil(msg -> msg.equals("5"))
                        .subscribeWith(someConsumer)
                        .doOnDiscard(PooledDataBuffer.class, DataBufferUtils::release)
                        .then()
        );
    }
```

I committed a test 0aa632e717f9503c57944533377491d04dacb7f4 in our repository for this use case.

**Closed by violetagg** 2020-01-22 13:53 UTC
Labels: status/invalid

**Comment by sergiusz-n** [comment] 2020-01-22 14:26
@violetagg thanks for the quick responses!
So, I wonder what behaviour is considered to be wrong: 0.8.15 or 0.9.4. 
The question just to clarify my confusion: the current status came as a side-effect for the [#533] (https://github.com/reactor/reactor-netty/issues/533) fix or it was done _intentionally_, since `.take(...)` operators should have been cancelling sessions, but didn't do so in 0.8.x and my originally sample code worked occasionally.

It seems that the following code in [WebsocketClientOperations.java](https://github.com/reactor/reactor-netty/blob/master/src/main/java/reactor/netty/http/client/WebsocketClientOperations.java) makes the difference:
```java
	@Override
	protected void onInboundCancel() {
		if (log.isDebugEnabled()) {
			log.debug(format(channel(), "Cancelling Websocket inbound. Closing Websocket"));
		}
		sendCloseNow(null, f -> terminate());
	}
```  

would you fix it in next 0.8.x releases for the sake of consistency?

**Comment by violetagg** [comment] 2020-01-22 15:09
It is not a side effect it is done intentionally.
Currently we have this implementation which is the desired implementation
https://github.com/reactor/reactor-netty/blob/0.9.x/src/main/java/reactor/netty/http/client/WebsocketClientOperations.java#L157-L162
https://github.com/reactor/reactor-netty/blob/0.9.x/src/main/java/reactor/netty/http/server/WebsocketServerOperations.java#L178-L183

We didn't change 0.8.x because of the change in the behaviour.

**Comment by sergiusz-n** [comment] 2020-01-22 15:14
@violetagg thanks for the clarifications and for your time!
