### ISSUE TITLE
Export both macOS native DNS resolvers

### ISSUE THREAD

**Issue by pluttrell** [reactor/reactor-netty#2544] opened 2022-10-13 08:19 UTC
Many people are reporting issues using Netty on M1 Macs ([ref](https://github.com/netty/netty/issues/11020#issuecomment-1220533248)).

The POM for v1.0.24 includes the following:

```
<dependencies>
  <dependency>
    <groupId>io.netty</groupId>
    <artifactId>netty-resolver-dns-native-macos</artifactId>
    <version>4.1.82.Final</version>
    <classifier>osx-x86_64</classifier>
    <scope>compile</scope>
    <exclusions>
      <exclusion>
        <artifactId>commons-logging</artifactId>
        <groupId>commons-logging</groupId>
      </exclusion>
    </exclusions>
  </dependency>
<dependencies>
```

Note the single classier: `osx-x86_64`.

`reactor-netty-core/build.gradle` includes the following starting on [line 63](https://github.com/reactor/reactor-netty/blob/7d28d2ac1db1feb9c64b504727fb8ee77aaf91d1/reactor-netty-core/build.gradle#L63):
```
	if (!"$nettyVersion".endsWithAny("SNAPSHOT")) {
		if (osdetector.classifier == "osx-x86_64" || osdetector.classifier == "osx-aarch_64") {
			api "io.netty:netty-resolver-dns-native-macos:$nettyVersion$os_suffix"
		}
		else {
			api "io.netty:netty-resolver-dns-native-macos:$nettyVersion:osx-x86_64"
		}
	}
	else {
		// MacOS binaries are not available for Netty SNAPSHOT version
		api "io.netty:netty-resolver-dns-native-macos:$nettyVersion"
	}
```

The `io.netty:netty-resolver-dns-native-macos` dependencies declared are thus being controlled by the build machine's OS. 

Should the build machine impact the declared dependencies?

I propose that **both** macOS architectures be declared as dependencies. 

Perhaps changing the above block to:

```
	if (!"$nettyVersion".endsWithAny("SNAPSHOT")) {
		api "io.netty:netty-resolver-dns-native-macos:$nettyVersion:osx-x86_64"
		api "io.netty:netty-resolver-dns-native-macos:$nettyVersion:osx-aarch_64"
	}
	else {
		// MacOS binaries are not available for Netty SNAPSHOT version
		api "io.netty:netty-resolver-dns-native-macos:$nettyVersion"
	}
```

**Comment by pderop** [comment] 2022-10-13 09:03
Hello @pluttrell ,

This issue is a duplicate of the recent #2440 issue; and we actually do not desire to include all natives in jars, and the osx-x86_64  will even be removed in upcoming 2.0.x version, so it is up to the user to select which native dependencies are needed.

Please have a look into the #2440 for all the details; 

thank you.

**Comment by pderop** [comment] 2022-10-13 09:04
closing this as a duplicate of the #2440 issue, please reopen if needed.

**Closed by pderop** 2022-10-13 09:04 UTC
Labels: type/bug, status/need-triage

**Comment by gmuth** [comment] 2022-11-29 18:57
If it is up to user to select which native dependency is used than why do YOU during library build decide on the x86_64 dependency?
I guess because it's not possible with this kind of dependency layout to implement "the library user has to decide". Consequently you'd have to remove the dependency completely and declare it as optional in the documentation if it's required for a specific feature and document what needs to be done in order to use his feature.

**Comment by violetagg** [comment] 2022-11-30 14:48
@gmuth Take a look at my response here https://github.com/reactor/reactor-netty/issues/2440#issuecomment-1220762196 and check this PR #2448
I also contributed some improvements to Netty project here https://github.com/netty/netty/pull/12732 and here https://github.com/netty/netty/pull/12950

In addition I would like to mention that there is now PR for Windows OS specific nameserver resolution. If that is accepted there will be natives also for Windows.
