### ISSUE TITLE
Memory Leak on WebClient usage

### ISSUE THREAD

**Issue by fmutluay** [reactor/reactor-netty#2586] opened 2022-11-24 18:06 UTC
We are experiencing with OutOfMemory error when using webclient with reactive netty stack.
Tried to get enable memory leak log via parameters like "-Dio.netty.leakDetection.level=paranoid -Dio.netty.leakDetectionLevel=paranoid _reactor.netty.channel.LeakDetection=DEBUG" but no success.

## Expected Behavior

No Leak.

## Actual Behavior

When we run the application, every request creating a reactor.netty.internal.shaded.reactor.pool.SimpleDequePool and these is not gc'ed. (Also tried with -Dio.netty.allocator.type=unpooled option)

When we analyze the heap-dump, it is pointing to leak suspect as
```One instance of "reactor.netty.http.HttpResources" loaded by "org.springframework.boot.loader.LaunchedURLClassLoader @ 0xfc057638" occupies 49.489.144 (77,71%) bytes. The memory is accumulated in one instance of "java.util.concurrent.ConcurrentHashMap$Node[]" loaded by "<system class loader>". ```
(We have tried with -Xms64m -Xms16m to get OOM issue fastly. ~7000 unique request)

From heap-dump histogram output:
```
Class Name                                                                                            | Objects | Shallow Heap | Retained Heap
-----------------------------------------------------------------------------------------------------------------------------------------------
java.util.concurrent.ConcurrentHashMap                                                                |     731 |       46.784 | >= 52.373.800
java.util.concurrent.ConcurrentHashMap$Node[]                                                         |     311 |      397.968 | >= 52.335.696
java.util.concurrent.ConcurrentHashMap$Node                                                           |  37.575 |    1.202.400 | >= 51.832.712
reactor.netty.http.HttpResources                                                                      |       1 |           32 | >= 49.489.480
reactor.netty.resources.DefaultPooledConnectionProvider                                               |       1 |           56 | >= 49.489.136
reactor.netty.internal.shaded.reactor.pool.SimpleDequePool                                            |   6.971 |      501.912 | >= 47.966.544
reactor.netty.internal.shaded.reactor.pool.DefaultPoolConfig                                          |   6.971 |      446.144 | >= 36.036.688
reactor.core.publisher.MonoCreate                                                                     |   6.972 |      111.552 | >= 35.144.464
reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnectionAllocator$$Lambda$867         |   6.971 |      111.536 | >= 35.032.864
reactor.netty.http.client.HttpClientConfig                                                            |  13.942 |    3.011.472 | >= 34.965.560
reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnectionAllocator                     |   6.971 |      223.072 | >= 34.922.032
org.springframework.http.client.reactive.ReactorClientHttpConnector$$Lambda$838                       |   6.971 |      223.072 | >= 14.804.720
reactor.netty.tcp.SslProvider                                                                         |   6.975 |      502.200 | >= 13.590.584
io.netty.handler.ssl.JdkSslClientContext                                                              |   6.973 |      334.704 | >= 12.643.592
java.lang.String                                                                                      | 174.507 |    4.188.168 | >= 12.447.416
javax.net.ssl.SSLContext                                                                              |   6.973 |      167.352 | >= 11.416.464
byte[]                                                                                                | 211.272 |   11.362.616 | >= 11.362.616
java.util.concurrent.ConcurrentLinkedDeque                                                            |  14.404 |      345.696 | >= 11.316.656
sun.security.ssl.SSLContextImpl$TLSContext                                                            |   6.973 |      334.704 | >= 11.286.152
java.util.concurrent.ConcurrentLinkedDeque$Node                                                       |  28.864 |      692.736 | >= 10.970.376
reactor.netty.internal.shaded.reactor.pool.SimpleDequePool$QueuePooledRef                             |  13.863 |      776.328 | >= 10.205.008
org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction$$Lambda$835|   6.971 |      167.304 | >= 10.193.952
io.netty.channel.epoll.EpollSocketChannel                                                             |   6.932 |      887.296 | >= 10.146.312
org.springframework.web.reactive.function.client.DefaultClientRequestBuilder$BodyInserterRequest      |   6.972 |      334.656 |  >= 9.862.392
reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnection                              |   6.932 |      277.280 |  >= 9.821.768
-----------------------------------------------------------------------------------------------------------------------------------------------
```

When we collect info via ../jdk/jmap -histo [pid]
```
 num     #instances         #bytes  class name (module)
-------------------------------------------------------
   1:        619617      104935304  [B (java.base@11.0.16.1)
   2:        584024       60401384  [I (java.base@11.0.16.1)
   3:        218171       56510232  [J (java.base@11.0.16.1)
   4:        569946       43412952  [Ljava.lang.Object; (java.base@11.0.16.1)
   5:        201841       16147152  [S (java.base@11.0.16.1)
   6:        211423       14784376  [Ljava.util.HashMap$Node; (java.base@11.0.16.1)
   7:         14287       11013416  [C (java.base@11.0.16.1)
   8:        334995       10719840  java.util.HashMap$Node (java.base@11.0.16.1)
   9:        119790        8624880  java.util.regex.Matcher (java.base@11.0.16.1)
  10:        176140        8454720  java.util.HashMap (java.base@11.0.16.1)
  11:        344186        8260464  java.lang.String (java.base@11.0.16.1)
  12:        242461        6400040  [Ljava.lang.String; (java.base@11.0.16.1)
  13:        143539        5741560  java.util.HashMap$KeyIterator (java.base@11.0.16.1)
  14:         88645        4254960  io.netty.util.ResourceLeakDetector$TraceRecord
  15:         17146        3703536  reactor.netty.http.client.HttpClientConfig
  16:         87440        3497600  java.util.LinkedHashMap$Entry (java.base@11.0.16.1)
  17:         62281        3487736  java.util.LinkedHashMap (java.base@11.0.16.1)
  18:        137833        3307992  java.util.ArrayList (java.base@11.0.16.1)
  19:        100673        2416152  java.math.MutableBigInteger (java.base@11.0.16.1)
  20:        144397        2310352  java.util.HashSet (java.base@11.0.16.1)
  21:        143302        2292832  java.util.HashMap$KeySet (java.base@11.0.16.1)
  22:        119790        1916640  [Ljava.util.regex.IntHashSet; (java.base@11.0.16.1)
  23:         31962        1789872  sun.security.util.MemoryCache$SoftCacheEntry (java.base@11.0.16.1)
  24:         55325        1770400  java.util.concurrent.ConcurrentHashMap$Node (java.base@11.0.16.1)
  ...
  ...
  70:          8090         388320  org.springframework.web.reactive.function.client.DefaultClientRequestBuilder$BodyInserterRequest
  71:         16156         387744  java.util.concurrent.ConcurrentLinkedDeque (java.base@11.0.16.1)
  72:         24025         384400  sun.security.ssl.SessionId (java.base@11.0.16.1)
  73:         11859         379488  java.security.MessageDigest$Delegate (java.base@11.0.16.1)
  74:          7849         376752  io.netty.handler.ssl.JdkSslClientContext
  75:          7849         376752  sun.security.ssl.SSLContextImpl$TLSContext (java.base@11.0.16.1)
  76:          7847         376656  reactor.netty.transport.ProxyProvider
  77:         15686         376464  java.net.Inet4Address (java.base@11.0.16.1)
  78:          7665         367920  io.netty.channel.DefaultChannelPipeline
  79:         15330         367920  io.netty.channel.VoidChannelPromise
  80:         15330         367920  io.netty.util.DefaultAttributeMap$DefaultAttribute
  81:         14867         356808  java.util.Collections$UnmodifiableRandomAccessList (java.base@11.0.16.1)
  82:         11666         320288  [Ljava.nio.ByteBuffer; (java.base@11.0.16.1)
  83:          7847         313880  reactor.netty.http.client.HttpResponseDecoderSpec
  84:          4866         311424  java.util.concurrent.ConcurrentHashMap (java.base@11.0.16.1)
  85:          7665         306600  io.netty.channel.AbstractChannel$CloseFuture
  86:          7665         306600  reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnection
  87:         19090         305440  org.springframework.util.MultiValueMapAdapter
  88:         12640         303360  java.util.LinkedList$Node (java.base@11.0.16.1)
  89:          9186         293952  jdk.internal.math.FloatingDecimal$ASCIIToBinaryBuffer (java.base@11.0.16.1)
  90:          5962         286176  com.sun.crypto.provider.GCTR (java.base@11.0.16.1)
  91:         11687         280488  java.util.Arrays$ArrayList (java.base@11.0.16.1)
  92:         16126         258016  java.util.HashMap$EntrySet (java.base@11.0.16.1)
  93:          7847         251104  org.springframework.http.client.reactive.ReactorClientHttpConnector$$Lambda$826/0x0000000100634840
  94:          7847         251104  reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnectionAllocator
  95:          7666         245312  io.netty.channel.AdaptiveRecvByteBufAllocator
  96:          7665         245280  io.netty.channel.DefaultChannelId
  ...
  ...
 116:          7849         188376  [Lsun.security.ssl.EphemeralKeyManager$EphemeralKeyPair; (java.base@11.0.16.1)
 117:          7849         188376  javax.net.ssl.SSLContext (java.base@11.0.16.1)
 118:          7848         188360  [Lreactor.netty.http.HttpProtocol;
 119:          7848         188352  java.util.function.BiPredicate$$Lambda$87/0x0000000100175040 (java.base@11.0.16.1)
 120:          7847         188328  org.springframework.web.reactive.function.BodyInserters$$Lambda$805/0x0000000100631040
 121:          7847         188328  org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction
 122:          7847         188328  org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction$$Lambda$823/0x0000000100635c40
 123:          7847         188328  reactor.netty.http.client.HttpConnectionProvider
 124:          7847         188328  reactor.netty.internal.shaded.reactor.pool.AllocationStrategies$SizeBasedAllocationStrategy
 125:          7847         188328  reactor.netty.resources.PooledConnectionProvider$PoolKey
 126:          3306         185136  java.util.stream.ReferencePipeline$Head (java.base@11.0.16.1)
 127:          1937         184024  [Lsun.security.ssl.SSLHandshake; (java.base@11.0.16.1)
 128:          7665         183960  io.netty.channel.SucceededChannelFuture
 129:          7665         183960  io.netty.channel.epoll.LinuxSocket
 130:          7502         180048  sun.security.jca.ProviderList$ServiceList$1 (java.base@11.0.16.1)
 131:          5566         178112  com.sun.crypto.provider.HmacCore$HmacSHA256 (java.base@11.0.16.1)
 132:          5298         169536  org.springframework.http.MediaType
 133:          6853         164472  java.lang.StringBuilder (java.base@11.0.16.1)
 134:          6776         162624  sun.security.jca.GetInstance$Instance (java.base@11.0.16.1)
 135:          3916         156640  io.netty.channel.DefaultChannelPromise
 136:          9547         152752  io.netty.handler.codec.http.DefaultHttpHeaders
 137:          7027         150528  [Ljava.lang.reflect.Type; (java.base@11.0.16.1)
 138:          2954         148432  [[I (java.base@11.0.16.1)
  ...
  ...
 144:          8332         133312  reactor.core.publisher.MonoCreate
 145:          8089         129424  reactor.core.publisher.MonoJust
 146:          7907         126512  io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle$1
 147:          7872         125952  reactor.util.Loggers$Slf4JLogger
 148:          3934         125888  java.util.LinkedList (java.base@11.0.16.1)
 149:          7852         125632  reactor.core.Disposables$AlwaysDisposable
 150:          7852         125632  sun.security.provider.NativePRNG (java.base@11.0.16.1)
 151:          7849         125584  io.netty.util.DefaultAttributeMap
 152:          7849         125584  sun.security.ssl.EphemeralKeyManager (java.base@11.0.16.1)
 153:          7847         125552  com.rasyonet.client.configuration.ClientRestServiceConfiguration$$Lambda$776/0x0000000100617440
 154:          7847         125552  org.springframework.http.client.reactive.ReactorClientHttpConnector
 155:          7847         125552  reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnectionAllocator$$Lambda$855/0x0000000100643c40
 156:          7847         125552  reactor.netty.resources.PooledConnectionProvider$PoolFactory$$Lambda$868/0x000000010065a040
 157:          7847         125552  reactor.netty.transport.ProxyProvider$$Lambda$781/0x0000000100615840
```

## Steps to Reproduce

```java
@Configuration
public class ClientRestServiceConfiguration {
                
    @Value("${service.endpoint.baseurl}")
    private String baseURL;

    @Value("${service.connect.timeout}")
    private int connectionTimeout;

    @Value("${service.read.timeout}")
    private int readTimeout;

    @Value("${service.write.timeout}")
    private int writeTimeout;

    @Value("${service.http.proxy.host}")
    private String serviceHttpProxy;

    @Value("${service.http.proxy.port}")
    private int serviceHttpProxyPort;

    @Value("${service.endpoint.url.context}")
    private String serviceEndpointUrlContext;

    @Value("${service.basic-auth.username}")
    private String basicAuthUsername;

    @Value("${service.basic-auth.password}")
    private String basicAuthPassword;

    public WebClient getWebClient() throws SSLException
    {

        SslContext sslContext = SslContextBuilder
                .forClient()
                .trustManager(InsecureTrustManagerFactory.INSTANCE)
                .build();

        HttpClient httpClient = HttpClient.create()
                .secure(t -> t.sslContext(sslContext) )
                .tcpConfiguration(client ->
                        client.option(ChannelOption.CONNECT_TIMEOUT_MILLIS, connectionTimeout)
                                .doOnConnected(conn -> conn
                                        .addHandlerLast(new ReadTimeoutHandler(readTimeout))
                                        .addHandlerLast(new WriteTimeoutHandler(writeTimeout))))
                .tcpConfiguration(tcpClient -> tcpClient
                        .proxy(proxy -> proxy
                                .type(ProxyProvider.Proxy.HTTP)
                                .host(serviceHttpProxy)
                                .port(serviceHttpProxyPort)))

                ;

        ClientHttpRequestFactory clientHttpRequestFactory = new HttpComponentsClientHttpRequestFactory(httpClient);

        return WebClient.builder()
                .baseUrl(baseURL)
                .clientConnector(connector)
                .defaultHeader("Content-Type", MediaType.APPLICATION_JSON_VALUE)
                .filter(ExchangeFilterFunctions.basicAuthentication(basicAuthUsername, basicAuthPassword))
                .build();
    }

}


@Service
public class ConsumeClientService {


    private final ClientRestServiceConfiguration clientRestServiceConfiguration;

    @Autowired
    public RasyonetService(ClientRestServiceConfiguration clientRestServiceConfiguration) {
        this.clientRestServiceConfiguration = clientRestServiceConfiguration;
    }


    public Mono<String> callRestService(String contextPath, String request) throws SSLException {

        Mono<String> clientResponse = clientRestServiceConfiguration.getWebClient()
                .post()
                .uri(contextPath)
                .header("Content-Type","application/json")
                .body(Mono.just(request),String.class)
                .retrieve()
                .bodyToMono(String.class)
		.onErrorResume(e-> Mono.error(new RuntimeException(e.toString(),e)))
               ;

        return clientResponse;
    }

}

```

## Your Environment

* Reactor version(s) used: 
```reactor-netty-* v1.0.24```

* Other relevant libraries versions (eg. `netty`, ...):
```SpringBoot v2.7.5```

* JVM version (`java -version`): 
```java version "11.0.16.1" 2022-08-18 LTS
  Java(TM) SE Runtime Environment 18.9 (build 11.0.16.1+1-LTS-1)
  Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.16.1+1-LTS-1, mixed mode)
``` 

* OS and version (eg. `uname -a`): 
```RHEL 8.6```

**Comment by pderop** [comment] 2022-11-25 16:25
Hi @fmutluay ,

I could not reproduce any OOM using the code similar to what you have suggested.
So, can you elaborate more on the issue , and can you provide a sample reproducer project which I can build and test ?

thanks.

**Comment by fmutluay** [comment] 2022-11-27 16:59
Hi @pderop ,

I have created a private repo and shared the demo code with you.
[https://github.com/fmutluay/reactive-code-trial](url)

Demo project requires basic auth and it's using reqbin.com/post-online endpoint, everything set-up for your test.

> tried with

`for((i=1;i<=20000;i++));
 do
   curl -X GET "http://localhost:8080/test/json";
 done
`

we have identified the leak with jfr + visualvm runtime heap stat and other tools.

Thanks & Regards,
Fatih.

**Comment by pderop** [comment] 2022-11-28 17:54
Hello @fmutluay ,

Thanks for the reproducer project; I indeed could reproduce the OOM (using Gatling).

now, I think the issue here is that a new `WebClient` instance is created for each new rest service, which is very memory consuming, especially when using https.

So, I just changed `ConsumeClientService` from the demo in order to cache the WebClient and reuse it for every rest calls:

instead of:

```
public class ConsumeClientService {
    private final ClientRestServiceConfiguration clientRestServiceConfiguration;

    @Autowired
    public ConsumeClientService(ClientRestServiceConfiguration clientRestServiceConfiguration) throws SSLException {
        this.clientRestServiceConfiguration = clientRestServiceConfiguration;
    }


    public Mono<String> callRestService(String contextPath, String request) throws SSLException {

        Mono<String> clientResponse = clientRestServiceConfiguration.getWebClient()
                .post()
                ...
```

then do:

```
public class ConsumeClientService {
    private final ClientRestServiceConfiguration clientRestServiceConfiguration;
    private final WebClient webClient;

    @Autowired
    public ConsumeClientService(ClientRestServiceConfiguration clientRestServiceConfiguration) throws SSLException {
        this.clientRestServiceConfiguration = clientRestServiceConfiguration;
        this.webClient = clientRestServiceConfiguration.getWebClient();
    }


    public Mono<String> callRestService(String contextPath, String request) throws SSLException {

        Mono<String> clientResponse = webClient // clientRestServiceConfiguration.getWebClient()
                .post()
```

This fixed the issue and my Gatling scenario is not reproducing anymore any OOM, and the jstat -gcold command is then very stable:

```
    MC         MU       CCSC      CCSU         OC           OU       YGC    FGC    FGCT     CGC    CGCT       GCT   
   47552.0    47242.1    5952.0    5791.2      29696.0      24864.5    289     0     0.000   212     0.228     1.319
   47552.0    47242.1    5952.0    5791.2      29696.0      24864.5    289     0     0.000   212     0.228     1.319
```

I'm closing this issue, but feel free to reopen if you are not satisfied.
thanks.

**Closed by pderop** 2022-11-28 17:54 UTC
Labels: type/bug, for/user-attention
