### ISSUE TITLE
WebsocketServerOperations sends WebSocketCloseStatus 1005 which is not accepted by CloseWebSocketFrame

### ISSUE THREAD

**Issue by Johannes-Rost** [reactor/reactor-netty#1891] opened 2021-11-23 09:44 UTC
## Expected Behavior
No exception should occur when WebsocketServerOperations closes a Frame.

## Actual Behavior
reactor.netty.http.server.WebsocketServerOperations#onInboundNext sends a WebSocketCloseStatus.EMPTY (1005) which is not accepted by CloseWebSocketFrame created in reactor.netty.http.client.WebsocketClientOperations#sendClose(int, java.lang.String), because it is not considered valid by io.netty.handler.codec.http.websocketx.WebSocketCloseStatus#isValidStatusCode

## Steps to Reproduce
Error appears in our logs. I could not reproduce it localy. The stacktrace looks like this:

```
Stack Trace:
  reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.IllegalArgumentException: WebSocket close status code does NOT comply with RFC-6455: 1005
Caused by: java.lang.IllegalArgumentException: WebSocket close status code does NOT comply with RFC-6455: 1005
        at io.netty.handler.codec.http.websocketx.CloseWebSocketFrame.requireValidStatusCode(CloseWebSocketFrame.java:209)
        at io.netty.handler.codec.http.websocketx.CloseWebSocketFrame.<init>(CloseWebSocketFrame.java:69)
        at reactor.netty.http.client.WebsocketClientOperations.sendClose(WebsocketClientOperations.java:213)
        at org.springframework.web.reactive.socket.adapter.ReactorNettyWebSocketSession.close(ReactorNettyWebSocketSession.java:124)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125)
        at reactor.core.publisher.FluxFilter$FilterSubscriber.onNext(FluxFilter.java:113)
        at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:220)
        at reactor.core.publisher.FluxFirstWithSignal$FirstEmittingSubscriber.onNext(FluxFirstWithSignal.java:330)
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopePassingSpanSubscriber.java:88)
        at reactor.core.publisher.Operators$MonoInnerProducerBase.complete(Operators.java:2634)
        at reactor.core.publisher.SinkOneMulticast.tryEmitValue(SinkOneMulticast.java:70)
        at reactor.netty.http.server.WebsocketServerOperations.sendCloseNow(WebsocketServerOperations.java:258)
        at reactor.netty.http.server.WebsocketServerOperations.onInboundNext(WebsocketServerOperations.java:156)
        at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1372)
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1235)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1284)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

## Your Environment
Spring Cloud Gateway 3.0.5
Reactor Netty 1.0.12
Netty 4.1.69
Reactor Core 3.4.11

**Comment by violetagg** [comment] 2021-11-24 07:37
@Johannes-Rost 
https://github.com/reactor/reactor-netty/blob/a4ec7de39f38d2556ef228ed790abbcc3d1a2516/reactor-netty-http/src/main/java/reactor/netty/http/client/WebsocketClientOperations.java#L211-L214

This is an API that is called by those using Reactor Netty. It is never called by Reactor Netty itself.

According to the specification this status code cannot be sent as a status code for the close frame:

https://datatracker.ietf.org/doc/html/rfc6455#section-7.4.1

```
1005

      1005 is a reserved value and MUST NOT be set as a status code in a
      Close control frame by an endpoint.  It is designated for use in
      applications expecting a status code to indicate that no status
      code was actually present.
```

I'm closing this as invalid.

**Closed by violetagg** 2021-11-24 07:37 UTC
Labels: type/bug

**Comment by Johannes-Rost** [comment] 2021-11-24 08:53
@violetagg I have seen the specification, nevertheless Reactor Netty is using the status code 1005 and in the case auf Spring Cloud Gateway it also calls the code you mentioned.

https://github.com/reactor/reactor-netty/blob/23cba2ed12efc02fbc174b75f225d3a2a78b0805/reactor-netty-http/src/main/java/reactor/netty/http/server/WebsocketServerOperations.java#L150-L157

`reactor.netty.http.server.WebsocketServerOperations` uses `io.netty.handler.codec.http.websocketx.WebSocketCloseStatus#EMPTY` to `sendCloseNow` in Line 156, which in turns calls the code you mentioned above, which leads to the exception I described above:

```
        at reactor.netty.http.client.WebsocketClientOperations.sendClose(WebsocketClientOperations.java:213)
        at org.springframework.web.reactive.socket.adapter.ReactorNettyWebSocketSession.close(ReactorNettyWebSocketSession.java:124)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125)
        at reactor.core.publisher.FluxFilter$FilterSubscriber.onNext(FluxFilter.java:113)
        at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:220)
        at reactor.core.publisher.FluxFirstWithSignal$FirstEmittingSubscriber.onNext(FluxFirstWithSignal.java:330)
        at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopePassingSpanSubscriber.java:88)
        at reactor.core.publisher.Operators$MonoInnerProducerBase.complete(Operators.java:2634)
        at reactor.core.publisher.SinkOneMulticast.tryEmitValue(SinkOneMulticast.java:70)
        at reactor.netty.http.server.WebsocketServerOperations.sendCloseNow(WebsocketServerOperations.java:258)
        at reactor.netty.http.server.WebsocketServerOperations.onInboundNext(WebsocketServerOperations.java:156)
```

This behavior was introduced with https://github.com/reactor/reactor-netty/issues/1485

**Comment by violetagg** [comment] 2021-11-24 09:04
@Johannes-Rost

https://github.com/reactor/reactor-netty/blob/23cba2ed12efc02fbc174b75f225d3a2a78b0805/reactor-netty-http/src/main/java/reactor/netty/http/server/WebsocketServerOperations.java#L246-L265

This is the actual method implementation, as you can see Reactor Netty does not create a close frame with an invalid status code.
The second parameter that is `WebSocketCloseStatus.EMPTY` is used to notify the application for a the type of the close status.

As per specification

`1005 is a reserved value and MUST NOT be set as a status code in a Close control frame by an endpoint.`, Reactor Netty never sends such status code in a close frame, so I don't see a violation of the specification.

`It is designated for use in applications expecting a status code`, Reactor Netty notifies the application with `WebSocketCloseStatus.EMPTY`, when there is no status code in the close frame. I also think that we do not violate the specification here.

**Comment by Johannes-Rost** [comment] 2021-11-24 09:26
@violetagg I am not sure wether any specification is violated, but I think something is wrong here.
We have been seeing this exception sporadically in our logs recently and I took a look at the stack trace. Since it looks to me like Reactor Netty is using the status code itself (Line 156 of `WebsocketServerOperations`) and then rejecting it elsewhere (Line 213 of `WebsocketClientOperation`, respectively Line 206 of `io.netty.handler.codec.http.websocketx.CloseWebSocketFrame`) I have posted this ticket.

If you take a look at the stacktrace fragment from my last post, you can see that the status code is just handed down from `WebsocketServerOperations` Line 156 to Line 258 to [...] to `WebsocketClientOperations#sendClose(int, java.lang.String)` where a`CloseWebSocketFrame` is created and the exception is thrown.

Maybe this is also a mistake Spring Cloud Gateway makes when plugging the Reactor Netty components together, but since it looks to me for now like only Reactor Netty classes are involved, this is where I came in for now.

**Comment by violetagg** [comment] 2021-11-24 09:41
@Johannes-Rost From the stack trace we have

```
        at reactor.netty.http.client.WebsocketClientOperations.sendClose(WebsocketClientOperations.java:213)
        at org.springframework.web.reactive.socket.adapter.ReactorNettyWebSocketSession.close(ReactorNettyWebSocketSession.java:124)
```

I searched Spring Cloud repository and the only usage of `org.springframework.web.reactive.socket.WebSocketSession;` is here
https://github.com/spring-cloud/spring-cloud-gateway/blob/d94450561604a8bb6f1e263180c744c0ca57944a/spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/filter/WebsocketRoutingFilter.java#L200-L234

`proxySession.closeStatus()`/`session.closeStatus()` uses this implementation
https://github.com/spring-projects/spring-framework/blob/259bcd60fbbc5cdb8b230595a5004707f4c6ff23/spring-webflux/src/main/java/org/springframework/web/reactive/socket/adapter/ReactorNettyWebSocketSession.java#L127-L131

So  imho if something has to be done it should be in `WebsocketRoutingFilter`.

**Comment by Johannes-Rost** [comment] 2021-11-24 10:02
@violetagg If I understand it correctly `WebsocketServerOperations#onInboundNext` receives an `CloseWebSocketFragment` which is empty. Therefore the status code of the `CloseWebsocketFrame`created is `-1` which in turn leads to calling `sendCloseNow` with `WebSocketCloseStatus.EMPTY`.

The actual `Sink` behind `WebsocketServerOperations#onCloseState` in this case is `org.springframework.web.reactive.socket.adapter.ReactorNettyWebSocketSession#close(CloseStatus)`, which is currently only handing down the `CloseStatus#getCode` to `WebsocketClientOperations`. Instead it should check the status code and make shure to send a valid code. Correct?

Thank you very much for your patience.

**Comment by violetagg** [comment] 2021-11-24 10:16
@Johannes-Rost Yes that's correct. The API (`reactor.netty.http.websocket.WebsocketInbound#receiveCloseStatus`) used in 
https://github.com/spring-projects/spring-framework/blob/259bcd60fbbc5cdb8b230595a5004707f4c6ff23/spring-webflux/src/main/java/org/springframework/web/reactive/socket/adapter/ReactorNettyWebSocketSession.java#L127-L131
is only for notifying the applications for the type of the code status.

There are other status codes that also cannot be used in a close frame (it's not only 1005), so the applications have to be careful what kind of status code they use when sending a close frame.

**Comment by Johannes-Rost** [comment] 2021-11-24 10:25
@violetagg Should I file a bug for Spring Cloud Gateway or is this handled somehow via the `for/spring-cloud-gateway`tag?

**Comment by violetagg** [comment] 2021-11-24 10:26
@Johannes-Rost Yes you have to file the issue. This label is just to specify that the issue is in an external project.

**Comment by violetagg** [comment] 2021-11-24 11:43
@Johannes-Rost I created a PR #1896 in order to clarify in the javadoc that some status codes must not be used as such in a websocket close frame.
