### ISSUE TITLE
HTTP connection not always closed on dispose()

### ISSUE THREAD

**Issue by timurstrekalov** [reactor/reactor-netty#528] opened 2018-11-27 20:50 UTC
I apologise in advance for any obvious lack of understanding of inner workings of reactor-netty – I'm still rather new to the whole paradigm. However, I've noticed something that seems rather like a bug.

Basically, when an HTTP connection's Subscription object is disposed of quickly enough after subscribing, the connection doesn't get closed. I think the problem is in `reactor.netty.http.client.HttpClientConnect.MonoHttpConnect.TcpClientSubscriber` – it should be something like:

```
final static class TcpClientSubscriber implements CoreSubscriber<Connection> {

    final MonoSink<Connection> sink;
    final Disposable.Composite connections; // added

    TcpClientSubscriber(MonoSink<Connection> sink) {
        this.sink = sink;
        this.connections = Disposables.composite(); // added
    }

    @Override
    public void onSubscribe(Subscription s) {
        s.request(Long.MAX_VALUE);
    }

    @Override
    public void onNext(Connection connection) {
        connections.add(connection); // added
    }

    @Override
    public void onError(Throwable throwable) {
        connections.dispose(); // added
        sink.error(throwable);
    }

    @Override
    public void onComplete() {
        connections.dispose(); // added
    }

    @Override
    public Context currentContext() {
        return sink.currentContext();
    }
}
```

### Expected behavior

Calling `dispose()` on an HTTP request Subscription should always close the underlying connection.

### Actual behavior

Calling `dispose()` doesn't always close the connection.

### Steps to reproduce

Consider this simple, albeit very crude, example:

```
public static void main(String[] args) throws Exception {
    AtomicInteger openConnections = new AtomicInteger();

    DisposableServer server = HttpServer
            .create()
            .port(0)
            .handle((in, out) -> {
                openConnections.incrementAndGet();

                try {
                    Thread.sleep(500);
                } catch (InterruptedException e) {
                    throw new RuntimeException(e);
                }

                return out
                        .send(ByteBufFlux.fromString(Mono.just("test")))
                        .then()
                        .doOnTerminate(openConnections::decrementAndGet);
            })
            .bindNow();

    HttpClient httpClient = HttpClient
            .create()
            .addressSupplier(server::address);

    for (int i = 0; i < 100; i++) {
        httpClient
                .get()
                .response()
                .subscribe()
                .dispose();
    }

    Thread.sleep(2000);

    System.out.println("open connections: " + openConnections.get());
}
```

This would print more than 0 connections in the end (not necessarily all the time, I guess, but most of the time).

Note that I've actually experienced this in a real-life application using websockets, but it seems to apply to any HTTP connections.

### Reactor Netty version

0.8.3.RELEASE

### JVM version (e.g. `java -version`)

1.8.0_192

### OS version (e.g. `uname -a`)

Tested on Windows 7 and MacOS 10.14.1

**Comment by smaldini** [comment] 2018-11-27 22:44
Hey @timurstrekalov ! Thanks for your issue, it's pretty complete. 

So one thing to note, the TcpClientSubscriber will only receive one connection ever, and we don't use it but for forwarding errors as the Connection will also go in the setup ConnectionObserver which acts as a state machine for http lifecycle.

Then the problem is different and surprising, you are using Thread sleep on the server and that's going to block N loops (you should actually see openConnection.get at the end matches your `Runtime.getRuntime().availableProcessors()`).  The problem is worse than it seems because by default the same server threads are used by the client, so you might create a deadlock in the situation where you both run httpClient and httpServer in a same JVM.
 You can simulate a delay in a non blocking fashion like this : 

```java
DisposableServer server = HttpServer
				.create()
				.port(0)
				.handle((in, out) -> {
					openConnections.incrementAndGet();

					return out.sendString(Mono.just("test").delayElement(Duration.ofSeconds(1)))
							.then()
							.doOnTerminate(openConnections::decrementAndGet);
				})
				.bindNow();
```

If you were to keep your test as this you need to leave more time, i would suggest then the following code: 

```java
AtomicInteger openConnections = new AtomicInteger(100);

		DisposableServer server = HttpServer
				.create()
				.port(0)
				.handle((in, out) -> {

					try {
						Thread.sleep(500);
					} catch (InterruptedException e) {
						throw new RuntimeException(e);
					}

					return out
							.send(ByteBufFlux.fromString(Mono.just("test")))
							.then()
							.doOnTerminate(openConnections::decrementAndGet);
				})
				.bindNow();

		HttpClient httpClient = HttpClient
				.create()
				.addressSupplier(server::address);

		for (int i = 0; i < 100; i++) {
			httpClient
					.get()
					.response()
					.subscribe()
					.dispose();
		}

		while(openConnections.get() != 0) {
			Thread.sleep(1);
		}

		System.out.println("open connections: " + openConnections.get());
```

Closing for now but let us know if you detect something strange !

**Comment by timurstrekalov** [comment] 2018-11-28 11:52
Hi @smaldini, thanks for your reply. Sorry the example wasn't really correct. It's not easy to replicate what I've experienced here :)

Now, I'm quite sure the issue is there, although it's not easy to demonstrate it.

Cannot submit a viable example right now — I'm behind one of those super awesome corporate firewalls that restrict everything, so typing this from my phone.

The real-life test that I had involved using Undertow as the websocket server with statistics enabled. I would start a websocket connection, send and receive in `handle()`, give it 50ms to connect and then dispose immediately after.

With 10 connections, this would leave 2-3 not closed, as per Undertow stats. Now, I've also replicated this using the reactor-netty server, although I had to use JProfiler to see how many open sockets there were after disposal. Increasing the time between `subscribe()` and `dispose ()` to 500ms left no connections open.

Sorry, I'll try to come up with an example tonight if you can't reproduce it until then simply based on my rather convoluted account of the problem :)

**Comment by smaldini** [comment] 2018-11-30 20:07
We will investigate that might be a missing dispose during a state transition. Thanks for the details !

**Comment by violetagg** [comment] 2018-12-14 12:55
@timurstrekalov The example above is not quite correct.

You cannot rely on:
```
Thread.sleep(50); // increasing this makes it work
	
d.dispose();
```

It is more correct to say `When I receive the response then I'll dispose the connection`. So you should rewrite the code like this for example (I'm trying just to guess what you want to do):

```
Disposable d = client
	.websocket()
	.handle((in, out) -> {
		out
			.options(NettyPipeline.SendOptions::flushOnEach)
			.sendString(Mono.just("test"))
			.then()
			.subscribe();
		
		return in
			.aggregateFrames()
			.receive()
			.asString()
====>		        .doFinally(sig -> out.withConnection(c -> c.dispose()));
	})
	.subscribe();
```

**Comment by timurstrekalov** [comment] 2018-12-14 13:01
@violetagg what I actually want is this:

- open a connection, send a message
- keep receiving whatever messages I get from the server
- make sure the connection is closed when I call dispose()

**Comment by sleoniy** [comment] 2020-02-26 22:08
No updates? We are just going to leave sockets open?

**Comment by violetagg** [comment] 2020-02-28 08:20
@sleoniy what is your Reactor Netty version?

**Comment by violetagg** [comment] 2020-03-20 11:32
I'm closing this. If there is Reactor Netty issue we can reopen it.

**Closed by violetagg** 2020-03-20 11:32 UTC
Labels: status/invalid
