### ISSUE TITLE
Why is reactor netty 1.0.9 introduced and the reactor core version used is 3.1.16 instead of 3.4.8 in reactor netty core

### ISSUE THREAD

**Issue by 1ssqq1lxr** [reactor/reactor-netty#1762] opened 2021-08-02 13:50 UTC
Why is reactor netty 1.0.9 introduced and the reactor core version used is 3.1.16 instead of 3.4.8 in reactor netty core？

**Comment by violetagg** [comment] 2021-08-02 20:31
@1ssqq1lxr  Can you specify where you see version 3.1.16?
https://repo1.maven.org/maven2/io/projectreactor/netty/reactor-netty-core/1.0.9/reactor-netty-core-1.0.9.pom

**Comment by 1ssqq1lxr** [comment] 2021-08-03 02:37
In the spring environment, the dependent reactor netty version will change. What is the situation?

**Comment by 1ssqq1lxr** [comment] 2021-08-03 02:37
> In the spring environment, the dependent reactor netty version will change. What is the situation?

In the spring environment, the dependent reactor netty version will change. What is the situation?

**Comment by 1ssqq1lxr** [comment] 2021-08-03 02:46
> @1ssqq1lxr Can you specify where you see version 3.1.16?
> https://repo1.maven.org/maven2/io/projectreactor/netty/reactor-netty-core/1.0.9/reactor-netty-core-1.0.9.pom
> https://github.com/reactor/reactor-netty/blob/v1.0.9/gradle.properties

![image](https://user-images.githubusercontent.com/19258331/127949524-ad86ad3a-454d-4e53-b582-0a5deaad5a1a.png)

**Comment by simonbasle** [comment] 2021-08-03 12:04
this doesn't seem logical. maybe an intellij cache issue? or Maven/Gradle issue? Spring Boot references the reactor-bom, but the BOM in which reactor-netty 1.0.9 was released is also correct:  https://repo1.maven.org/maven2/io/projectreactor/reactor-bom/2020.0.9/reactor-bom-2020.0.9.pom

are you sure you haven't configured / forced an old version of a reactive library that would bring this old reactor version transitively? if you're using Gradle, you could maybe analyze dependencies and see what points to that version?

**Comment by 1ssqq1lxr** [comment] 2021-08-06 09:19
> this doesn't seem logical. maybe an intellij cache issue? or Maven/Gradle issue? Spring Boot references the reactor-bom, but the BOM in which reactor-netty 1.0.9 was released is also correct: https://repo1.maven.org/maven2/io/projectreactor/reactor-bom/2020.0.9/reactor-bom-2020.0.9.pom
> 
> are you sure you haven't configured / forced an old version of a reactive library that would bring this old reactor version transitively? if you're using Gradle, you could maybe analyze dependencies and see what points to that version?

I rely on the parent dependency of springboot, and the version of reactor used changes with the version of springboot

**Comment by simonbasle** [comment] 2021-08-09 10:03
> I rely on the parent dependency of springboot, and the version of reactor used changes with the version of springboot

But which version of Spring Boot are you using? You need to perform a fuller dependency analysis, but I'm pretty sure the issue isn't on reactor-netty/reactor-core/reactor-bom side given the above.

**Comment by violetagg** [comment] 2021-08-10 08:35
@1ssqq1lxr I generated a new Spring Boot application (v2.5.3) via start.spring.io. The dependencies seem to be OK - Netty is 4.1.66.Final and Reactor Core is 3.4.8

![Screenshot 2021-08-10 at 11 26 52](https://user-images.githubusercontent.com/696661/128834564-fc148c0e-d99b-41fa-ae39-7fc9bf23767f.png)


Then I created a simple maven project with the pom.xml below and the dependencies seem OK again

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>org.example</groupId>
	<artifactId>test</artifactId>
	<version>1.0-SNAPSHOT</version>

	<properties>
		<maven.compiler.source>11</maven.compiler.source>
		<maven.compiler.target>11</maven.compiler.target>
	</properties>

	<dependencies>
		<dependency>
			<groupId>io.projectreactor.netty</groupId>
			<artifactId>reactor-netty-http</artifactId>
			<version>1.0.9</version>
		</dependency>
	</dependencies>
</project>
```

If I use dependency management then again the dependencies seem OK

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>org.example</groupId>
	<artifactId>test</artifactId>
	<version>1.0-SNAPSHOT</version>

	<properties>
		<maven.compiler.source>11</maven.compiler.source>
		<maven.compiler.target>11</maven.compiler.target>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>io.projectreactor</groupId>
				<artifactId>reactor-bom</artifactId>
				<version>2020.0.9</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<dependency>
			<groupId>io.projectreactor.netty</groupId>
			<artifactId>reactor-netty-http</artifactId>
		</dependency>
	</dependencies>
</project>
```


Please try to provide a reproducible project.

**Comment by violetagg** [comment] 2021-08-13 08:03
@1ssqq1lxr  I'm closing this, we can reopen it if it appears Reactor Netty issue.

**Comment by 1ssqq1lxr** [comment] 2021-08-13 08:04
ok



---Original---
From: "Violeta ***@***.***&gt;
Date: Fri, Aug 13, 2021 16:03 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [reactor/reactor-netty] Why is reactor netty 1.0.9 introduced and the reactor core version used is 3.1.16 instead of 3.4.8 in reactor netty core (#1762)




 
@1ssqq1lxr  I'm closing this, we can reopen it if it appears Reactor Netty issue.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Closed by violetagg** 2021-08-13 08:03 UTC
Labels: type/bug, for/user-attention
