### ISSUE TITLE
reactor.netty.http.client.PrematureCloseException: Connection prematurely closed DURING response

### ISSUE THREAD

**Issue by fido016** [reactor/reactor-netty#2297] opened 2022-06-14 18:23 UTC
Getting this error on the following:

```
UriSpec<RequestBodySpec> uriSpec = client.method(httpMethod);
		
// Define the URL using the client above
log.info("runNewWayListingWebClient - Define the URL using the client");
RequestBodySpec bodySpec = uriSpec.uri(uri);
		
//Define the Body using the URI 
log.info("runNewWayListingWebClient - Define the Body ");
RequestHeadersSpec<?> headersSpec = null;;
				
if (this.getIncomingObject() instanceof ListingsSvcRqType)
		{
			log.info("runNewWayListingWebClient - Define the Body - ListingsSvcRqType.class");
		  headersSpec = bodySpec.body(
		  Mono.just(this.getIncomingObject()), ListingsSvcRqType.class);
		}
		else if(this.getIncomingObject() instanceof EwasDom)
		{
			log.info("runNewWayListingWebClient - Define the Body - EwasDom.class");
			headersSpec = bodySpec.body(
			  Mono.just(this.getIncomingObject()), EwasDom.class);
}
		
log.info("runNewWayListingWebClient - getContext");
SecurityContext context = getContext();
UserDetail userDetail = (UserDetail) context.getAuthentication().getPrincipal();

StringBuilder roleListBuffer = getRoleCodes(userDetail);

log.info("runNewWayListingWebClient -  headersSpec.header");
headersSpec.header(URLConstants.USER_NAME, userDetail.getUserName());
headersSpec.header(URLConstants.PASSWORD, userDetail.getPassword());
headersSpec.header(URLConstants.ROLE_LIST, roleListBuffer.toString());
		
log.info("runNewWayListingWebClient -  Set the FilterReq");
// Set the FilterReq
for (Map.Entry<String, String> entry : filterReq.entrySet()) {
	 			log.info(entry.getKey() + ":" + entry.getValue());
	 	        headersSpec.header(entry.getKey(), entry.getValue());
	    }
//Set additional attributes
	headersSpec.header(
			    HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON_VALUE)
			  .accept(MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML, MediaType.TEXT_PLAIN)
//			  .acceptCharset(StandardCharsets.UTF_8)
//			  .ifNoneMatch("*")
//////			  .ifModifiedSince(ZonedDateTime.now())
			  ;

//  Line below foobars ..   
ResponseEntity<String> entityMono = headersSpec.retrieve().toEntity(String.class).block();
```

```
Client Configuration
		int maxConnections = 500;
		ConnectionProvider connProvider = ConnectionProvider
				                                      .builder("webclient-conn-pool")
				                                      .maxConnections(maxConnections)
				                                      .maxIdleTime(Duration.ofMillis(DEFAULT_KEEP_ALIVE_TIME_MILLIS*6))
				                                      .maxLifeTime(Duration.ofMillis(DEFAULT_KEEP_ALIVE_TIME_MILLIS*6))
				                                      .pendingAcquireMaxCount(maxConnections * 2)
				                                      .pendingAcquireTimeout(Duration.ofMillis(DEFAULT_KEEP_ALIVE_TIME_MILLIS*6))
				                                      .build();	  
		// old 
		SSLContext sSlContext = SSLContext.getInstance("TLSv1.2");
	      sSlContext.init(null, null, null);
	      
	  		
	      // new 
	      Http11SslContextSpec http11SslContextSpec = Http11SslContextSpec.forClient(); 
	      
		HttpClient httpClient = HttpClient.create(connProvider)
	    		  .secure(spec -> spec.sslContext(http11SslContextSpec))
				  .wiretap("reactor.netty.http.client.HttpClient", // Logging -- Logger category
						    LogLevel.DEBUG, AdvancedByteBufFormat.TEXTUAL)	// Debugging ??
				  .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 5000)
				  .responseTimeout(Duration.ofMillis(5000))
				  .option(ChannelOption.SO_KEEPALIVE, true)
				  .doOnConnected(conn -> 
				    conn.addHandlerLast(new ReadTimeoutHandler(50000, TimeUnit.MILLISECONDS))
				      .addHandlerLast(new WriteTimeoutHandler(50000, TimeUnit.MILLISECONDS))
				      )
				  ;

				WebClient client = WebClient.builder()
						.clientConnector(new ReactorClientHttpConnector(httpClient))
						.build();  
				
				return client;
```

------------------------------------------
LOG
----------------------------------------

Log contents:

WARN  reactor.netty.channel.FluxReceive  - An exception has been observed post termination

```
2022-06-14 13:53:26 [reactor-http-nio-2] DEBUG r.n.http.client.HttpClientOperations - [9f6582cb-1, L:/127.0.0.1:5540 - R:localhost/127.0.0.1:8090] Received response (auto-read:false) : [Content-Type=text/plain;charset=ISO-8859-1, Date=Tue, 14 Jun 2022 17:53:26 GMT, content-length=3997]
2022-06-14 13:53:26 [reactor-http-nio-2] DEBUG r.n.r.DefaultPooledConnectionProvider - [9f6582cb-1, L:/127.0.0.1:5540 - R:localhost/127.0.0.1:8090] onStateChange(POST{uri=/aasrv/download/claim/info/filter, connection=PooledConnection{channel=[id: 0x9f6582cb, L:/127.0.0.1:5540 - R:localhost/127.0.0.1:8090]}}, [response_received])
2022-06-14 13:53:26 [reactor-http-nio-2] DEBUG reactor.netty.http.client.HttpClient - [9f6582cb-1, L:/127.0.0.1:5540 - R:localhost/127.0.0.1:8090] READ COMPLETE
2022-06-14 13:53:31 [reactor-http-nio-2] DEBUG reactor.netty.http.client.HttpClient - [9f6582cb-1, L:/127.0.0.1:5540 - R:localhost/127.0.0.1:8090] CLOSE
2022-06-14 13:53:31 [reactor-http-nio-2] DEBUG r.n.r.PooledConnectionProvider - [9f6582cb-1, L:/127.0.0.1:5540 ! R:localhost/127.0.0.1:8090] Channel closed, now: 0 active connections, 0 inactive connections and 0 pending acquire requests.
2022-06-14 13:53:31 [reactor-http-nio-2] DEBUG reactor.netty.ReactorNetty - [9f6582cb-1, L:/127.0.0.1:5540 ! R:localhost/127.0.0.1:8090] Non Removed handler: ReadTimeoutHandler, context: ChannelHandlerContext(ReadTimeoutHandler, [id: 0x9f6582cb, L:/127.0.0.1:5540 ! R:localhost/127.0.0.1:8090]), pipeline: DefaultChannelPipeline{(reactor.left.loggingHandler = reactor.netty.transport.logging.ReactorNettyLoggingHandler), (reactor.left.httpCodec = io.netty.handler.codec.http.HttpClientCodec), (reactor.left.responseTimeoutHandler = io.netty.handler.timeout.ReadTimeoutHandler), (ReadTimeoutHandler = io.netty.handler.timeout.ReadTimeoutHandler), (WriteTimeoutHandler = io.netty.handler.timeout.WriteTimeoutHandler), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
2022-06-14 13:53:31 [reactor-http-nio-2] DEBUG reactor.netty.ReactorNetty - [9f6582cb-1, L:/127.0.0.1:5540 ! R:localhost/127.0.0.1:8090] Non Removed handler: WriteTimeoutHandler, context: ChannelHandlerContext(WriteTimeoutHandler, [id: 0x9f6582cb, L:/127.0.0.1:5540 ! R:localhost/127.0.0.1:8090]), pipeline: DefaultChannelPipeline{(reactor.left.loggingHandler = reactor.netty.transport.logging.ReactorNettyLoggingHandler), (reactor.left.httpCodec = io.netty.handler.codec.http.HttpClientCodec), (reactor.left.responseTimeoutHandler = io.netty.handler.timeout.ReadTimeoutHandler), (ReadTimeoutHandler = io.netty.handler.timeout.ReadTimeoutHandler), (WriteTimeoutHandler = io.netty.handler.timeout.WriteTimeoutHandler), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
2022-06-14 13:53:31 [reactor-http-nio-2] DEBUG reactor.netty.ReactorNetty - [9f6582cb-1, L:/127.0.0.1:5540 ! R:localhost/127.0.0.1:8090] Non Removed handler: reactor.left.responseTimeoutHandler, context: ChannelHandlerContext(reactor.left.responseTimeoutHandler, [id: 0x9f6582cb, L:/127.0.0.1:5540 ! R:localhost/127.0.0.1:8090]), pipeline: DefaultChannelPipeline{(reactor.left.loggingHandler = reactor.netty.transport.logging.ReactorNettyLoggingHandler), (reactor.left.httpCodec = io.netty.handler.codec.http.HttpClientCodec), (reactor.left.responseTimeoutHandler = io.netty.handler.timeout.ReadTimeoutHandler), (ReadTimeoutHandler = io.netty.handler.timeout.ReadTimeoutHandler), (WriteTimeoutHandler = io.netty.handler.timeout.WriteTimeoutHandler), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
2022-06-14 13:53:31 [reactor-http-nio-2] DEBUG reactor.netty.http.client.HttpClient - [9f6582cb-1, L:/127.0.0.1:5540 ! R:localhost/127.0.0.1:8090] INACTIVE
2022-06-14 13:53:31 [reactor-http-nio-2] DEBUG r.n.r.DefaultPooledConnectionProvider - [9f6582cb-1, L:/127.0.0.1:5540 ! R:localhost/127.0.0.1:8090] onStateChange(POST{uri=/aasrv/download/claim/info/filter, connection=PooledConnection{channel=[id: 0x9f6582cb, L:/127.0.0.1:5540 ! R:localhost/127.0.0.1:8090]}}, [response_incomplete])
2022-06-14 13:53:31 [reactor-http-nio-2] WARN  reactor.netty.channel.FluxReceive - [9f6582cb-1, L:/127.0.0.1:5540 ! R:localhost/127.0.0.1:8090] An exception has been observed post termination
reactor.netty.http.client.PrematureCloseException: Connection prematurely closed DURING response
```

## Expected Behavior

The transaction should complete 

## Actual Behavior

The  transaction never completes ...  The endpoint gets called,  response returned partially .. 

 No Error caught .. incomplete response  .. 

## Steps to Reproduce
See above 

## Your Environment

* Reactor version(s) used:
  * user-agent: ReactorNetty/1.0.13

  * spring-boot-starter-webflux
     <version>2.6.1</version>

* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`java -version` -- 1.8):
* OS and version (Windows 10 Enterprise / Tomcat 9):

**Comment by violetagg** [comment] 2022-06-15 06:46
@fido016 I've edited your comment to improve the formatting. You might want to check out this [Mastering Markdown guide](https://guides.github.com/features/mastering-markdown/) for future reference.

**Comment by violetagg** [comment] 2022-06-15 06:54
@fido016 Can you provide a reproducible example?

**Comment by fido016** [comment] 2022-06-15 10:55
Thank you

Paul M. Cournoyer
Sr. Systems Analyst
Business Applications
MAPFRE Insurance
211 Main Street
Webster, MA 01570
Tel: 1-800-221-1605  Ext. 14829
C: NA
***@***.******@***.***>

Follow us on:
***@***.***<https://www.facebook.com/mapfreinsurance/>  ***@***.*** <https://www.instagram.com/mapfreinsurance/>    ***@***.*** <https://www.linkedin.com/company/mapfre/mycompany/>    ***@***.*** <https://twitter.com/mapfreins>   ***@***.*** <https://www.youtube.com/mapfreins>

***@***.***

At MAPFRE we develop our business in a way that respects the environment, please do not print this email unless absolutely necessary.

The contents of this message along with any attached files, especially any personal data contained therein, are confidential and intended exclusively for the named recipient. If you are not the named recipient and have received the message in error, or if you have become aware of its contents for whatever reason, please let us know by replying to this message and then destroying or deleting it. In any event, you must refrain from using, reproducing, altering, storing or forwarding this message and any attached files to a third party, or you will incur legal liability.

**Comment by fido016** [comment] 2022-06-15 11:18
Thank you for getting back to me ..   Unfortunately, it's an internal application.  The code provided resides on a local host Tomcat 9 server and does "real" database connections and the like .. 
 I guess my ask is,  how does Netty / WebClient determine how to close connections.   We are researching replacing our Rest Template with this technology.  Also, if possible, I would like to try to get more detailed way of understanding/logging the premature exception as well ...   I can see this post transaction hitting the end point, the end point getting the data and returning it back ..  However, the payload is truncated as the caller webclient attempts to process it .. I'm guessing that this is the premature end condition. 
Originally, the data returned was as a application content of JSON, then I changed the application content to string and noticed the same  ..

**Comment by fido016** [comment] 2022-06-15 11:31
Also, I tried to use the tcp client instead and noticed the same results ..  Any help or suggestions are much appreciated ..    Best ..  PC

**Comment by fido016** [comment] 2022-06-15 11:54
one more note,  originally,  I was using the Netty bundled with the following:
		<dependency>
   		 	<groupId>org.springframework.boot</groupId>
    		 <artifactId>spring-boot-starter-webflux</artifactId>
    		 <version>2.6.1</version>
		</dependency>

Is there any Merit to abandoning this and using Netty alone instead .. 
		<dependency>
   		 	<groupId>org.springframework.boot</groupId>
    		 <artifactId>spring-boot-starter-webflux</artifactId>
    		 <version>2.6.1</version>
		</dependency>

**Comment by violetagg** [comment] 2022-06-15 12:26
@fido016 Do you see the issue with the latest releases? I want to be sure that this not something that is fixed in Spring/Reactor projects.

**Comment by fido016** [comment] 2022-06-15 12:37
I am using 

<groupId>org.springframework.boot</groupId>
    		 <artifactId>spring-boot-starter-webflux</artifactId>
    		 <version>2.6.1</version>

which pulls in Netty and I'm using a http client as  the primary client ..

**Comment by violetagg** [comment] 2022-06-15 12:55
> I am using
> 
> org.springframework.boot spring-boot-starter-webflux 2.6.1
> 
> which pulls in Netty and I'm using a http client as the primary client ..

I meant that these are not the latest releases neither for Reactor Netty nor Spring Framework/Spring Boot

**Comment by fido016** [comment] 2022-06-15 12:57
oh,  thank you ..   Sorry about that ..  Which version would you recommend?

**Comment by violetagg** [comment] 2022-06-15 12:57
> oh, thank you .. Sorry about that .. Which version would you recommend?

https://github.com/reactor/reactor-netty/releases
https://github.com/spring-projects/spring-framework/releases
https://github.com/spring-projects/spring-boot/releases

**Comment by fido016** [comment] 2022-06-15 14:25
Thank you.  I will look at those links that you've provided ..  As a reference,  I am using the article below as a starting point ..  

https://www.baeldung.com/spring-5-webclient

**Comment by fido016** [comment] 2022-06-15 14:31
I have updated my pom to use the latest,  which brought in Netty 1.0.19 version .. 
### Pom change
<dependency>
   		 	<groupId>org.springframework.boot</groupId>
    		 <artifactId>spring-boot-starter-webflux</artifactId>
    		 <version>2.7.0</version>
		</dependency>
### Log
and I'm getting, 

2022-06-15 10:06:59 [reactor-http-nio-2] DEBUG i.n.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@1b14597e
2022-06-15 10:06:59 [reactor-http-nio-2] DEBUG r.netty.transport.TransportConfig - [88d3c0e9] Initialized pipeline DefaultChannelPipeline{(reactor.left.loggingHandler = reactor.netty.transport.logging.ReactorNettyLoggingHandler), (reactor.left.httpCodec = io.netty.handler.codec.http.HttpClientCodec), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
2022-06-15 10:06:59 [reactor-http-nio-2] DEBUG reactor.netty.http.client.HttpClient - [88d3c0e9] REGISTERED
2022-06-15 10:07:00 [reactor-http-nio-2] DEBUG r.netty.transport.TransportConnector - [88d3c0e9] Connecting to [localhost/127.0.0.1:8090].
2022-06-15 10:07:00 [reactor-http-nio-2] DEBUG reactor.netty.http.client.HttpClient - [88d3c0e9] CONNECT: localhost/127.0.0.1:8090
2022-06-15 10:07:00 [reactor-http-nio-2] DEBUG r.n.r.DefaultPooledConnectionProvider - [88d3c0e9, L:/127.0.0.1:22183 - R:localhost/127.0.0.1:8090] Registering pool release on close event for channel
2022-06-15 10:07:00 [reactor-http-nio-2] DEBUG r.n.r.PooledConnectionProvider - [88d3c0e9, L:/127.0.0.1:22183 - R:localhost/127.0.0.1:8090] Channel connected, now: 1 active connections, 0 inactive connections and 0 pending acquire requests.
2022-06-15 10:07:00 [reactor-http-nio-2] DEBUG reactor.netty.http.client.HttpClient - [88d3c0e9, L:/127.0.0.1:22183 - R:localhost/127.0.0.1:8090] ACTIVE
2022-06-15 10:07:00 [reactor-http-nio-2] DEBUG r.n.r.DefaultPooledConnectionProvider - [88d3c0e9, L:/127.0.0.1:22183 - R:localhost/127.0.0.1:8090] onStateChange(PooledConnection{channel=[id: 0x88d3c0e9, L:/127.0.0.1:22183 - R:localhost/127.0.0.1:8090]}, [connected])
2022-06-15 10:07:00 [reactor-http-nio-2] DEBUG r.n.r.DefaultPooledConnectionProvider - [88d3c0e9-1, L:/127.0.0.1:22183 - R:localhost/127.0.0.1:8090] onStateChange(GET{uri=/, connection=PooledConnection{channel=[id: 0x88d3c0e9, L:/127.0.0.1:22183 - R:localhost/127.0.0.1:8090]}}, [configured])
2022-06-15 10:07:00 [reactor-http-nio-2] DEBUG reactor.netty.ReactorNetty - [88d3c0e9-1, L:/127.0.0.1:22183 - R:localhost/127.0.0.1:8090] Added decoder [ReadTimeoutHandler] at the end of the user pipeline, full pipeline: [reactor.left.loggingHandler, reactor.left.httpCodec, ReadTimeoutHandler, reactor.right.reactiveBridge, DefaultChannelPipeline$TailContext#0]
2022-06-15 10:07:00 [reactor-http-nio-2] DEBUG reactor.netty.ReactorNetty - [88d3c0e9-1, L:/127.0.0.1:22183 - R:localhost/127.0.0.1:8090] Added decoder [WriteTimeoutHandler] at the end of the user pipeline, full pipeline: [reactor.left.loggingHandler, reactor.left.httpCodec, ReadTimeoutHandler, WriteTimeoutHandler, reactor.right.reactiveBridge, DefaultChannelPipeline$TailContext#0]
2022-06-15 10:07:00 [reactor-http-nio-2] DEBUG r.n.http.client.HttpClientConnect - [88d3c0e9-1, L:/127.0.0.1:22183 - R:localhost/127.0.0.1:8090] Handler is being applied: {uri=http://localhost:8090/aasrv/download/claim/info/filter, method=POST}
2022-06-15 10:07:00 [reactor-http-nio-2] DEBUG r.n.r.DefaultPooledConnectionProvider - [88d3c0e9-1, L:/127.0.0.1:22183 - R:localhost/127.0.0.1:8090] onStateChange(POST{uri=/aasrv/download/claim/info/filter, connection=PooledConnection{channel=[id: 0x88d3c0e9, L:/127.0.0.1:22183 - R:localhost/127.0.0.1:8090]}}, [request_prepared])
2022-06-15 10:07:00 [reactor-http-nio-2] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacityPerThread: 4096
2022-06-15 10:07:00 [reactor-http-nio-2] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.ratio: 8
2022-06-15 10:07:00 [reactor-http-nio-2] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.chunkSize: 32
2022-06-15 10:07:00 [reactor-http-nio-2] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.blocking: false
2022-06-15 10:07:00 [reactor-http-nio-2] DEBUG reactor.netty.http.client.HttpClient - [88d3c0e9-1, L:/127.0.0.1:22183 - R:localhost/127.0.0.1:8090] WRITE: 293B
2022-06-15 10:07:00 [reactor-http-nio-2] DEBUG reactor.netty.http.client.HttpClient - [88d3c0e9-1, L:/127.0.0.1:22183 - R:localhost/127.0.0.1:8090] FLUSH
2022-06-15 10:07:00 [reactor-http-nio-2] DEBUG reactor.netty.http.client.HttpClient - [88d3c0e9-1, L:/127.0.0.1:22183 - R:localhost/127.0.0.1:8090] WRITE: 178B
2022-06-15 10:07:00 [reactor-http-nio-2] DEBUG reactor.netty.http.client.HttpClient - [88d3c0e9-1, L:/127.0.0.1:22183 - R:localhost/127.0.0.1:8090] FLUSH
2022-06-15 10:07:00 [reactor-http-nio-2] DEBUG reactor.netty.http.client.HttpClient - [88d3c0e9-1, L:/127.0.0.1:22183 - R:localhost/127.0.0.1:8090] WRITE: 0B
2022-06-15 10:07:00 [reactor-http-nio-2] DEBUG reactor.netty.http.client.HttpClient - [88d3c0e9-1, L:/127.0.0.1:22183 - R:localhost/127.0.0.1:8090] FLUSH
2022-06-15 10:07:00 [reactor-http-nio-2] DEBUG r.n.r.DefaultPooledConnectionProvider - [88d3c0e9-1, L:/127.0.0.1:22183 - R:localhost/127.0.0.1:8090] onStateChange(POST{uri=/aasrv/download/claim/info/filter, connection=PooledConnection{channel=[id: 0x88d3c0e9, L:/127.0.0.1:22183 - R:localhost/127.0.0.1:8090]}}, [request_sent])
2022-06-15 10:07:00 [reactor-http-nio-2] DEBUG reactor.netty.ReactorNetty - [88d3c0e9-1, L:/127.0.0.1:22183 - R:localhost/127.0.0.1:8090] Added encoder [reactor.left.responseTimeoutHandler] at the beginning of the user pipeline, full pipeline: [reactor.left.loggingHandler, reactor.left.httpCodec, reactor.left.responseTimeoutHandler, ReadTimeoutHandler, WriteTimeoutHandler, reactor.right.reactiveBridge, DefaultChannelPipeline$TailContext#0]
2022-06-15 10:07:00 [reactor-http-nio-2] DEBUG reactor.netty.http.client.HttpClient - [88d3c0e9-1, L:/127.0.0.1:22183 - R:localhost/127.0.0.1:8090] READ: 2048B
2022-06-15 10:07:00 [reactor-http-nio-2] DEBUG r.n.http.client.HttpClientOperations - [88d3c0e9-1, L:/127.0.0.1:22183 - R:localhost/127.0.0.1:8090] Received response (auto-read:false) : [Content-Type=text/plain;charset=ISO-8859-1, Date=Wed, 15 Jun 2022 14:07:00 GMT, content-length=3993]
2022-06-15 10:07:00 [reactor-http-nio-2] DEBUG r.n.r.DefaultPooledConnectionProvider - [88d3c0e9-1, L:/127.0.0.1:22183 - R:localhost/127.0.0.1:8090] onStateChange(POST{uri=/aasrv/download/claim/info/filter, connection=PooledConnection{channel=[id: 0x88d3c0e9, L:/127.0.0.1:22183 - R:localhost/127.0.0.1:8090]}}, [response_received])
2022-06-15 10:07:00 [reactor-http-nio-2] DEBUG reactor.netty.http.client.HttpClient - [88d3c0e9-1, L:/127.0.0.1:22183 - R:localhost/127.0.0.1:8090] READ COMPLETE
2022-06-15 10:07:05 [reactor-http-nio-2] DEBUG reactor.netty.http.client.HttpClient - [88d3c0e9-1, L:/127.0.0.1:22183 - R:localhost/127.0.0.1:8090] CLOSE
2022-06-15 10:07:05 [reactor-http-nio-2] DEBUG r.n.r.PooledConnectionProvider - [88d3c0e9-1, L:/127.0.0.1:22183 ! R:localhost/127.0.0.1:8090] Channel closed, now: 0 active connections, 0 inactive connections and 0 pending acquire requests.
2022-06-15 10:07:05 [reactor-http-nio-2] DEBUG reactor.netty.ReactorNetty - [88d3c0e9-1, L:/127.0.0.1:22183 ! R:localhost/127.0.0.1:8090] Non Removed handler: ReadTimeoutHandler, context: ChannelHandlerContext(ReadTimeoutHandler, [id: 0x88d3c0e9, L:/127.0.0.1:22183 ! R:localhost/127.0.0.1:8090]), pipeline: DefaultChannelPipeline{(reactor.left.loggingHandler = reactor.netty.transport.logging.ReactorNettyLoggingHandler), (reactor.left.httpCodec = io.netty.handler.codec.http.HttpClientCodec), (reactor.left.responseTimeoutHandler = io.netty.handler.timeout.ReadTimeoutHandler), (ReadTimeoutHandler = io.netty.handler.timeout.ReadTimeoutHandler), (WriteTimeoutHandler = io.netty.handler.timeout.WriteTimeoutHandler), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
2022-06-15 10:07:05 [reactor-http-nio-2] DEBUG reactor.netty.ReactorNetty - [88d3c0e9-1, L:/127.0.0.1:22183 ! R:localhost/127.0.0.1:8090] Non Removed handler: WriteTimeoutHandler, context: ChannelHandlerContext(WriteTimeoutHandler, [id: 0x88d3c0e9, L:/127.0.0.1:22183 ! R:localhost/127.0.0.1:8090]), pipeline: DefaultChannelPipeline{(reactor.left.loggingHandler = reactor.netty.transport.logging.ReactorNettyLoggingHandler), (reactor.left.httpCodec = io.netty.handler.codec.http.HttpClientCodec), (reactor.left.responseTimeoutHandler = io.netty.handler.timeout.ReadTimeoutHandler), (ReadTimeoutHandler = io.netty.handler.timeout.ReadTimeoutHandler), (WriteTimeoutHandler = io.netty.handler.timeout.WriteTimeoutHandler), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
2022-06-15 10:07:05 [reactor-http-nio-2] DEBUG reactor.netty.ReactorNetty - [88d3c0e9-1, L:/127.0.0.1:22183 ! R:localhost/127.0.0.1:8090] Non Removed handler: reactor.left.responseTimeoutHandler, context: ChannelHandlerContext(reactor.left.responseTimeoutHandler, [id: 0x88d3c0e9, L:/127.0.0.1:22183 ! R:localhost/127.0.0.1:8090]), pipeline: DefaultChannelPipeline{(reactor.left.loggingHandler = reactor.netty.transport.logging.ReactorNettyLoggingHandler), (reactor.left.httpCodec = io.netty.handler.codec.http.HttpClientCodec), (reactor.left.responseTimeoutHandler = io.netty.handler.timeout.ReadTimeoutHandler), (ReadTimeoutHandler = io.netty.handler.timeout.ReadTimeoutHandler), (WriteTimeoutHandler = io.netty.handler.timeout.WriteTimeoutHandler), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
2022-06-15 10:07:05 [reactor-http-nio-2] DEBUG reactor.netty.http.client.HttpClient - [88d3c0e9-1, L:/127.0.0.1:22183 ! R:localhost/127.0.0.1:8090] INACTIVE
2022-06-15 10:07:05 [reactor-http-nio-2] DEBUG r.n.r.DefaultPooledConnectionProvider - [88d3c0e9-1, L:/127.0.0.1:22183 ! R:localhost/127.0.0.1:8090] onStateChange(POST{uri=/aasrv/download/claim/info/filter, connection=PooledConnection{channel=[id: 0x88d3c0e9, L:/127.0.0.1:22183 ! R:localhost/127.0.0.1:8090]}}, [response_incomplete])
2022-06-15 10:07:05 [reactor-http-nio-2] WARN  reactor.netty.channel.FluxReceive - [88d3c0e9-1, L:/127.0.0.1:22183 ! R:localhost/127.0.0.1:8090] An exception has been observed post termination
reactor.netty.http.client.PrematureCloseException: Connection prematurely closed DURING response
2022-06-15 10:07:05 [reactor-http-nio-2] DEBUG reactor.netty.http.client.HttpClient - [88d3c0e9-1, L:/127.0.0.1:22183 ! R:localhost/127.0.0.1:8090] UNREGISTERED

Unfortunately,  I still seem to be getting the error ..

**Comment by fido016** [comment] 2022-06-15 14:31
Thanks again for your help with this ..

**Comment by violetagg** [comment] 2022-06-24 12:01
@fido016

From this log I see the same that you described:
The headers are received but then while reading the response body the connection is closed.
If you use tcp dump can you see whether the server or the client closes the connection.

Also you mentioned:

> Also, I tried to use the tcp client instead and noticed the same results

So you are observing the same issue with another client? Is it possible that the issue is in the server?

**Comment by fido016** [comment] 2022-06-24 12:14
Hi Violeta-

Thanks for getting back to me ..

Your idea to check the versions of components suggested a new approach for me on this.

I abandoned the Spring starter approach and opted using the configuration listed below ..

We are tied to:
<org.springframework-version>5.1.0.RELEASE</org.springframework-version>

So, I ended up using the following configuration and things seem to be working.


<dependency>
    <groupId>io.projectreactor.netty</groupId>
    <artifactId>reactor-netty</artifactId>
    <version>1.0.20</version>
</dependency>


<dependency>
    <groupId>io.projectreactor</groupId>
    <artifactId>reactor-core</artifactId>
    <version>3.4.19</version>
</dependency>

This appears to be working!

Cheers!

PC

Paul M. Cournoyer
Sr. Systems Analyst
Business Applications
MAPFRE Insurance
211 Main Street
Webster, MA 01570
Tel: 1-800-221-1605  Ext. 14829
C: NA
***@***.******@***.***>

Follow us on:
***@***.***<https://www.facebook.com/mapfreinsurance/>  ***@***.*** <https://www.instagram.com/mapfreinsurance/>    ***@***.*** <https://www.linkedin.com/company/mapfre/mycompany/>    ***@***.*** <https://twitter.com/mapfreins>   ***@***.*** <https://www.youtube.com/mapfreins>

***@***.***

At MAPFRE we develop our business in a way that respects the environment, please do not print this email unless absolutely necessary.

The contents of this message along with any attached files, especially any personal data contained therein, are confidential and intended exclusively for the named recipient. If you are not the named recipient and have received the message in error, or if you have become aware of its contents for whatever reason, please let us know by replying to this message and then destroying or deleting it. In any event, you must refrain from using, reproducing, altering, storing or forwarding this message and any attached files to a third party, or you will incur legal liability.

**Comment by violetagg** [comment] 2022-06-24 12:20
@fido016

> This appears to be working!

So we can close this?
I mean Reactor Netty HttpClient is working as expected?

**Comment by violetagg** [comment] 2022-06-27 06:45
@fido016 I'm closing this. If needed we can reopen it.

**Closed by violetagg** 2022-06-27 06:45 UTC
Labels: type/bug, for/user-attention

**Comment by fido016** [comment] 2022-10-11 07:16
Yes, please close this.

Thanks again!

PC

Paul M. Cournoyer
Sr. Systems Analyst
Business Applications
MAPFRE Insurance
211 Main Street
Webster, MA 01570
Tel: 1-800-221-1605  Ext. 14829
C: NA
***@***.******@***.***>

Follow us on:
***@***.***<https://www.facebook.com/mapfreinsurance/>  ***@***.*** <https://www.instagram.com/mapfreinsurance/>    ***@***.*** <https://www.linkedin.com/company/mapfre/mycompany/>    ***@***.*** <https://twitter.com/mapfreins>   ***@***.*** <https://www.youtube.com/mapfreins>

***@***.***

At MAPFRE we develop our business in a way that respects the environment, please do not print this email unless absolutely necessary.

The contents of this message along with any attached files, especially any personal data contained therein, are confidential and intended exclusively for the named recipient. If you are not the named recipient and have received the message in error, or if you have become aware of its contents for whatever reason, please let us know by replying to this message and then destroying or deleting it. In any event, you must refrain from using, reproducing, altering, storing or forwarding this message and any attached files to a third party, or you will incur legal liability.
