### ISSUE TITLE
calling BlockingNettyContext.shutdown() does not clear handlers

### ISSUE THREAD

**Issue by bclozel** [reactor/reactor-netty#90] opened 2017-05-10 11:41 UTC
This issue is linked with spring-projects/spring-boot#9146
When trying to fix devtools support in Spring Boot (i.e. stopping the server, recreating a new Spring context and starting a new server - all that without stopping the JVM), I've found that disposing a server and starting a new one has not the expected behavior.

Here's a repro case that shows the behavior:

```java
package com.example.demo;

import org.assertj.core.api.Assertions;
import org.junit.Test;
import reactor.ipc.netty.http.client.HttpClient;
import reactor.ipc.netty.http.client.HttpClientResponse;
import reactor.ipc.netty.http.server.HttpServer;
import reactor.ipc.netty.tcp.BlockingNettyContext;

import org.springframework.http.ResponseEntity;
import org.springframework.web.client.RestTemplate;

public class ReactorNettyRestart {

	@Test
	public void testRestart() {
		// start a first server with a handler that answers HTTP 200 OK
		BlockingNettyContext context = HttpServer.create(8080)
				.start((req, resp) -> resp.status(200).send());

		HttpClientResponse response = HttpClient.create(8080).get("/").block();

		// checking the response status, OK
		Assertions.assertThat(response.status().code()).isEqualTo(200);
		// dispose the Netty context and wait for the channel close
		context.shutdown();
		context.getContext().onClose().block();

		// create a totally new server instance, with a different handler that answers HTTP 201
		context = HttpServer.create(8080)
				.start((req, resp) -> resp.status(201).send());

		response = HttpClient.create(8080).get("/").block();

		// fails, response status is 200 and debugging shows the the previous handler is called
		Assertions.assertThat(response.status().code()).isEqualTo(201);
		context.shutdown();
		context.getContext().onClose().block();
	}

	@Test
	public void testRestartBlockingClient() {

		RestTemplate template = new RestTemplate();
		// start a first server with a handler that answers HTTP 200 OK
		BlockingNettyContext context = HttpServer.create(8080)
				.start((req, resp) -> resp.status(200).send());

		ResponseEntity<String> response = template.getForEntity("http://localhost:8080/", String.class);

		// checking the response status, OK
		Assertions.assertThat(response.getStatusCode().value()).isEqualTo(200);
		// dispose the Netty context and wait for the channel close
		context.shutdown();
		context.getContext().onClose().block();

		// create a totally new server instance, with a different handler that answers HTTP 201
		context = HttpServer.create(8080)
				.start((req, resp) -> resp.status(201).send());

		response = template.getForEntity("http://localhost:8080/", String.class);

		// fails, response status is 200 and debugging shows the the previous handler is called
		Assertions.assertThat(response.getStatusCode().value()).isEqualTo(201);
		context.shutdown();
		context.getContext().onClose().block();
	}

}
```

Am I misusing the `HttpServer` API?
Is there some state that I forgot to clear?

**Comment by smaldini** [comment] 2017-06-02 23:19
The issue has more to do with the very currently limited lifecycle to be reworked.
Meanwhile, to fully reset the client pool, use HttpResources.reset().

**Comment by simonbasle** [comment] 2017-07-12 18:55
I have added global resource cleanup as part of the `BlockingNettyContext` `shutdown()` method (that comes after `start` or automatically on JVM shutdown when using `startAndAwait`). See #135
Wdyt @bclozel @smaldini could that be a good resolution?

**Comment by bclozel** [comment] 2017-07-18 14:25
I've updated the code sample in the original issue, and I can still reproduce the issue with the current 0.7.0 SNAPSHOT.
The new code sample shows that this can be reproduced as well with a `RestTemplate` client, backed by a basic JDK client (so nothing reactor related).

**Comment by sdeleuze** [comment] 2018-07-18 14:18
I faced the very same issue in Spring Fu (https://github.com/spring-projects/spring-fu/commit/6be8b90fbfff0cdfc9e89fdb4c63153e5c3866c6) and I think that's a rather annoying one (it keeps the port open after closing the server) that deserves to be fixed before Spring Framework 5.1 / Spring Boot 2.1 release IMO.

**Comment by smaldini** [comment] 2018-07-24 07:49
We should have the following fix in a next milestone/RC: 
when disposableServer.dispose() is called globalResource will be scanned for associated client connections and cleaned accordingly.

**Comment by sdeleuze** [comment] 2018-09-22 09:40
I reopen this issue, I still see it in Spring Fu. To reproduce clone https://github.com/spring-projects/spring-fu, remove `HttpResources.reset()` instances from https://github.com/spring-projects/spring-fu/blob/master/kofu/src/test/kotlin/org/springframework/boot/kofu/web/AbstractWebServerDslTests.kt, you will see test failures with client requesting the wrong server.

**Comment by violetagg** [comment] 2018-10-04 10:30
@sdeleuze Can you test PR #449

**Comment by sdeleuze** [comment] 2018-10-09 08:16
The issue still occurs with latest snapshot, you you want to debug that I have created a branch that reproduces the issue: https://github.com/spring-projects/spring-fu/tree/reactor-netty-http-resources. You can run for example `JacksonDslTests` it fails without `HttpResources.reset()` at the end of each test.

**Comment by sdeleuze** [comment] 2018-10-09 10:04
As noticed by @violetagg, `Californium-BUILD-SNAPSHOT` was not using Reactor Netty snapshots. Now that it is the case, I have been able to verify that the issue is fixed. Thanks.

**Closed by sdeleuze** 2018-10-09 10:04 UTC
Labels: bug
