### ISSUE TITLE
Data frame included in response for 204 No Content status

### ISSUE THREAD

**Issue by idikshit** [reactor/reactor-netty#2309] opened 2022-06-20 09:20 UTC
Hi,

While sending PATCH requests to our application for which a corresponding 204 No Content response is sent back. We see data frame included in response.

Dependencies
Spring Cloud Gateway - 3.0.7
Spring Boot - 2.6.6
Reactor netty - 1.0.16
Netty - 4.1.73.Final
OS - Cent OS / Linux

Expected behavior - Data frame should not be included in response from server.

PFA attached network trace and logs, the following filter can be used to filter packets. tcp.port==8081 && http2

[reactor-netty.zip](https://github.com/reactor/reactor-netty/files/8939297/reactor-netty.zip)

**Comment by idikshit** [comment] 2022-06-29 04:35
@violetagg Please find below attached snapshot for reference

<img width="960" alt="GOAWAY" src="https://user-images.githubusercontent.com/76950833/176352493-a7552e06-acfc-4c7a-b995-255e9b3b025c.PNG">

**Comment by pderop** [comment] 2022-06-29 16:53
Hi @idikshit ,

Could you attach your wireshark please ? I would like to see the flag from the _DATA[1]_ frame and also the size of _DATA[1]_.
It probably contains an _END_STREAM_ flag and its size is probably 0 ? in this case, it would just mean that _DATA[1]_ is the last frame which is considered to close the stream, no ?

Please attach your wireshark, so we can verify.
thank you.

**Comment by idikshit** [comment] 2022-06-30 08:49
Hi @pderop 
I have already attached wireshark capture, it is present in above attached zip file. Please check my previous comment. Thanks

**Comment by pderop** [comment] 2022-06-30 14:14
I'm sorry @idikshit, I missed the zip file.

Actually, we need a reproducible sample project to test with the gateway, can you provide it please ?

thanks

**Comment by pderop** [comment] 2022-07-13 15:03
@idikshit ,

Hi,

I'm having two issues with the demo:

first, I tried to build the demo, but I got an error:
```
- Spring Boot [2.6.6] is not compatible with this Spring Cloud release train

Action:

Consider applying the following actions:

- Change Spring Boot version to one of the following versions [2.4.x, 2.5.x] .

```


So, since you are using Reactor Netty 1.0.16, I changed the build.gradle in order to pull the RN 1.0.16 like this:
``
	id 'org.springframework.boot' version '2.5.10'
``


But now, I can't reproduce the problem because the incoming H2C client request is forwarded to the server using HTTP protocol, not H2C.

can you please check the demo ?
thanks

**Comment by idikshit** [comment] 2022-07-14 08:51
Hi @pderop 

PFA demo project with updated changes.

[demo.zip](https://github.com/reactor/reactor-netty/files/9110214/demo.zip)

**Comment by pderop** [comment] 2022-07-15 09:07
Hi @idikshit

This time the demo project forwards the request to the destination server using H2C, but I'm sorry I still can't reproduce.

Here is the test I did:

- I'm using an http2 server listening on 8090, so I just have changed your application.yaml with uri: http://127.0.0.1:8090
- I then did this curl command:

```
curl -v -X PATCH --http2-prior-knowledge http://localhost:8081/services/hello/patch
*   Trying 127.0.0.1:8081...
* Connected to localhost (127.0.0.1) port 8081 (#0)
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x13a810a00)
> PATCH /services/hello/patch HTTP/2
> Host: localhost:8081
> user-agent: curl/7.79.1
> accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 4294967295)!
< HTTP/2 204 
< 
* Connection #0 to host localhost left intact

```

Now, here is wireshark trace:

![pderop-wireshark-2](https://user-images.githubusercontent.com/650758/179190780-71ddc794-ec9e-4aea-bf4d-64941c24f9e3.png)

- so, we see from frame **73** that the GW forwards the request to localhost:8090. 
- then in frame **77**, the http2 destination server responds a 204 no content to the gateway 
- finally, in frame **79**, the GW forwards the response to curl, and in the HEADERS we see that the End Stream flag is set, and the HEADERS message is not followed by an empty DATA frame.


please double check the demo project ?
thanks.

**Comment by violetagg** [comment] 2022-07-29 08:07
@idikshit I'm closing this one. We can reopen it when you can provide reproducible example.

**Closed by violetagg** 2022-07-29 08:07 UTC
Labels: type/bug, for/user-attention
