### ISSUE TITLE
HTTPS proxy support

### ISSUE THREAD

**Issue by 90K2** [reactor/reactor-netty#1389] opened 2020-11-20 06:11 UTC
`reactor\netty\tcp\ProxyProvider.java` 

	public enum Proxy {
		HTTP, SOCKS4, SOCKS5
	}

Why would you not add HTTPS support for proxy ? 🙄

**Comment by violetagg** [comment] 2020-11-20 06:28
@90K2 Type `HTTP` is for both HTTP and HTTPS. What is the problem that you observe about HTTPS?

**Comment by violetagg** [comment] 2020-12-03 09:24
@90K2 I'm closing this, if you can provide more information, we can reopen it.

**Closed by violetagg** 2020-12-03 09:24 UTC
Labels: for/user-attention

**Comment by VasanthVarma** [comment] 2021-06-28 12:59
Getting this on trying to hit a https service using proxy - any leads @violetagg 
failure when writing TLS control frames; nested exception is javax.net.ssl.SSLException: failure when writing TLS control frames"

**Comment by xiguayizu** [comment] 2021-09-12 15:03
> @90K2我正在关闭这个，如果你能提供更多信息，我们可以重新打开它。

I also encountered this problem. How can I contact you? 
I give you my test account and password.


javax.net.ssl.SSLException: failure when writing TLS control frames
	at io.netty.handler.ssl.SslHandler.setHandshakeFailureTransportFailure(SslHandler.java:1870) [netty-handler-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.handler.ssl.SslHandler.access$600(SslHandler.java:167) [netty-handler-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.handler.ssl.SslHandler$2.operationComplete(SslHandler.java:985) [netty-handler-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.handler.ssl.SslHandler$2.operationComplete(SslHandler.java:980) [netty-handler-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) [netty-common-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552) [netty-common-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) [netty-common-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) [netty-common-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609) [netty-common-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) [netty-common-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.PendingWriteQueue.safeFail(PendingWriteQueue.java:279) [netty-transport-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.PendingWriteQueue.removeAndFailAll(PendingWriteQueue.java:177) [netty-transport-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.handler.proxy.ProxyHandler.failPendingWrites(ProxyHandler.java:435) [netty-handler-proxy-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.handler.proxy.ProxyHandler.failPendingWritesAndClose(ProxyHandler.java:352) [netty-handler-proxy-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.handler.proxy.ProxyHandler.setConnectFailure(ProxyHandler.java:347) [netty-handler-proxy-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.handler.proxy.ProxyHandler.channelRead(ProxyHandler.java:267) [netty-handler-proxy-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) [netty-transport-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-codec-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-codec-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [netty-transport-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.handler.proxy.HttpProxyHandler$HttpClientCodecWrapper.channelRead(HttpProxyHandler.java:272) [netty-handler-proxy-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.55.Final.jar:4.1.55.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_231]
Caused by: io.netty.handler.proxy.HttpProxyHandler$HttpProxyConnectException: http, basic, /52.28.250.157:40100 => api.ip.sb:443, status: 407 Proxy Authentication Required
	at io.netty.handler.proxy.HttpProxyHandler.handleResponse(HttpProxyHandler.java:200) ~[netty-handler-proxy-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.handler.proxy.ProxyHandler.channelRead(ProxyHandler.java:258) [netty-handler-proxy-4.1.55.Final.jar:4.1.55.Final]
	... 24 common frames omitted
