### ISSUE TITLE
Spring Boot WebClient ProxyConnectException

### ISSUE THREAD

**Issue by raananaka** [reactor/reactor-netty#2072] opened 2022-03-06 23:21 UTC
Hi all,

The problem is very simple, while using a proxy with restTemplate all working as expected, however, WebClient is refusing to get the required outcome.

**Exception Details:**
`Caused by: io.netty.handler.proxy.ProxyConnectException: http, basic, xxx.xxx.com/xx.x.xx.xx:2000 => xx.xx.com/<unresolved>:443, disconnected`

more.........

```
javax.net.ssl.SSLException: failure when writing TLS control frames
	at io.netty.handler.ssl.SslHandler.setHandshakeFailureTransportFailure(SslHandler.java:1844)
	at io.netty.handler.ssl.SslHandler.access$600(SslHandler.java:169)
	at io.netty.handler.ssl.SslHandler$2.operationComplete(SslHandler.java:951)
	at io.netty.handler.ssl.SslHandler$2.operationComplete(SslHandler.java:946)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.channel.PendingWriteQueue.safeFail(PendingWriteQueue.java:288)
	at io.netty.channel.PendingWriteQueue.removeAndFailAll(PendingWriteQueue.java:186)
	at io.netty.handler.proxy.ProxyHandler.failPendingWrites(ProxyHandler.java:435)
	at io.netty.handler.proxy.ProxyHandler.failPendingWritesAndClose(ProxyHandler.java:352)
	at io.netty.handler.proxy.ProxyHandler.setConnectFailure(ProxyHandler.java:347)
	at io.netty.handler.proxy.ProxyHandler.channelInactive(ProxyHandler.java:234)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:418)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354)
	at io.netty.handler.codec.http.HttpClientCodec$Decoder.channelInactive(HttpClientCodec.java:311)
	at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:221)
	at io.netty.handler.proxy.HttpProxyHandler$HttpClientCodecWrapper.channelInactive(HttpProxyHandler.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:831)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Code**
The code is tested with non proxy and working.
The proxy is using basic username and pass authentication. 

```
@Bean(name = "sslContext")
	public SslContext sslContext() {
		SslContext sslContext = null;
		try {

			sslContext = SslContextBuilder.forClient().protocols("SSLv3", "TLSv1", "TLSv1.1", "TLSv1.2")
					.trustManager(InsecureTrustManagerFactory.INSTANCE).build();

		} catch (SSLException e) {
			sslContext = null;
		}
		return sslContext;
	}

	@Bean(name = "httpClient")
	public HttpClient httpClient(SslContext sslContext) {
		
		Function<String, String> pwd = password -> globalAPIConfig.getApiProxyPassword();
		HttpClient client = null;

		if (globalAPIConfig.isApiProxyOn()) {

			client = HttpClient.create().secure(t -> t.sslContext(sslContext))
					.doOnConnected(conn -> conn
							.addHandler(new ReadTimeoutHandler(globalAPIConfig.getApiConnectTimeoutMillis(),
									TimeUnit.MILLISECONDS))
							.addHandler(new WriteTimeoutHandler(globalAPIConfig.getApiConnectTimeoutMillis())))
					.proxy(proxy -> proxy.type(ProxyProvider.Proxy.HTTP)
							.address(new InetSocketAddress(globalAPIConfig.getApiProxyProxyUrl(),
									globalAPIConfig.getApiProxyPort()))
							.username(globalAPIConfig.getApiProxyUsername()).password(pwd).nonProxyHosts("localhost"));
		} else {
			client = HttpClient.create()
					.doOnConnected(conn -> conn
							.addHandler(new ReadTimeoutHandler(globalAPIConfig.getApiConnectTimeoutMillis(),
									TimeUnit.MILLISECONDS))
							.addHandler(new WriteTimeoutHandler(globalAPIConfig.getApiConnectTimeoutMillis())));
		}

		client.option(ChannelOption.CONNECT_TIMEOUT_MILLIS, globalAPIConfig.getApiConnectTimeoutMillis());

		return client;
	}
```

Really appreciate your help...

**Comment by raananaka** [comment] 2022-03-07 02:55
OK, made some progress, changed the proxy url and using the IP address. it is working, however, getting a few SSL Handshake exception.

**Comment by raananaka** [comment] 2022-03-07 03:15
Changing to an IP address solved the issue, not sure if you guys can replicate the issue using a proxy.

**Comment by violetagg** [comment] 2022-03-07 19:13
@raananaka I've edited your comment to improve the formatting.

Can you provide us an example for `globalAPIConfig.getApiProxyProxyUrl()`?

**Comment by raananaka** [comment] 2022-03-07 23:57
Thank you for your help, 

**RestTemplate**

`@Bean
	RestTemplate restTemplate() {

		final String PROXY_USER = environment.getProperty("rest.api.proxy.username", String.class);
		final String PROXY_PASSWORD = environment.getProperty("rest.api.proxy.password", String.class);
		final String PROXY_HOST = environment.getProperty("rest.api.proxy.proxyUrl", String.class);
		final int PROXY_PORT = environment.getProperty("rest.api.proxy.port", Integer.class);
		final Boolean PROXY_ON = environment.getProperty("rest.api.proxy.on", Boolean.class);

		HttpClientBuilder clientBuilder = HttpClientBuilder.create();

		if (PROXY_ON) {
			CredentialsProvider credentialsProvider = new BasicCredentialsProvider();
			credentialsProvider.setCredentials(new AuthScope(PROXY_HOST, PROXY_PORT),
					new UsernamePasswordCredentials(PROXY_USER, PROXY_PASSWORD));

			clientBuilder.useSystemProperties();
			clientBuilder.setProxy(new HttpHost(PROXY_HOST, PROXY_PORT, AuthScope.ANY_REALM));
			clientBuilder.setDefaultCredentialsProvider(credentialsProvider);
			clientBuilder.setProxyAuthenticationStrategy(new ProxyAuthenticationStrategy());
		}

		clientBuilder.setUserAgent(
				"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.246");
		clientBuilder.disableCookieManagement();

		CloseableHttpClient client = clientBuilder.build();

		HttpComponentsClientHttpRequestFactory factory = new HttpComponentsClientHttpRequestFactory();
		factory.setConnectionRequestTimeout(50000);
		factory.setConnectTimeout(40000);
		factory.setReadTimeout(30000);
		factory.setHttpClient(client);

		RestTemplate template = new RestTemplate();
		template.setRequestFactory(factory);

		return template;
	}`

**Comment by violetagg** [comment] 2022-03-08 11:17
@raananaka Is it possible to provide a tcpdump from the communication with the proxy when you DO NOT use IP?

**Comment by raananaka** [comment] 2022-03-09 04:31
cpdump.pcapn
[tcpdump.pcapng.zip](https://github.com/reactor/reactor-netty/files/8211684/tcpdump.pcapng.zip)
g

**Comment by violetagg** [comment] 2022-03-10 13:14
> cpdump.pcapn [tcpdump.pcapng.zip](https://github.com/reactor/reactor-netty/files/8211684/tcpdump.pcapng.zip)
> 
> it is working today with host name, some issues as highlighted in the file

So this is a tcpdump from a working proxy?

**Comment by raananaka** [comment] 2022-03-10 22:06
yes it is

**Comment by violetagg** [comment] 2022-03-11 07:05
@raananaka It seems something related to your infrastructure ... Closing the issue.

**Closed by violetagg** 2022-03-11 07:05 UTC
Labels: for/user-attention

**Comment by GregoireW** [comment] 2022-07-21 19:00
Hello,

I just face this error but only when I compile with graalvm native image.   With standard hotspot it is ok.

Now it is a great question on how to fix this...

```
        HttpClient httpClient = HttpClient.create()
                .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 10 * 1000)
                .proxyWithSystemProperties()
                .doOnConnected(connection -> {
                    connection.addHandlerLast(new ReadTimeoutHandler(2 * 60 * 1000L, MILLISECONDS));
                    connection.addHandlerLast(new WriteTimeoutHandler(2 * 60 * 1000L, MILLISECONDS));
                });


         WebClient.builder()
                .clientConnector(new ReactorClientHttpConnector(httpClient))
                .build();
```

the error look like:

```
2022-07-21 15:28:54.784  WARN 1 --- [ctor-http-nio-2] r.netty.http.client.HttpClientConnect    : [124589ab, L:/1.2.3.4:34952 - R:proxy.corp.org/1.3.5.7:3128] The connection observed an error

javax.net.ssl.SSLException: failure when writing TLS control frames
	at io.netty.handler.ssl.SslHandler.setHandshakeFailureTransportFailure(SslHandler.java:1897) ~[na:na]
	at io.netty.handler.ssl.SslHandler.access$600(SslHandler.java:169) ~[na:na]
	at io.netty.handler.ssl.SslHandler$2.operationComplete(SslHandler.java:934) ~[na:na]
	at io.netty.handler.ssl.SslHandler$2.operationComplete(SslHandler.java:929) ~[na:na]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) ~[com.mycorp.myapp.MyApplication:4.1.79.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552) ~[com.mycorp.myapp.MyApplication:4.1.79.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) ~[com.mycorp.myapp.MyApplication:4.1.79.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) ~[com.mycorp.myapp.MyApplication:4.1.79.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609) ~[com.mycorp.myapp.MyApplication:4.1.79.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) ~[com.mycorp.myapp.MyApplication:4.1.79.Final]
	at io.netty.channel.PendingWriteQueue.safeFail(PendingWriteQueue.java:288) ~[na:na]
	at io.netty.channel.PendingWriteQueue.removeAndFailAll(PendingWriteQueue.java:186) ~[na:na]
	at io.netty.handler.proxy.ProxyHandler.failPendingWrites(ProxyHandler.java:434) ~[com.mycorp.myapp.MyApplication:4.1.79.Final]
	at io.netty.handler.proxy.ProxyHandler.failPendingWritesAndClose(ProxyHandler.java:351) ~[com.mycorp.myapp.MyApplication:4.1.79.Final]
	at io.netty.handler.proxy.ProxyHandler.setConnectFailure(ProxyHandler.java:346) ~[com.mycorp.myapp.MyApplication:4.1.79.Final]
	at io.netty.handler.proxy.ProxyHandler.access$100(ProxyHandler.java:38) ~[com.mycorp.myapp.MyApplication:4.1.79.Final]
	at io.netty.handler.proxy.ProxyHandler$2.run(ProxyHandler.java:198) ~[na:na]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[com.mycorp.myapp.MyApplication:4.1.79.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153) ~[com.mycorp.myapp.MyApplication:4.1.79.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[com.mycorp.myapp.MyApplication:4.1.79.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[com.mycorp.myapp.MyApplication:4.1.79.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[com.mycorp.myapp.MyApplication:4.1.79.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[na:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[na:na]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[na:na]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[na:na]
	at java.lang.Thread.run(Thread.java:833) ~[com.mycorp.myapp.MyApplication:na]
	at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704) ~[com.mycorp.myapp.MyApplication:na]
	at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202) ~[na:na]
Caused by: io.netty.handler.proxy.ProxyConnectException: http, none, proxy.corp.org/1.3.5.7:3128 => out.ext.com/<unresolved>:443, timeout
	... 13 common frames omitted

2022-07-21 15:28:54.785  WARN 1 --- [ctor-http-nio-2] r.netty.http.client.HttpClientConnect    : [124589ab, L:/1.2.3.4:34952 - R:proxy.corp.org/1.3.5.7:3128] The connection observed an error

io.netty.handler.proxy.ProxyConnectException: http, none, proxy.corp.org/1.3.5.7:3128 => out.ext.com/<unresolved>:443, timeout
	at io.netty.handler.proxy.ProxyHandler$2.run(ProxyHandler.java:198) ~[na:na]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[com.mycorp.myapp.MyApplication:4.1.79.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153) ~[com.mycorp.myapp.MyApplication:4.1.79.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[com.mycorp.myapp.MyApplication:4.1.79.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[com.mycorp.myapp.MyApplication:4.1.79.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[com.mycorp.myapp.MyApplication:4.1.79.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[na:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[na:na]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[na:na]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[na:na]
	at java.lang.Thread.run(Thread.java:833) ~[com.mycorp.myapp.MyApplication:na]
	at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704) ~[com.mycorp.myapp.MyApplication:na]
	at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202) ~[na:na]
```

**Comment by violetagg** [comment] 2022-07-21 19:17
@GregoireW Please check this https://projectreactor.io/docs/netty/release/reference/index.html#faq.proxy-connect-method

**Comment by GregoireW** [comment] 2022-07-22 08:56
FYI, I tried to do a minimal app to check this issue with native image.  It went OK.

With a quick diff on the pom, on my app I updated spring-native version from 0.12.0 to 0.12.1 and   native-buildtool from 0.9.12 to 0.9.13    and the issue is gone.

**Comment by eljoemed** [comment] 2023-06-20 17:29
Hi @GregoireW @violetagg  
I'm experiencing exactly the same issue as @GregoireW at diference that I'm mocking proxy with wiremock as a forward proxy. when I desable the proxy properties the call is working. Once I configure the proxy I get the same error than @GregoireW .
bellow my webclient config if someone can help. Thanks

```
WebClient.builder()
                        .baseUrl(properties.url())
                        .defaultHeader(CONTENT_TYPE, APPLICATION_JSON_VALUE)
                        .clientConnector(getConnector())
                        .filter(this::encryptPayload)
                        .filter(this::signAuthorizationHeader)
                        .build();
```
```
private ReactorClientHttpConnector getConnector() {
        return new ReactorClientHttpConnector(
                HttpClient.create()
                          .proxyWithSystemProperties()
                          .option(CONNECT_TIMEOUT_MILLIS, properties.timeout())
                          .responseTimeout(ofMillis(properties.timeout()))
                          .doOnConnected(conn -> conn.addHandlerLast(new ReadTimeoutHandler(properties.timeout(), MILLISECONDS))
                                                     .addHandlerLast(new WriteTimeoutHandler(properties.timeout(), MILLISECONDS)))
        );
    }
```

```
private void configureProxy() {
        if (StringUtils.isNotEmpty(properties.proxy())) {
            URI proxyURI = URI.create(properties.proxy());
            System.setProperty("http.proxyHost", proxyURI.getHost());
            System.setProperty("http.proxyPort", valueOf(proxyURI.getPort()));
        }
    }
```

**Comment by violetagg** [comment] 2023-06-20 18:01
@eljoemed Please open a new issue with the reproducible example.

**Comment by violetagg** [comment] 2023-06-21 10:14
#2838 was created for the comment above
