### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "io.netty.handler.codec.http.HttpRequest.headers()" because "nettyRequest" is null

### ISSUE THREAD

**Issue by jakshay21** [reactor/reactor-netty#2426] opened 2022-08-10 10:34 UTC
HttpRequest is a Nullable param in HttpServerOperations.

Invoking nettyRequest.headers() as part of the HttpServerOperations constructor resulting in NPE.

```
reactor-http-epoll-36              reactor.netty.transport.ServerTransport -- [56fa470a, L:/17.171.24.85:40004 ! R:/17.157.16.116:42506] onUncaughtException(SimpleConnection{channel=[id: 0x56fa470a, L:/17.171.24.85:40004 ! R:/17.157.16.116:42506]})
java.lang.NullPointerException: Cannot invoke "io.netty.handler.codec.http.HttpRequest.headers()" because "nettyRequest" is null
	at reactor.netty.http.server.HttpServerOperations.<init>(HttpServerOperations.java:166) ~[reactor-netty-http-1.0.17.jar!/:1.0.17]
	at reactor.netty.http.server.HttpServerOperations$FailedHttpServerRequest.<init>(HttpServerOperations.java:925) ~[reactor-netty-http-1.0.17.jar!/:1.0.17]
	at reactor.netty.http.server.HttpServerOperations.sendDecodingFailures(HttpServerOperations.java:769) ~[reactor-netty-http-1.0.17.jar!/:1.0.17]
	at reactor.netty.http.server.HttpTrafficHandler.sendDecodingFailures(HttpTrafficHandler.java:271) ~[reactor-netty-http-1.0.17.jar!/:1.0.17]
	at reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java:231) ~[reactor-netty-http-1.0.17.jar!/:1.0.17]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.75.Final.jar!/:4.1.75.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.75.Final.jar!/:4.1.75.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.75.Final.jar!/:4.1.75.Final]
	at reactor.netty.http.server.logging.AccessLogHandlerH1.channelRead(AccessLogHandlerH1.java:58) ~[reactor-netty-http-1.0.17.jar!/:1.0.17]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.75.Final.jar!/:4.1.75.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.75.Final.jar!/:4.1.75.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.75.Final.jar!/:4.1.75.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[netty-transport-4.1.75.Final.jar!/:4.1.75.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[netty-codec-4.1.75.Final.jar!/:4.1.75.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) ~[netty-codec-4.1.75.Final.jar!/:4.1.75.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[netty-transport-4.1.75.Final.jar!/:4.1.75.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.75.Final.jar!/:4.1.75.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.75.Final.jar!/:4.1.75.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.75.Final.jar!/:4.1.75.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.75.Final.jar!/:4.1.75.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.75.Final.jar!/:4.1.75.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.75.Final.jar!/:4.1.75.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.75.Final.jar!/:4.1.75.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[netty-transport-classes-epoll-4.1.75.Final.jar!/:4.1.75.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[netty-transport-classes-epoll-4.1.75.Final.jar!/:4.1.75.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-transport-classes-epoll-4.1.75.Final.jar!/:4.1.75.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-common-4.1.75.Final.jar!/:4.1.75.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.75.Final.jar!/:4.1.75.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.75.Final.jar!/:4.1.75.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

```

* Netty version - 1.0.17

**Comment by jakshay21** [comment] 2022-08-10 10:35
Similar concern was raised in the past around this

https://github.com/reactor/reactor-netty/issues/2068

**Comment by pderop** [comment] 2022-08-10 15:53
Hi @jakshay21 ,

Can you provide the NPE please ? do you also get the NPE using the latest 1.0.22 reactor-netty version ?
thank you.

**Comment by jakshay21** [comment] 2022-08-12 05:01
Hi @pderop,
Sorry forgot to attach the stack trace before. I've updated the description.

**Comment by pderop** [comment] 2022-08-12 08:25
Looking at the NPE, it's likely that the NPE is resolved since 1.0.18, see #2149, that's why I asked previously to try with the latest version (1.0.22).  See the [code change made in HttpServerOperations.java, in 1.0.18](https://github.com/reactor/reactor-netty/pull/2149/files#diff-537f1e33d6e1428b0fcac7e1fe10ba87e6cc7aadc6f240fdb73fbe3103baae74R756) from #2149.

so, can you test again with the latest version  ? else, please provide a reproducible example which we can build and test on the latest 1.0.22 version ?

thank you.

**Comment by violetagg** [comment] 2022-08-15 06:06
@jakshay21 I'm closing this, we can reopen it if the issue is observed with the latest released version.

**Closed by violetagg** 2022-08-15 06:06 UTC
Labels: type/bug, for/user-attention

**Comment by jakshay21** [comment] 2022-08-16 08:19
@violetagg @pderop 
Sorry I was away and missed the notifications around the recent comments. 

I'll bump up the version and retest, and will reopen if the issue resurfaces again.

Thank you.
