### ISSUE TITLE
Performance issue with WebClient under high load in WebFlux.

### ISSUE THREAD

**Issue by ssalamov** [reactor/reactor-netty#1960] opened 2021-12-27 16:37 UTC
Hello,

Hope you are doing well and can assist with this issue.

We have Spring WebFlux and reactor Netty collaborated system (both are latest versions) where WebClient is being used for rest APIs calls with different downstreams (We use ~20 different hosts for rest APIs). Trying to find issue with WebClient performance during high load. We are running isolated performance tests (instead real downstreams we use wiremock for mocking all responses, so no slow responses neither error probability means all calls receive responses within ~5ms). However issue is that once load is reaching > ~250K rpm, ~30K per instance usually one (sometimes 2 or 3) instances producing spikes with timeouts/exceptions in WebClient. See attached screenshots from new relic monitoring for once case/instance.

Putting here used WebClient configuration properties:

lineitems.netty.http.response.timeout=250 (global request read timeout, also for different api calls configured different values)
lineitems.netty.http.connect.timeout=500
lineitems.netty.http.pending.acquire.max.count=2000
lineitems.netty.http.pending.acquire.timeout=120000 (tested with different values still see such spikes)
lineitems.netty.http.concurrent.connection.max.count=50
lineitems.netty.http.client.max.idle.time=30000
lineitems.netty.http.client.max.life.time=30000

Here is the ClientHttpConnector bean configured like: 
```
 @Bean
    public ClientHttpConnector clientConnector() {
        ConnectionProvider connectionProvider = ConnectionProvider.builder("ClientHttpConnector")
                .metrics(isNettyHttpClientMetricsEnabled)
                .maxConnections(maxConcurrentConnectionCount)
                .maxIdleTime(Duration.ofMillis(maxIdleTimeInMilliseconds))
                .maxLifeTime(Duration.ofMillis(maxLifeTimeInMilliseconds))
                .pendingAcquireTimeout(Duration.ofMillis(pendingAcquireTimeoutInMillis))
                .pendingAcquireMaxCount(pendingAcquireMaxCount)
                .build();

        HttpClient httpClient = HttpClient.create(connectionProvider)
                .metrics(isNettyHttpClientMetricsEnabled, WebClientConfiguration::getTag)
                .keepAlive(true)
                .doOnError((req, t) -> log.warn("doOnError - error {} ", req.fullPath(), t), (res, t) -> log.warn("HttpClient error on response: ", t))
                .doOnRequestError(this::logOnRequestError)
                .doOnResponseError(this::logOnResponseError)
                .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, connectTimeoutInMillis)
                .doAfterRequest(this::applyRequestLevelTimeoutPerProvider)
                .followRedirect(true);

        return new ReactorClientHttpConnector(httpClient);
    }
```

Here is one of the WebClient usage in the system:

```
webClient
      .put()
      .uri(uriBuilder -> uriBuilder
              .scheme("https").host("products")
              .replacePath(path)
              .build())
      .bodyValue(request)
      .retrieve()
      .bodyToMono(responseType)
      .transformDeferred(requestResilience::apply)
      .transformDeferred(CircuitBreakerOperator.of(circuitBreaker))
      .retryWhen(RETRY_WHEN_TIMEOUT)
      .onErrorMap(ProductCommunicationException::new)
      .contextWrite(context -> context.put(PROVIDER_HOST_LABEL, HOST))
```

<img width="700" alt="memory consumption" src="https://user-images.githubusercontent.com/39103746/147490191-4c12b7d8-1a68-4cfa-9fdf-dafef820ca3c.png">
<img width="1637" alt="netty http client and conneciton provider metrics" src="https://user-images.githubusercontent.com/39103746/147490195-47f30c8b-b936-4850-98a8-6eaab6cec63a.png">
<img width="699" alt="GC cpou usage" src="https://user-images.githubusercontent.com/39103746/147490202-4179826f-62b1-4eb4-b27c-02814108273f.png">

I think WebClient should handle all downstreams'  mocked responses gracefully.
However it doesn't and produces spike errors in single instance (usually). Timeouts and PrematureCloseException. 

Hope you can guide me correct usage/tuning of WebClient with many downstream calls under high load. If you need further details let me know.

Regards,
Samir Salamov

**Comment by OlegDokuka** [comment] 2021-12-27 17:23
Hi @ssalamov! 
From your graphs, it seems that there is a significant number of threads blocked somewhere. 
Can it be a root cause? 
Also, can you share your benchmarks, which reproduce the problem? I am eager to see your full setup.

Thanks,
Oleh

**Comment by ssalamov** [comment] 2021-12-27 17:40
Hi, @OlegDokuka. Provide such reproducible solution will take some time. So not sure when i can do it. Additional information about system is we use blocking aws sdk (dynamodbv2) for Dynamo db, however we subscribe all our calls with `.subscribeOn(Schedulers.boundedElastic());`. Can it be reason why `Aws Sdk blocked threads` metric (refer screenshot) shows such data?

1. Single web request scenario: fetch/create db data -> decorate data received from downstreams -> update data in db.
2. We do have also async processing over amazon sqs listeners which following the same flow as web request.

**Comment by OlegDokuka** [comment] 2021-12-27 18:08
@ssalamov.

> Provide such reproducible solution will take some time. So not sure when i can do it.

I believe we can nothing to do without a proper example. What you show should not cause any trouble so far.

> Additional information about system is we use blocking aws sdk (dynamodbv2) for Dynamo db, however we subscribe all our calls with .subscribeOn(Schedulers.boundedElastic());. Can it be reason why Aws Sdk blocked threads metric (refer screenshot) shows such data?

Well, this can be a root cause. Threads tend to add uncertainty. Also, I'm not sure that 1.6k threads can be created by `boundedElastic` scheduler. The math behind it is simple and is `availableCpu` * 10 ( see https://github.com/reactor/reactor-core/blob/main/reactor-core/src/main/java/reactor/core/scheduler/Schedulers.java#L93). Thus, the problem is likely in the different place.

From GC pressure - it seems you do generate a ton of objects. Not sure they are from webclient. We have to have a full picture to figure out the problem. Maybe memory dump can add more clarity

**Comment by ssalamov** [comment] 2021-12-27 18:36
@OlegDokuka I can provide memory dump - once have it will attach.

**Comment by ssalamov** [comment] 2021-12-27 19:11
@OlegDokuka wanted to clarify your above comment about 1.6k threads. As we use xlarge instances in aws which is 16 cpu cores. So if 10 instances used during perf tests then it's matching 16 * 10 * 10 = 1.6K. It can be changed by instances count - auto scaling. I will try to use fixed thread pool instead elastic. Maybe instead availableCpu * 10 I can try with availableCpu * 5 = 80 in my case, not to block all threads. Will share results...

**Comment by OlegDokuka** [comment] 2021-12-27 19:29
> So if 10 instances used during perf tests then it's matching 16 * 10 * 10 = 1.6K.

Makes sense. I was thinking it is a single instance. You may try both - decrease and measure as well as increase and see if issue was resolved

**Comment by ssalamov** [comment] 2021-12-28 11:12
@OlegDokuka for now I share screenshot (I know it's nothing, but maybe it can lead us somewhere) from thread dump, but later if I allowed (for security purposes) will share thread and heap dump.  This time I tested with fixed thread pool (80 threads) in db repositories subscriptions.

<img width="1368" alt="Screenshot 2021-12-28 at 12 09 09" src="https://user-images.githubusercontent.com/39103746/147560276-6799cbac-bb0f-478f-8c9a-a4ac5cc80068.png">.

**Comment by violetagg** [comment] 2022-01-10 13:14
@ssalamov Please provide some reproducible example.

**Comment by ssalamov** [comment] 2022-01-10 19:32
Hello, @violetagg. Currently we are working to identify blocking parts in our system. We could fix some of them, but still there are some unknown stacktraces (block hound exceptions) which hard to identify where root cause can be. Where it's possible we do fixing blocking parts, where is not we schedule operation with boundedElastic() to avoid blocking operation in event loop. Sharing here some of the unknown stacktraces which maybe you can recognise:

1.
```
java.lang.Error: jdk.internal.misc.Unsafe#park
	at com.ocado.lineitems.Application.lambda$main$0(Application.java:28)
	at reactor.blockhound.BlockHound$Builder.lambda$install$6(BlockHound.java:318)
	at reactor.blockhound.BlockHoundRuntime.checkBlocking(BlockHoundRuntime.java:46)
	at java.base/jdk.internal.misc.Unsafe.park(Unsafe.java)
	at java.base/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:917)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1240)
	at java.base/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:267)
	at java.base/java.util.concurrent.PriorityBlockingQueue.remove(PriorityBlockingQueue.java:658)
	at reactor.core.scheduler.BoundedElasticScheduler$BoundedServices.setIdle(BoundedElasticScheduler.java:426)
	at reactor.core.scheduler.BoundedElasticScheduler$BoundedState.release(BoundedElasticScheduler.java:539)
	at reactor.core.scheduler.BoundedElasticScheduler$BoundedState.dispose(BoundedElasticScheduler.java:564)
	at reactor.core.Disposables$ListCompositeDisposable.dispose(Disposables.java:268)
	at reactor.core.Disposables$ListCompositeDisposable.dispose(Disposables.java:161)
	at reactor.core.scheduler.ExecutorServiceWorker.dispose(ExecutorServiceWorker.java:72)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.cancel(FluxPublishOn.java:278)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.cancel(FluxHide.java:157)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.cancel(FluxOnAssembly.java:654)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.cancel(FluxOnAssembly.java:654)
	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.cancel(FluxFlattenIterable.java:283)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.cancel(FluxHide.java:157)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.cancel(FluxOnAssembly.java:654)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.cancel(FluxOnAssembly.java:654)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:839)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:608)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:588)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onError(FluxFlatMap.java:451)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:544)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:544)
	at com.ocado.lineitems.config.logging.MdcContextLifter.onError(MdcContextConfiguration.java:60)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onError(FluxHide.java:142)
	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drainAsync(FluxFlattenIterable.java:321)
	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drain(FluxFlattenIterable.java:686)
	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.onError(FluxFlattenIterable.java:257)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:544)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:544)
	at com.ocado.lineitems.config.logging.MdcContextLifter.onError(MdcContextConfiguration.java:60)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onError(FluxHide.java:142)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.doError(FluxPublishOn.java:511)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.checkTerminated(FluxPublishOn.java:549)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:432)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:527)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
--------------------------------------------------------------------------------------------------------------------
2.
```
java.lang.Error: jdk.internal.misc.Unsafe#park
	at com.ocado.lineitems.Application.lambda$main$0(Application.java:28)
	at reactor.blockhound.BlockHound$Builder.lambda$install$6(BlockHound.java:318)
	at reactor.blockhound.BlockHoundRuntime.checkBlocking(BlockHoundRuntime.java:46)
	at java.base/jdk.internal.misc.Unsafe.park(Unsafe.java)
	at java.base/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:917)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1240)
	at java.base/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:267)
	at java.base/java.util.concurrent.PriorityBlockingQueue.offer(PriorityBlockingQueue.java:478)
	at java.base/java.util.concurrent.PriorityBlockingQueue.add(PriorityBlockingQueue.java:460)
	at reactor.core.scheduler.BoundedElasticScheduler$BoundedServices.pick(BoundedElasticScheduler.java:405)
	at reactor.core.scheduler.BoundedElasticScheduler.schedule(BoundedElasticScheduler.java:208)
	at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.trySchedule(MonoPublishOn.java:146)
	at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.onNext(MonoPublishOn.java:120)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:539)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:539)
	at com.ocado.lineitems.config.logging.MdcContextLifter.onNext(MdcContextConfiguration.java:54)
	at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.onNext(MonoSubscribeOn.java:146)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:539)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:539)
	at com.ocado.lineitems.config.logging.MdcContextLifter.onNext(MdcContextConfiguration.java:54)
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onNext(FluxTimeout.java:180)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:539)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:539)
	at com.ocado.lineitems.config.logging.MdcContextLifter.onNext(MdcContextConfiguration.java:54)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:539)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:539)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:539)
	at com.ocado.lineitems.config.logging.MdcContextLifter.onNext(MdcContextConfiguration.java:54)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:539)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:539)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:539)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:539)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:539)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:539)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:539)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:539)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:539)
	at com.ocado.lineitems.config.logging.MdcContextLifter.onNext(MdcContextConfiguration.java:54)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:539)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:539)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:539)
	at com.ocado.lineitems.config.logging.MdcContextLifter.onNext(MdcContextConfiguration.java:54)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:539)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:539)
	at com.ocado.lineitems.config.logging.MdcContextLifter.onNext(MdcContextConfiguration.java:54)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onNext(FluxFilterFuseable.java:118)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:539)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:539)
	at com.ocado.lineitems.config.logging.MdcContextLifter.onNext(MdcContextConfiguration.java:54)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
	at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:159)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onComplete(FluxOnAssembly.java:549)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onComplete(FluxOnAssembly.java:549)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onComplete(FluxOnAssembly.java:549)
	at com.ocado.lineitems.config.logging.MdcContextLifter.onComplete(MdcContextConfiguration.java:65)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onComplete(FluxHide.java:147)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:150)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onComplete(FluxOnAssembly.java:549)
	at com.ocado.lineitems.config.logging.MdcContextLifter.onComplete(MdcContextConfiguration.java:65)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onComplete(FluxHide.java:147)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onComplete(FluxPeekFuseable.java:277)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onComplete(FluxOnAssembly.java:549)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onComplete(FluxOnAssembly.java:549)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onComplete(FluxOnAssembly.java:549)
	at com.ocado.lineitems.config.logging.MdcContextLifter.onComplete(MdcContextConfiguration.java:65)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onComplete(FluxHide.java:147)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:150)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onComplete(FluxOnAssembly.java:549)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onComplete(FluxOnAssembly.java:549)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:400)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:419)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:473)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:702)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at reactor.netty.http.client.AbstractHttpClientMetricsHandler.channelRead(AbstractHttpClientMetricsHandler.java:115)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at reactor.netty.channel.AbstractChannelMetricsHandler.channelRead(AbstractChannelMetricsHandler.java:74)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1371)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1234)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1283)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

3.

```
java.lang.Error: jdk.internal.misc.Unsafe#park
	at com.ocado.lineitems.Application.lambda$main$0(Application.java:28)
	at reactor.blockhound.BlockHound$Builder.lambda$install$6(BlockHound.java:318)
	at reactor.blockhound.BlockHoundRuntime.checkBlocking(BlockHoundRuntime.java:46)
	at java.base/jdk.internal.misc.Unsafe.park(Unsafe.java)
	at java.base/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:917)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1240)
	at java.base/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:267)
	at java.base/java.util.concurrent.PriorityBlockingQueue.remove(PriorityBlockingQueue.java:658)
	at reactor.core.scheduler.BoundedElasticScheduler$BoundedServices.setIdle(BoundedElasticScheduler.java:426)
	at reactor.core.scheduler.BoundedElasticScheduler$BoundedState.release(BoundedElasticScheduler.java:539)
	at reactor.core.scheduler.BoundedElasticScheduler$BoundedState.dispose(BoundedElasticScheduler.java:564)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:84)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

So having such blocking parts in flows actually can cause stalling system. So first we would like to get rid of blocking parts as much as possible and then test system again. Code base is too big and hard to highlight specific code snippets which can cause this issue even not knowing what is that.

**Comment by ssalamov** [comment] 2022-01-11 10:17
I guess above two exceptions coming from bounded elastic scheduler, so can we whitelist/ignore them? Or I miss something? Another one is happening inside EpollEventLoop which imo should be fixed. But we don't know where blocking code.

**Comment by OlegDokuka** [comment] 2022-01-25 14:16
Hi @ssalamov!

For not it seems that the issues are on the application side rather than on the reactor-netty side. Thus I'm closing this ticket. Feel free to reopen it once you have an example which reproduces/shows the problem

Best,
Oleh

**Closed by OlegDokuka** 2022-01-25 14:16 UTC
Labels: status/need-investigation, for/user-attention, area/perf

**Comment by mateusz-nalepa** [comment] 2025-02-08 11:20
Hello!

Imo it looks like, that problem you encountered @ssalamov is exactly the same, like this issue https://github.com/spring-projects/spring-framework/issues/34199

cc @OlegDokuka @violetagg
