### ISSUE TITLE
Using reactor-netty:0.9.4 memory leak happening with PooledConnectionProvider size increasing over period of time

### ISSUE THREAD

**Issue by skmedishetty** [reactor/reactor-netty#1003] opened 2020-02-18 22:07 UTC
Team,

We are facing memory leak issue and noticed pool connection provider increases as time goes on.
We are using cloudfoundry-client-reactor which requires reactor-netty.

PooledConnectionProvider {name=cloudfoundry-client, poolFactory=reactor.netty.resources.ConnectionProvider$$Lambda$52/34419690@a7d7100} 
size = 383

Could you please help me to resolve the issue.

**Comment by violetagg** [comment] 2020-02-19 05:45
@skmedishetty Can you provide more details? How do you configure CF Java Client? Can you test with 0.9.5.BUILD-SNAPSHOT?

**Comment by skmedishetty** [comment] 2020-02-19 14:38
@violetagg  I cannot use snapshot build the issue is happening, we are not allowed to use snapshots.
More error details below issue
https://github.com/cloudfoundry/cf-java-client/issues/1035

The code is below as mentioned in the document.
https://github.com/cloudfoundry/cf-java-client

 @Bean
    @ConditionalOnBean(PropertySourcesPlaceholderConfigurer.class)
    public PasswordGrantTokenProvider tokenProvider() {

        return PasswordGrantTokenProvider.builder()
            .password(applicationDetails().getPassword())
            .username(applicationDetails().getUserId())
            .build();
    }

    @Bean
	public ReactorCloudFoundryClient cloudFoundryClient(ConnectionContext connectionContext, TokenProvider tokenProvider) {
        return ReactorCloudFoundryClient.builder()
            .connectionContext(connectionContext)
            .tokenProvider(tokenProvider)
            .build();
    }

**Comment by violetagg** [comment] 2020-02-19 16:05
@skmedishetty then I'll need some reproducible example. 
@twoseat can you help with this?

**Comment by skmedishetty** [comment] 2020-02-19 16:21
@violetagg @twoseat I need your help.. we are using this for high critical application which requires resilience.. to scale up/down in case of issues.

**Comment by violetagg** [comment] 2020-02-20 05:28
it might be related to this fix https://github.com/reactor/reactor-netty/commit/643c6725486ee8e95b7e805ab8d4178feacf2b8c

**Comment by skmedishetty** [comment] 2020-02-20 16:48
@violetagg  when are you releasing 0.9.5 the one which has fix ?

**Comment by violetagg** [comment] 2020-02-20 16:50
@skmedishetty The plan is Monday 24.02

**Comment by skmedishetty** [comment] 2020-02-20 17:30
@violetagg  what are the packages you suggest enable  debug for troubleshoot.

**Comment by violetagg** [comment] 2020-02-20 17:34
@skmedishetty depends what you want to debug

**Comment by skmedishetty** [comment] 2020-02-20 18:13
@violetagg  ok
Also how to handle this kind of exception Suppressed: reactor.core.publisher.FluxOnAssembly$AssemblySnapshotException: null
Its eating actual exception and unable to find it.

**Comment by violetagg** [comment] 2020-02-20 19:16
@skmedishetty `reactor-core-3.0.7.RELEASE.jar` is pretty old and is not supported anymore

**Comment by skmedishetty** [comment] 2020-02-20 20:56
@violetagg  yeah in newer version also how can we handle suppressed exceptions. I observed this in 3.3.0 too

**Comment by violetagg** [comment] 2020-02-21 05:46
@skmedishetty Let's keep the discussion here to the memory leak issue. For any further questions on how to debug etc. I would prefer to use [Gitter](https://gitter.im/reactor/reactor).

**Comment by violetagg** [comment] 2020-02-21 05:52
Closing as a duplicate of #988

**Closed by violetagg** 2020-02-21 05:52 UTC
Labels: status/duplicate, type/bug
