### ISSUE TITLE
A really large header should not result in a client PrematureCloseException

### ISSUE THREAD

**Issue by crankydillo** [reactor/reactor-netty#1584] opened 2021-04-05 17:35 UTC
If the header value is longer than the configured maximum header length and not 'extremely' long, then the customer gets a 413.  However, if the header value is 'extremely' long, the user experiences a severed connection while sending the request.

## Expected Behavior

Within reason, all 'too long' header values should result in a 413 Response.

## Actual Behavior

When the header is really long, the code will sever the connection before it finishes reading the request.

## Steps to Reproduce

```
	@ParameterizedTest
	@ValueSource(ints = {1_000, 1_000_000})
	void testHeaderTooLong(final int headerSize) {
		final String path = "/";
		final DisposableServer server = HttpServer.create()
				.port(0)
				.httpRequestDecoder(c -> c.maxHeaderSize(100))
				.route(routes ->
					routes.get(path, (req, resp) -> resp.sendString(Mono.just("oh nos!")))
				).bindNow();

		final String headerVal =
				IntStream
						.range(0, headerSize)
						.mapToObj(i -> "a")
						.collect(Collectors.joining());

		final HttpClient client = createClient(server.port());

		final int status = client.headers(hs -> hs.add("longheader", headerVal))
				.get()
				.uri(path)
				.response()
				.map(resp -> resp.status().code())
				.block();

		assertThat(status).isEqualTo(413);
		server.disposeNow();
	}
```

## Possible Solution

I will follow this up with a link to a branch that has the failing test and a 'feels hackish' fix.  I'm pretty certain you'll want to go another route:)

Minimally, I'm guessing [this code](https://github.com/reactor/reactor-netty/blob/d21d5146258ae5966deb16b9ecbf19d2920153eb/reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java#L672) will need to change.

## Your Environment

mac laptop, many environments

* Reactor version(s) used: 1.0.5, master
* Other relevant libraries versions (eg. `netty`, ...): 
* JVM version (`java -version`): several..
* OS and version (eg. `uname -a`): several..

**Comment by violetagg** [comment] 2021-04-05 17:54
@crankydillo

https://github.com/reactor/reactor-netty/blob/d21d5146258ae5966deb16b9ecbf19d2920153eb/reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java#L672

Yes this can be removed as `Connection: close` is set already. When you remove this, do you still see the issue?

**Comment by crankydillo** [comment] 2021-04-05 19:06
I removed it and added some other things to turn my test scenario green.  Maybe those other things weren't necessary.   I will double check and let you know.

**Comment by crankydillo** [comment] 2021-04-05 19:37
[This draft PR](https://github.com/reactor/reactor-netty/pull/1586) shows what I did to get the test to pass.

**Comment by crankydillo** [comment] 2021-04-05 19:48
I must admit that I didn't run all the tests:(  It looks like this change breaks some of them.  I'm glad I opened this as a draft!  Anyhow, take what you want.  If you don't have time to work on it, let me know.  I'm slowly getting an understanding of the code.

**Comment by violetagg** [comment] 2021-07-28 18:42
@crankydillo I'm looking at this one, but I can receive something similar (not your test) only with Adopt Jdk 8. If you are able to check whether this is failing on your side and the java version and vendor?

**Comment by violetagg** [comment] 2021-08-16 12:01
@crankydillo I cannot reproduce this with the provided test case. I'm closing this issue, we can reopen it if you can provide some reproducible example.

**Comment by crankydillo** [comment] 2021-08-17 14:01
Hi @violetagg .  This still fails with me.  I pushed my code to [this branch]().  Running this:

```
./gradlew reactor-netty-http:test --tests HeaderTest
```

```
$ java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (Zulu 8.38.0.13-CA-macosx) (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (Zulu 8.38.0.13-CA-macosx) (build 25.212-b04, mixed mode)
```

```
$ uname -a
Darwin LM-AST-40013529 19.6.0 Darwin Kernel Version 19.6.0: Tue Jun 22 19:49:55 PDT 2021; root:xnu-6153.141.35~1/RELEASE_X86_64 x86_64
```

If time allows, I'll try to test this on a Linux box.

**Comment by violetagg** [comment] 2021-08-17 15:20
@crankydillo reopening - I pushed to Github actions

with Zulu - it failes only on Mac and Windows with NIO
with Adopt - it fails for almost all OS/transport variations 

#1777

**Comment by violetagg** [comment] 2021-08-19 10:36
@crankydillo What you are observing is described here: https://docs.oracle.com/javase/8/docs/technotes/guides/net/articles/connection_release.html

In your PR #1586 you are suggesting to drain the incoming data.

According to the specification https://datatracker.ietf.org/doc/html/rfc7230#section-6.3, one can either read the entire request body and preserve the connection or just close the connection:

```
A server MUST read
   the entire request message body or close the connection after sending
   its response, since otherwise the remaining data on a persistent
   connection would be misinterpreted as the next request.
```

The implementation in Reactor Netty deliberately do not drain the incoming data for such requests.

**Comment by violetagg** [comment] 2021-08-23 08:28
@crankydillo I'm closing this one, we can reopen it if it is needed.

**Closed by violetagg** 2021-08-23 08:28 UTC
Labels: type/bug, for/user-attention

**Comment by crankydillo** [comment] 2021-08-23 15:43
Hey Violeta.  I don't think we need a change here.  I believe we experienced this while performing some header-related performance testing.  However, I'm still think think clients should not get a premature close exception in this case.  It still seems like you could avoid reading the entire stream, send a 413, and close the connection.  However, I'm not crystal clear on the HTTP spec wrt sending the response before consuming the entire request.

Anyhow, I'm not asking for this to be re-opened.  Just making sure I was clear:)
