### ISSUE TITLE
How to properly warmup connection pool

### ISSUE THREAD

**Issue by maczikasz** [reactor/reactor-netty#1023] opened 2020-03-09 21:30 UTC
Hey team. I am creating an application that needs to call another microservice, and add the minimum possible amount of latency doing so. So for that I wanted to give netty and the Spring webclient a try. 

On the first try i saw that calling the first time the netty version was much slower than the simple RestTemplate based ones, after some debugging and trace logging I realized that the reason this initial call was so slow is because the connection pool is only created on the first call. 

I tried adding a warmup call, which helped but I find it a not so elegant solution:
Without warmup
```
2020-03-09 22:28:10.696  INFO 4483 --- [nio-8080-exec-1] com.example.demo.ControllerConfigs       : Total took 317
2020-03-09 22:28:14.647  INFO 4483 --- [nio-8080-exec-2] com.example.demo.ControllerConfigs       : Total took 16
2020-03-09 22:28:15.746  INFO 4483 --- [nio-8080-exec-4] com.example.demo.ControllerConfigs       : Total took 14
2020-03-09 22:28:17.923  INFO 4483 --- [nio-8080-exec-6] com.example.demo.ControllerConfigs       : Total took 14
```

With warmup:
```
2020-03-09 22:29:05.307  INFO 4489 --- [nio-8080-exec-1] com.example.demo.ControllerConfigs       : Total took 32
2020-03-09 22:29:09.161  INFO 4489 --- [nio-8080-exec-2] com.example.demo.ControllerConfigs       : Total took 14
2020-03-09 22:29:09.558  INFO 4489 --- [nio-8080-exec-3] com.example.demo.ControllerConfigs       : Total took 13
2020-03-09 22:29:09.817  INFO 4489 --- [nio-8080-exec-4] com.example.demo.ControllerConfigs       : Total took 14
2020-03-09 22:29:09.992  INFO 4489 --- [nio-8080-exec-6] com.example.demo.ControllerConfigs       : Total took 13
```
Is there anything else I can do to optimize the first call performance? In my production I am running the app with very low CPU settings, so the difference is between 200ms for a normal call and 6-8 seconds for the initial one.

```kotlin
package com.example.demo

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.reactive.awaitSingle
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withContext
import org.slf4j.Logger
import org.slf4j.LoggerFactory
import org.springframework.beans.factory.annotation.Value
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration
import org.springframework.http.client.reactive.ReactorClientHttpConnector
import org.springframework.web.bind.annotation.PostMapping
import org.springframework.web.bind.annotation.RequestBody
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RestController
import org.springframework.web.client.RestTemplate
import org.springframework.web.reactive.function.BodyInserters
import org.springframework.web.reactive.function.client.WebClient
import reactor.core.publisher.Flux
import reactor.netty.http.client.HttpClient
import reactor.netty.resources.ConnectionProvider

@RestController
@RequestMapping("/sync")
class SyncController(@Value("\${target}") private val target: String, private val restTemplate: RestTemplate) {

    @PostMapping
    fun call(@RequestBody body: String): List<String> {
        val (time, result) = measureTimeMillis {
            body.split("+").fold(arrayListOf<List<String>>(arrayListOf())) { acc, s ->
                acc.add(acc.last().plus(s)); acc
            }.map { it.joinToString(" ") }
                    .map {
                        val (time, result) = measureTimeMillis {
                            restTemplate.postForEntity(target, it, String::class.java)
                                    .body!!
                        }
                        LOG.info("Call for $it took $time")
                        result
                    }
        }
        LOG.info("Total for took $time")

        return result
    }

    companion object {
        val LOG: Logger = LoggerFactory.getLogger(SyncController::class.java)
    }
}

@RestController
@RequestMapping("/coroutine")
class CoroutineController(@Value("\${target}") private val target: String, private val webClient: WebClient) {

    init {
        runBlocking {
            webClient.post()
                    .uri(target)
                    .body(BodyInserters.fromValue("warmup"))
                    .exchange()
                    .flatMap { it.toEntity(String::class.java) }
                    .map { it.body!! }
                    .awaitSingle()
        }
    }

    @PostMapping
    fun call(@RequestBody body: String): List<String> {
        val (time, result) = measureTimeMillis {
            runBlocking {
                withContext(Dispatchers.IO) {
                    body.split("+").fold(arrayListOf<List<String>>(arrayListOf())) { acc, s ->
                        acc.add(acc.last().plus(s)); acc
                    }.map { it.joinToString(" ") }
                            .map {
                                    webClient.post()
                                            .uri(target)
                                            .body(BodyInserters.fromValue(it))
                                            .exchange()
                                            .flatMap { it.toEntity(String::class.java) }
                                            .map { it.body!! }
                                            .awaitSingle()
                            }
                }//.map { it.awaitSingle() }
            }
        }
        LOG.info("Total took $time")

        return result
    }

    companion object {
        val LOG: Logger = LoggerFactory.getLogger(ControllerConfigs::class.java)
    }
}


@Configuration
class ControllerConfigs {
    @Bean
    fun restTemplate(): RestTemplate = RestTemplate()

    @Bean
    fun webClient(configuredHttpClient: HttpClient): WebClient =
            WebClient
                    .builder()
                    .clientConnector(ReactorClientHttpConnector(configuredHttpClient))
                    .build()

    @Suppress("ComplexMethod")
    @Bean
    fun configuredHttpClient(
    ): HttpClient = HttpClient
            .create()

    companion object {
        val LOG: Logger = LoggerFactory.getLogger(CoroutineController::class.java)
    }
}


inline fun <T> measureTimeMillis(block: () -> T): Pair<Long, T> {
    val start = System.currentTimeMillis()
    val t = block()
    return Pair(System.currentTimeMillis() - start, t)
}
```

**Comment by rstoyanchev** [comment] 2020-03-17 10:53
Is this with Spring MVC or WebFlux? Could how you describe how you are executing the requests? Do you have anything that ties the problem to the connection pool specifically, or are you just seeing that a warmup helps?

If would be most helpful if you provided an actual sample with exact dependencies.

**Comment by violetagg** [comment] 2020-03-17 10:54
@maczikasz Do you use Spring WebFlux or Spring MVC? From the example I can see that you utilise the WebClient but there is nothing for what you use as a server.

**Comment by violetagg** [comment] 2020-03-17 11:06
Also can you enable the metrics on the client like this:

```
    @Suppress("ComplexMethod")
    @Bean
    fun configuredHttpClient(
    ): HttpClient = HttpClient
            .create()
            .metrics(true)       <========= Enables HTTP client metrics
```

add to the pom.xml

```
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>io.micrometer</groupId>
			<artifactId>micrometer-registry-prometheus</artifactId>
		</dependency>
```

in application.properties add `management.endpoints.web.exposure.include=health,info,metrics,prometheus`

When you execute the first request access the metric below in order to see the connect time

`curl http://localhost:8080/actuator/metrics/reactor.netty.http.client.connect.time`

**Comment by maczikasz** [comment] 2020-03-19 13:14
the app in our porduction is based on websockets, but the call is happening inside a kotlin co-routine on the IO dispatcher, the example app is based on spring boot web and webflux, just for easier understanding as the behaviour is exactly the same. 

I figured it's the connection pool settings, because if I enable TRACE logs, I see that there is a lot of work being done on the first startup of the pool, including loading of native libraries, and so on, maybe it's not a CP but something else, the point is that it happens on first request, my assumption is that it the pool.

I can enable metrics and disable warmup on the example project, but I lost my SSD in the meantime, so I need to recreate it unfortunately, can you tell me what metrics you need?

**Comment by violetagg** [comment] 2020-03-19 13:33
> I figured it's the connection pool settings, because if I enable TRACE logs, I see that there is a lot of work being done on the first startup of the pool, including loading of native libraries, and so on, 

It will be interesting to see these logs, the only thing that happens when you hit the request (from connection pool point of view) is the actual connection to the remote peer. So here you may hit some DNS resolution.

So the metrics that are interesting are 

curl http://localhost:8080/actuator/metrics/reactor.netty.http.client.connect.time
curl http://localhost:8080/actuator/metrics/reactor.netty.http.client.address.resolver

**Comment by maczikasz** [comment] 2020-03-19 14:51
Without warmup:
https://gist.github.com/maczikasz/cc2b0e78f56c836d7dff2bc7dc3addb5

with the respective prom metrics
{"name":"reactor.netty.http.client.connect.time","description":"Time that is spent for connecting to the remote address","baseUnit":"seconds","measurements":[{"statistic":"COUNT","value":2.0},{"statistic":"TOTAL_TIME","value":0.006522804},{"statistic":"MAX","value":0.006108567}],"availableTags":[{"tag":"remote.address","values":["localhost:8089"]},{"tag":"status","values":["SUCCESS"]}]}
{"name":"reactor.netty.http.client.address.resolver","description":"Time that is spent for resolving the address","baseUnit":"seconds","measurements":[{"statistic":"COUNT","value":2.0},{"statistic":"TOTAL_TIME","value":0.001591446},{"statistic":"MAX","value":0.001545068}],"availableTags":[{"tag":"remote.address","values":["localhost:8089"]},{"tag":"status","values":["SUCCESS"]}]}

With warmup:
https://gist.github.com/maczikasz/51e963098af727d4591a54fc258d0c5a

{"name":"reactor.netty.http.client.address.resolver","description":"Time that is spent for resolving the address","baseUnit":"seconds","measurements":[{"statistic":"COUNT","value":1.0},{"statistic":"TOTAL_TIME","value":0.002472061},{"statistic":"MAX","value":0.0}],"availableTags":[{"tag":"remote.address","values":["localhost:8089"]},{"tag":"status","values":["SUCCESS"]}]}

{"name":"reactor.netty.http.client.connect.time","description":"Time that is spent for connecting to the remote address","baseUnit":"seconds","measurements":[{"statistic":"COUNT","value":1.0},{"statistic":"TOTAL_TIME","value":0.012744048},{"statistic":"MAX","value":0.0}],"availableTags":[{"tag":"remote.address","values":["localhost:8089"]},{"tag":"status","values":["SUCCESS"]}]}

**Comment by martin-tarjanyi** [comment] 2020-03-20 21:03
Isn't this issue duplicate of this one?
https://github.com/reactor/reactor-netty/issues/560

**Comment by maczikasz** [comment] 2020-03-20 21:27
possibly yes

**Comment by ndhilliprasad** [comment] 2020-05-28 04:15
Could you one help with work around solution for this?

**Comment by echoesbr** [comment] 2020-05-28 13:54
Having the same issue here. Similar setup reported by @maczikasz.

**Comment by violetagg** [comment] 2020-11-17 12:58
@maczikasz I think this is duplicate to #560 
See my last comment there

**Comment by violetagg** [comment] 2021-01-08 12:50
We will address this issue with #1455

**Closed** 2021-01-11 07:02 UTC
Labels: type/enhancement

**Comment by benjaminknauer** [comment] 2021-02-10 16:27
Copy & paste from #1455 for better google experience for people with the same issue:

Hi there :wave:

We upgraded Spring Boot to 2.4.2 with reactor-netty 1.0.3 but still encounter this issue.
Here is our upgraded configuration:

``` 
   @Bean
    public WebClient createWebClient(WebClient.Builder webClientBuilder) {
        log.info("Initializing WebClient Bean");

        final int timeoutInMillis = Long.valueOf(TimeUnit.SECONDS.toMillis(timeout)).intValue();
        final HttpClient httpClient = HttpClient.create()
                .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, timeoutInMillis)
                .responseTimeout(Duration.ofMillis(timeoutInMillis))
                .doOnConnected(conn ->
                        conn.addHandlerLast(new ReadTimeoutHandler(timeoutInMillis, TimeUnit.MILLISECONDS))
                                .addHandlerLast(new WriteTimeoutHandler(timeoutInMillis, TimeUnit.MILLISECONDS)));
        final ClientHttpConnector connector = new ReactorClientHttpConnector(httpClient);
        final WebClient webClient = webClientBuilder
                .clientConnector(connector)
                .defaultHeader("x-clientname", clientname)
                .build();

        httpClient.warmup().block();
        log.info("WebClient initialized");

        return webClient;
    }
```

Our call with WebClient:
```
  ResoponseObject doCall() {
        return this.webClient
                .get()
                .uri("http://***.de/api/rest/***")
                .accept(MediaType.APPLICATION_JSON)
                .retrieve()
                .bodyToMono(ResponseObject.class)
                .block();
    }
```

With debugging enabled via application.yaml:
`logging.level.reactor.netty: debug`

We now see this during application startup:
```
2021-02-10 17:02:31,922 INFO  d.t.e.b.c.c.WebClientAutoConfiguration - Initializing WebClient Bean 
2021-02-10 17:02:31,959 DEBUG r.n.r.DefaultLoopIOUring - Default io_uring support : false 
2021-02-10 17:02:31,967 DEBUG r.n.r.DefaultLoopEpoll - Default Epoll support : true 
2021-02-10 17:02:31,997 INFO  d.t.e.b.c.c.WebClientAutoConfiguration - WebClient initialized 
```
This should be an indication that the warmup works as expected?

But on first request this happens:
```
2021-02-10 17:05:16,045 DEBUG o.s.w.r.f.c.ExchangeFunctions - [73d400c8] HTTP GET http://***.de/api/rest/***
2021-02-10 17:05:16,050 DEBUG r.n.r.PooledConnectionProvider - Creating a new [http] client pool [PoolFactory{evictionInterval=PT0S, leasingStrategy=fifo, maxConnections=500, maxIdleTime=-1, maxLifeTime=-1, metricsEnabled=false, pendingAcquireMaxCount=1000, pendingAcquireTimeout=45000}] for [***.de/<unresolved>:80] 
2021-02-10 17:05:29,619 DEBUG r.n.r.DefaultPooledConnectionProvider - [id: 0x71b840f4] Created a new pooled channel, now 1 active connections and 0 inactive connections 
2021-02-10 17:05:29,635 DEBUG r.n.t.TransportConfig - [id: 0x71b840f4] Initialized pipeline DefaultChannelPipeline{(reactor.left.httpCodec = io.netty.handler.codec.http.HttpClientCodec), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)} 
...
```
In our case, creating the client pool is the problem. On a decent machine, it takes about 13 seconds.

Can you give us any comment on that? This is very this is very frustrating for us.

Thanks a lot!

**Comment by violetagg** [comment] 2021-02-10 16:40
https://github.com/reactor/reactor-netty/pull/1455#issuecomment-776842252
