### ISSUE TITLE
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Operation timed out

### ISSUE THREAD

**Issue by konstantinshevchuk** [reactor/reactor-netty#641] opened 2019-03-15 20:30 UTC
### OS version (e.g. `uname -a`)

Spring boot 2.1.3-RELEASE / Reactor-Netty 0.8.5-RELEASE

`io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Operation timed out`

Used NIO 100% `[reactor-http-nio-7]`

Happens one or two times per hour (Docker). Almost impossible to reproduce locally (MacBook Pro).

Is that platform dependent error?

**Comment by smaldini** [comment] 2019-03-21 05:38
Do you have a reproduction use case or a scenario that looks like your problem?

**Comment by konstantinshevchuk** [comment] 2019-03-21 13:31
@smaldini 
I can show only the WARN line in my log file

`[id: 0xdea62af2, L:/172.19.0.5:53938 - R:comoany-dev.oktapreview.com/15.182.2.60:443] The connection observed an error`

This happens couple of time per hours. No more errors in the log file.

**Comment by TomDush** [comment] 2019-05-10 14:03
Me too. I'm afraid I don't have better reproducible steps.
It happens every time after an idle period.

Java 12
Spring Boot 2.1.4
Reactor-netty: 0.8.6
Ubuntu/Docker/Kubernetes/Azure Container Service

Warn message is with salesforce oauth2:
```
WARN 18 --- [or-http-epoll-1] r.netty.http.client.HttpClientConnect    : [id: 0x1bf5a0c4, L:/xxx - R:login.salesforce.com/85.222.153.195:443] The connection observed an error
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection timed out
        at io.netty.channel.unix.Errors.newIOException(Errors.java:122) ~[netty-transport-native-unix-common-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.channel.unix.Errors.ioResult(Errors.java:146) ~[netty-transport-native-unix-common-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.channel.unix.FileDescriptor.readAddress(FileDescriptor.java:177) ~[netty-transport-native-unix-common-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.channel.epoll.AbstractEpollChannel.doReadBytes(AbstractEpollChannel.java:343) ~[netty-transport-native-epoll-4.1.34.Final-linux-x86_64.jar!/:4.1.34.Final]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:782) ~[netty-transport-native-epoll-4.1.34.Final-linux-x86_64.jar!/:4.1.34.Final]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:427) ~[netty-transport-native-epoll-4.1.34.Final-linux-x86_64.jar!/:4.1.34.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:328) ~[netty-transport-native-epoll-4.1.34.Final-linux-x86_64.jar!/:4.1.34.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[netty-common-4.1.34.Final.jar!/:4.1.34.Final]
        at java.base/java.lang.Thread.run(Thread.java:835) ~[na:na]
```

**Comment by darklynx** [comment] 2019-07-18 15:26
same here :(

```
2019-07-18 17:16:36.273  INFO 14157 --- [or-http-epoll-3] c.o.o.m.web.controllers.ListController   : Request to create a LIST object
2019-07-18 17:16:36.311  WARN 14157 --- [or-http-epoll-2] reactor.netty.channel.FluxReceive        : [id: 0xce1b374d, L:/172.30.8.55:60716 - R:api.integration.***.com/***:443] An exception has been observed post termination, use DEBUG level to see the full stack: io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer
2019-07-18 17:16:36.319  INFO 14157 --- [or-http-epoll-3] reactor.netty.http.server.AccessLog      : 127.0.0.1 - - [18/Jul/2019:17:16:36 +0200] "POST /api/lists HTTP/1.0" 200 0 8090 50 ms
```

**Comment by dkulig** [comment] 2020-01-28 08:26
Did anyone find a solution for the "Connection reset by peer" thing?

**Comment by violetagg** [comment] 2020-01-28 08:31
@dkulig this issues is for `Connection timed out` not `Connection reset by peer`. May be you need this one #564

**Comment by dkulig** [comment] 2020-01-28 08:39
My apologizes @violetagg - wrong issue

**Comment by asdf2014** [comment] 2020-03-18 07:48
Hi, @violetagg. The `keepAlive` parameter is currently enabled on my Netty server. Will the problem be triggered after receiving a short TCP connection?

```java
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
```

**Comment by violetagg** [comment] 2020-03-18 07:52
@asdf2014 This issue is for `operation timed out`. Please open a new issue and describe your scenario as well as the Reactor Netty version.
Thanks

**Comment by asdf2014** [comment] 2020-03-18 07:53
@violetagg Sure.

**Comment by SudBisht** [comment] 2020-05-03 14:13
@konstantinshevchuk  did you get any solution?

**Comment by meiyuisgithub** [comment] 2020-06-09 09:16
请教下大佬，gateway代理前端工程，页面暂停操作一段时间就会出现io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer报错：

2020-06-09 09:42:05.828 [reactor-http-epoll-1] ERROR o.s.w.s.a.HttpWebHandlerAdapter - [23b53156-170] 500 Server Error for HTTP GET "/gbd/index.html"
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
        |_ checkpoint ⇢ org.springframework.web.cors.reactive.CorsWebFilter [DefaultWebFilterChain]
        |_ checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
        |_ checkpoint ⇢ HTTP GET "/gbd/index.html" [ExceptionHandlingWebHandler]
Stack trace:
2020-06-09 09:42:06.750 [reactor-http-epoll-2] WARN  r.n.http.client.HttpClientConnect - [id: 0x18f3cd56, L:/172.17.0.104:37314 - R:192.168.42.50/192.168.42.50:80] The connection observed an error
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
2020-06-09 09:42:06.752 [reactor-http-epoll-2] ERROR o.s.w.s.a.HttpWebHandlerAdapter - [23b53156-171] 500 Server Error for HTTP GET "/gbd/index.html"
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
        |_ checkpoint ⇢ org.springframework.web.cors.reactive.CorsWebFilter [DefaultWebFilterChain]
        |_ checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
        |_ checkpoint ⇢ HTTP GET "/gbd/index.html" [ExceptionHandlingWebHandler]

**Comment by bearRunning** [comment] 2020-06-17 01:31
> 请教下大佬，网关代理前端工程，页面暂停操作将会出现io.netty.channel.unix.Errors $ NativeIoException：readAddress（..）失败：对等连接重置
> 
> 2020-06-09 09：42：05.828 [reactor-http-epoll-1]错误oswsaHttpWebHandlerAdapter-[23b53156-170] 500 HTTP GET服务器错误“ /gbd/index.html”
> io.netty.channel.unix.Errors $ NativeIoException：readAddress（..）失败：对等方重置连接
> 抑制：reactor.core.publisher.FluxOnAssembly $ OnAssemblyException：
> 在以下站点发现错误：
> | _检查点⇢org.springframework.web.cors。
> react.CorsWebFilter [DefaultWebFilterChain] | _检查点⇢org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
> | _检查点⇢HTTP GET“ /gbd/index.html” [ExceptionHandlingWebHandler]
> 堆栈跟踪：
> 2020-06-09 09：42：06.750 [reactor-http-epoll-2] WARN rnhttp.client.HttpClientConnect-[id：0x18f3cd56，L：/172.17.0.104：37314-R：192.168.42.50/192.168.42.50： 80]连接观察到错误
> io.netty.channel.unix.Errors $ NativeIoException：readAddress（..）失败：对等节点
> 2020-06-09 09：42：06.752 重置连接[reactor-http-epoll-2]错误oswsaHttpWebHandlerAdapter-[23b53156-171] HTTP GET“ /gbd/index.html”
> io.netty.channel.unix.Errors $ NativeIoException的500服务器错误：readAddress（..）失败：对等方重置连接被
> 禁止：reactor.core。 Publisher.FluxOnAssembly $ OnAssemblyException：
> 在以下站点发现错误：
> | _检查点⇢org.springframework.web.cors.reactive.CorsWebFilter [DefaultWebFilterChain]
> | _检查点⇢org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
> | _检查点⇢HTTP GET“ /gbd/index.html” [ExceptionHandlingWebHandler]

同问  你的问题解决了么

**Comment by violetagg** [comment] 2020-08-20 16:01
@sivapolisetty Do you experience this with the latest release?

**Comment by sivapolisetty** [comment] 2020-08-20 16:12
Yes @violetagg .
Spring boot 2.3.2-RELEASE / Reactor-Netty 0.9.10-RELEASE. 
Docker/Openshift environment. Getting "logger_name":"reactor.netty.http.client.HttpClientConnect","thread_name":"reactor-http-epoll-4","level":"WARN","level_value":30000,"stack_trace":"io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Operation timed out\n"

Not able to reproduce on Mac

**Comment by violetagg** [comment] 2020-08-21 06:32
@sivapolisetty Is it possible to take a tcpdump?

**Comment by kaladhar-mummadi** [comment] 2020-09-16 17:09
@violetagg experienced same `java.io.IOException: Operation timed out`. 
Attached the tcpdump log. Please let me know if more details are needed.
Also trying to understand why this happens. Does this mean that underlying socket connection is closed but channel is trying to retransmit on the same socket ?
<img width="1080" alt="Screen Shot 2020-09-16 at 10 05 28 AM" src="https://user-images.githubusercontent.com/3730954/93369505-56eaaf80-f804-11ea-8591-b5939220d740.png">

**Comment by darshan4545** [comment] 2020-10-29 23:07
any update on this issue ??

**Comment by chhaviLife360** [comment] 2020-11-01 00:14
I am facing the same issue, we are using `spring boot 2.2.0` and below java version-
```
openjdk 11.0.6 2020-01-14 LTS
OpenJDK Runtime Environment Zulu11.37+17-CA (build 11.0.6+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.37+17-CA (build 11.0.6+10-LTS, mixed mode)
```

reactor.core.Exceptions$ReactiveException: io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
	at reactor.core.Exceptions.propagate(Exceptions.java:336) ~[reactor-core-3.3.0.RELEASE.jar!/:3.3.0.RELEASE]
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:91) ~[reactor-core-3.3.0.RELEASE.jar!/:3.3.0.RELEASE]
	at reactor.core.publisher.Mono.block(Mono.java:1663) ~[reactor-core-3.3.0.RELEASE.jar!/:3.3.0.RELEASE]
	at com.life360.services.idprotect.service.webclient.impl.SontiqWebClientService.createUser(SontiqWebClientService.java:86) ~[classes!/:0.0.1-SNAPSHOT]
	at com.life360.services.idprotect.service.SontiqApiService.createUser(SontiqApiService.java:108) ~[classes!/:0.0.1-SNAPSHOT]
	at com.life360.services.idprotect.service.SontiqApiService$$FastClassBySpringCGLIB$$ca240d1e.invoke(<generated>) ~[classes!/:0.0.1-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769) ~[spring-aop-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) ~[spring-aop-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88) ~[spring-aop-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at io.github.resilience4j.circuitbreaker.CircuitBreaker.lambda$decorateCheckedSupplier$82a9021a$1(CircuitBreaker.java:73) ~[resilience4j-circuitbreaker-1.5.0.jar!/:1.5.0]
	at io.github.resilience4j.circuitbreaker.CircuitBreaker.executeCheckedSupplier(CircuitBreaker.java:810) ~[resilience4j-circuitbreaker-1.5.0.jar!/:1.5.0]
	at io.github.resilience4j.circuitbreaker.configure.CircuitBreakerAspect.defaultHandling(CircuitBreakerAspect.java:188) ~[resilience4j-spring-1.5.0.jar!/:1.5.0]
	at io.github.resilience4j.circuitbreaker.configure.CircuitBreakerAspect.proceed(CircuitBreakerAspect.java:135) ~[resilience4j-spring-1.5.0.jar!/:1.5.0]
	at io.github.resilience4j.circuitbreaker.configure.CircuitBreakerAspect.lambda$circuitBreakerAroundAdvice$6edadc33$1(CircuitBreakerAspect.java:118) ~[resilience4j-spring-1.5.0.jar!/:1.5.0]
	at io.github.resilience4j.fallback.DefaultFallbackDecorator.lambda$decorate$52452fd9$1(DefaultFallbackDecorator.java:36) ~[resilience4j-spring-1.5.0.jar!/:1.5.0]
	at io.github.resilience4j.circuitbreaker.configure.CircuitBreakerAspect.circuitBreakerAroundAdvice(CircuitBreakerAspect.java:118) ~[resilience4j-spring-1.5.0.jar!/:1.5.0]
	at jdk.internal.reflect.GeneratedMethodAccessor172.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644) ~[spring-aop-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633) ~[spring-aop-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) ~[spring-aop-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175) ~[spring-aop-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) ~[spring-aop-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93) ~[spring-aop-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) ~[spring-aop-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) ~[spring-aop-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at com.life360.services.idprotect.service.SontiqApiService$$EnhancerBySpringCGLIB$$911122b3.createUser(<generated>) ~[classes!/:0.0.1-SNAPSHOT]
	at com.life360.services.idprotect.consumer.PendingMessagesStreamsConsumer.processNewUserCircleChange(PendingMessagesStreamsConsumer.java:298) ~[classes!/:0.0.1-SNAPSHOT]
	at com.life360.services.idprotect.consumer.PendingMessagesStreamsConsumer$MessageType$2.lambda$process$1(PendingMessagesStreamsConsumer.java:792) ~[classes!/:0.0.1-SNAPSHOT]
	at java.util.Optional.ifPresentOrElse(Optional.java:203) ~[?:?]
	at com.life360.services.idprotect.consumer.PendingMessagesStreamsConsumer$MessageType$2.process(PendingMessagesStreamsConsumer.java:788) ~[classes!/:0.0.1-SNAPSHOT]
	at com.life360.services.idprotect.consumer.PendingMessagesStreamsConsumer.lambda$processPendingMessage$0(PendingMessagesStreamsConsumer.java:200) ~[classes!/:0.0.1-SNAPSHOT]
	at java.util.Optional.ifPresentOrElse(Optional.java:201) ~[?:?]
	at com.life360.services.idprotect.consumer.PendingMessagesStreamsConsumer.processPendingMessage(PendingMessagesStreamsConsumer.java:200) ~[classes!/:0.0.1-SNAPSHOT]
	at com.life360.services.idprotect.consumer.PendingMessagesStreamsConsumer.processRecord(PendingMessagesStreamsConsumer.java:184) ~[classes!/:0.0.1-SNAPSHOT]
	at com.life360.services.idprotect.consumer.ResilientRecordProcessor.processRecord(ResilientRecordProcessor.java:43) [classes!/:0.0.1-SNAPSHOT]
	at com.life360.services.idprotect.consumer.DynamoDbStreamsConsumer$StreamsRecordProcessorWithMetrics.processRecords(DynamoDbStreamsConsumer.java:219) [classes!/:0.0.1-SNAPSHOT]
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ProcessTask.callProcessRecords(ProcessTask.java:221) [amazon-kinesis-client-1.13.3.jar!/:?]
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ProcessTask.call(ProcessTask.java:176) [amazon-kinesis-client-1.13.3.jar!/:?]
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:49) [amazon-kinesis-client-1.13.3.jar!/:?]
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:24) [amazon-kinesis-client-1.13.3.jar!/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:93) ~[reactor-core-3.3.0.RELEASE.jar!/:3.3.0.RELEASE]
		at reactor.core.publisher.Mono.block(Mono.java:1663) ~[reactor-core-3.3.0.RELEASE.jar!/:3.3.0.RELEASE]

**Comment by violetagg** [comment] 2020-11-03 08:47
@chhaviLife360 Your exception is `Connection reset by peer` and the issue is for `Operation timed out`.
Please update to the latest Spring 2.2.x  as 2.2.0 is more than a year old.

**Comment by darshan4545** [comment] 2020-11-04 15:06
@violetagg using latest version and still getting this error

**Comment by violetagg** [comment] 2020-11-04 15:26
@darklynx Any chance for a reproducible example?

**Comment by darshan4545** [comment] 2020-11-30 01:06
https://github.com/spring-cloud/spring-cloud-gateway/tree/master/spring-cloud-gateway-sample

using same above code

**Comment by elibus** [comment] 2021-01-26 11:02
Same problem here. We have two servers calling a load balancer VIP and they both get a connection timeout error about once a day. We have noticed that this happens at about the same time.

**Comment by iblogc** [comment] 2021-03-20 14:13
@meiyuisgithub @bearRunning 请求你们的这个问题最后解决了吗？

**Comment by violetagg** [comment] 2021-11-01 09:44
@sonik-24 Any reproducible example? If yes can you open a new issue?

**Comment by violetagg** [comment] 2021-11-01 09:45
Closing this issue as there is no enough information in order to proceed with the investigation

**Closed by violetagg** 2021-11-01 09:45 UTC
Labels: status/need-investigation
