### ISSUE TITLE
HttpServer Underlying Downstream HttpClient Connection Getting Closed Quietly

### ISSUE THREAD

**Issue by ragini16071998** [reactor/reactor-netty#3014] opened 2024-01-04 08:35 UTC
**Problem Statement:**
There is a netty HttpServer, exposing an API(let's say API ax) and also interacts with the underlying netty HTTP downstream client for processing the same, we've observed a scenario when the client of API ax cancels a request before completion or encounters a read timeout. In such cases, the server's underlying HttpClient channel closes quietly without generating any exceptions and this behavior remains undetected in HttpClient in both the doOnRequestError and doOnResponseError methods.

Could you please provide guidance on how we can trace such requests and correlate them with the expected HTTP status?

**What's Happening:**
In HttpClientOperations.java class, inside onInboundClose() method, after API ax cancels request or readTimeout, first if block condition gets passed( if (isInboundCancelled() || isInboundDisposed())) which closes connection quietly without changing HttpClientState however for other cases HttpClientState set to RESPONSE_INCOMPLETE which gets caught in HttpClient.doOnResponseError() methods and can be handled at application layer accordingly(PFA)!

**What's Expected:**
There should be a way to catch such unexpected request cancellation or readTimeout at  application level so that they can be properly handled or logged which can be achieved either on doOnDisconnected() method by adding some identifier or changing HttpClientState appropriately and then catch and handle the same at application layer.

[logs.txt](https://github.com/reactor/reactor-netty/files/13827787/logs.txt)

<img width="1254" alt="Screenshot 2024-01-04 at 11 37 50 AM" src="https://github.com/reactor/reactor-netty/assets/17300155/385798dd-9048-4c61-ae7d-4698f9725c75">

**Comment by violetagg** [comment] 2024-01-04 09:04
@ragini16071998 Please provide some reproducible example.

**Comment by ragini16071998** [comment] 2024-01-09 20:49
Hi @violetagg ,
Find below the reproducible example.
Here client server dependency looks like:
**client1 -> server1(client2 -> server2)**

Since we are doing some logging on the server1 side by using some HttpClient methods like doOnRequestError, doOnResponse, doOnResponseError etc(refer client2 config), but in case of client1 responseTimeout, we are not able to log anything because the client2 channel gets closed quietly and it doesn't get captured neither in doOnRequestError method nor in doOnResponseError method hence for such client1 API calls we are not able to log response status.



` 
    @Test
    public void testMethod() {

        HttpServer server2 =
                HttpServer.create()
                        .port(8086)
                        .route(r ->
                                r.get("/goodMorning",
                                        (req, res) ->
                                                res.sendString(Mono.just("Good Morning!").delayElement(java.time.Duration.ofSeconds(1))
                                                )));


        DisposableServer ds2 = server2.bindNow();

        HttpClient client2;
        client2 = HttpClient.create()
                .port(ds2.port())
                .doOnRequestError((req, error) -> System.out.println("RequestError: " + error.getMessage()))
                .doOnResponse((res, anything) -> System.out.println("ResponseMessage: " + res))
                .doOnResponseError((res, error) -> System.out.println("ResponseError: " + error.getMessage()))
                .doOnDisconnected((conn) -> System.out.println("Disconnected: " + conn));

        HttpServer server1 =
                HttpServer.create()
                        .port(8085)
                        .route(r -> r.get("/hello",
                                (req, res) ->

                                        res.sendString(client2.get()
                                                .uri("/goodMorning")
                                                .responseContent()
                                                .aggregate()
                                                .asString())));

        DisposableServer ds = server1.bindNow();

        HttpClient client1;
        client1 = HttpClient.create()
                .port(ds.port())
                .responseTimeout(java.time.Duration.ofMillis(5000));
        String response =
                client1.get()
                        .uri("/hello")
                        .responseContent()
                        .aggregate()
                        .asString()
                        .block();

        System.out.println("Final Response: " + response);
    }
`

**Comment by violetagg** [comment] 2024-01-10 15:09
@ragini16071998 Thanks a lot for the test, this makes things clear.

You have this:

```
client1 -> server1(client2) -> server2
         ^                   ^
       connection1         connection2
```

Your configuration with `doOn...` covers the `connection2`, while what actually happens is that `connection1` is closed due to a timeout.

When `connection1` is closed, the only thing that the `server1` will do is to `cancel` the `Publisher` provided by `client2`. You need to start listening for that kind of cancellations. Here is the configuration that you need:

```
HttpServer server1 =
		HttpServer.create()
			.port(8085)
			.route(r -> r.get("/hello",
				(req, res) ->
					res.sendString(client2.get()
							.uri("/goodMorning")
							.responseContent()
							.aggregate()
							.asString())
						.then()
--> listen for cancel signal			.doOnCancel(() -> System.out.println("Cancel signal received"))));
```

This explains why you are entering the code in your first comment -> because the inbound was canceled.

**Comment by violetagg** [comment] 2024-01-15 08:39
@ragini16071998 I'm closing this as I think there is no issue with Reactor Netty. We can reopen it if needed.

**Closed by violetagg** 2024-01-15 08:39 UTC
Labels: for/stackoverflow, for/user-attention
