### ISSUE TITLE
Websocket 

### ISSUE THREAD

**Issue by 1ssqq1lxr** [reactor/reactor-netty#2804] opened 2023-05-16 09:12 UTC
## Expected Behavior

Initialize a websocket client to continuously send messages

## Actual Behavior

The server did not receive any messages sent

## code

```
  public WebsocketSender() {
        HttpClient.create()
                    .wiretap(true)
                    .websocket()
                    .uri("ws://127.0.0.1:1887/hahaha")
                    .handle((websocketInbound, websocketOutbound) -> {
                        this.sendText(websocketOutbound);
                        return websocketOutbound.neverComplete();

                    })
                    .subscribe();


//      HttpClient.create()
//                    .wiretap(true)
//                    .websocket()
//                    .uri("ws://127.0.0.1:1887/hahaha")
//                    .connect()
//                  .doOnNext(connection1 -> {
//                      connection1.outbound().sendString(Mono.just("hello")).then().subscribe();
//                  })
//                  .subscribe(connections::add);
    }

    private void sendText(WebsocketOutbound websocketOutbound) {
        new Thread(()->{
            while (true){
                websocketOutbound. send(Mono.just(PooledByteBufAllocator.DEFAULT.buffer().writeBytes("1231313".getBytes()))).then().subscribe();
            }
        }).start();
    }
```

## log

```
17:05:30.101 [reactor-http-nio-2] DEBUG reactor.netty.http.client.HttpClient - [14c49a15-1, L:/127.0.0.1:61710 - R:/127.0.0.1:1887] WRITE: 13B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 82 87 71 e8 54 db 40 da 67 ea 42 d9 67          |..q.T.@.g.B.g   |
+--------+-------------------------------------------------+----------------+
17:05:30.102 [reactor-http-nio-2] DEBUG reactor.netty.http.client.HttpClient - [14c49a15-1, L:/127.0.0.1:61710 - R:/127.0.0.1:1887] WRITE: 13B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 82 87 33 de 07 e8 02 ec 34 d9 00 ef 34          |..3.....4...4   |
+--------+-------------------------------------------------+----------------+
17:05:30.102 [reactor-http-nio-2] DEBUG reactor.netty.http.client.HttpClient - [14c49a15-1, L:/127.0.0.1:61710 - R:/127.0.0.1:1887] WRITE: 13B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 82 87 18 4b 24 b7 29 79 17 86 2b 7a 17          |...K$.)y..+z.   |
+--------+-------------------------------------------------+----------------+
17:05:30.102 [reactor-http-nio-2] DEBUG reactor.netty.http.client.HttpClient - [14c49a15-1, L:/127.0.0.1:61710 - R:/127.0.0.1:1887] WRITE: 13B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 82 87 27 b8 c7 ce 16 8a f4 ff 14 89 f4          |..'..........   |
+--------+-------------------------------------------------+----------------+
17:05:30.102 [reactor-http-nio-2] DEBUG reactor.netty.http.client.HttpClient - [14c49a15-1, L:/127.0.0.1:61710 - R:/127.0.0.1:1887] WRITE: 13B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 82 87 3a e4 e1 60 0b d6 d2 51 09 d5 d2          |..:..`...Q...   |
```

It seems like there's no problem, I'm using reactor netty version 1.0.22

**Comment by violetagg** [comment] 2023-05-16 12:12
@1ssqq1lxr I cannot reproduce the issue https://github.com/violetagg/GH-2804

**Comment by violetagg** [comment] 2023-05-19 08:11
@1ssqq1lxr I'm closing this one. If it is needed we can reopen it.

**Closed by violetagg** 2023-05-19 08:11 UTC
Labels: for/user-attention
