### ISSUE TITLE
Server hangs indefinitely for a css or js resource to load and eventually fails with java.lang.Exception: ChannelOperation terminal stack

### ISSUE THREAD

**Issue by umeshmorsu2018** [reactor/reactor-netty#464] opened 2018-10-15 18:02 UTC
We have configured spring cloud gateway to route requests to back-end service. Some resources in the back-end service failing due to following error (java.lang.IllegalArgumentException: invalid version format: 3B). Any help is appreciated.

> 2018-10-15 13:50:02.260 DEBUG 2529 --- [ctor-http-nio-7] r.i.n.channel.ChannelOperationsHandler : [id: 0x54207d36, L:/xx.xx.xxx.xxx:xxxxx - R:xxxx/xx.xx.xx.xx:xxxxx] Decoding failed: DefaultFullHttpResponse(decodeResult: failure(java.lang.IllegalArgumentException: invalid version format: 3B), version: HTTP/1.0, content: UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 0, widx: 0, cap: 0))
> HTTP/1.0 999 Unknown : 
> 
> java.lang.IllegalArgumentException: invalid version format: 3B
>  at io.netty.handler.codec.http.HttpVersion.<init>(HttpVersion.java:121) ~[netty-codec-http-4.1.29.Final.jar:4.1.29.Final]
>  at io.netty.handler.codec.http.HttpVersion.valueOf(HttpVersion.java:76) ~[netty-codec-http-4.1.29.Final.jar:4.1.29.Final]
>  at io.netty.handler.codec.http.HttpResponseDecoder.createMessage(HttpResponseDecoder.java:118) ~[netty-codec-http-4.1.29.Final.jar:4.1.29.Final]
>  at io.netty.handler.codec.http.HttpObjectDecoder.decode(HttpObjectDecoder.java:219) ~[netty-codec-http-4.1.29.Final.jar:4.1.29.Final]
>  at io.netty.handler.codec.http.HttpClientCodec$Decoder.decode(HttpClientCodec.java:202) ~[netty-codec-http-4.1.29.Final.jar:4.1.29.Final]
>  at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[netty-codec-4.1.29.Final.jar:4.1.29.Final]
>  at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[netty-codec-4.1.29.Final.jar:4.1.29.Final]
>  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[netty-codec-4.1.29.Final.jar:4.1.29.Final]
>  at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.29.Final.jar:4.1.29.Final]

**Comment by violetagg** [comment] 2018-10-15 18:09
Hi,

Please provide information for Reactor Netty/Spring Gateway versions. OS/Jdk?
Also a minimum reproducible scenario will be very helpful.

Regards,
Violeta

**Comment by violetagg** [comment] 2018-10-16 15:42
Yes please try to provide some reproducible example otherwise it will be hard to figure out what happens.
If you are not able to reproduce then set Reactor Netty log level to DEBUG and then try to correlated the logs for the bad request/response using the channel ID.

In the log above:
> 2018-10-15 13:50:02.260 DEBUG 2529 --- [ctor-http-nio-7] r.i.n.channel.ChannelOperationsHandler : [id: 0x54207d36, L:/xx.xx.xxx.xxx:xxxxx - R:xxxx/xx.xx.xx.xx:xxxxx]

this is the channel ID `id: 0x54207d36`

**Comment by violetagg** [comment] 2018-11-19 16:48
There is no update from the author for a month and with this incomplete information it is hard to figure out what happens.
Closing the issue, you can reopen it if you have more information.

**Closed by violetagg** 2018-11-19 16:48 UTC
Labels: need-more-info
