### ISSUE TITLE
Connection timeout to Netty Server

### ISSUE THREAD

**Issue by yechao4j** [reactor/reactor-netty#1032] opened 2020-03-19 08:20 UTC
My springcloud gateway project start with default netty configurations. My own global filter costs 500ms, and under hign load test at 300 concurrent threads, then type command like below:
```
[root@ks-m2 ~]# ss -lnt | grep 8080
State       Recv-Q   Send-Q      Local Address:Port 
LISTEN      129         128                       8080  
```
it seem like Recv-Q is full, then the nginx before the gateway throw errors:
```
2020/03/18 11:59:29 [error] 1570#0: *4402894538 connect() failed (110: Connection timed out) while connecting to upstream...
```
I don't understand how this happens, maybe my gateway netty configuration wrong?
Here is the minimal reproducible project:
https://github.com/yechao4j/netty-pool-sampler
Please help!

**Comment by violetagg** [comment] 2020-03-19 08:33
@yechao4j I would say that the issue is that you block the event loop. Try to use different thread pool for the sleep.

**Comment by yechao4j** [comment] 2020-03-19 09:01
@violetagg  Thread.Sleep is my sampler, in my real production scenario, the filter will get data from other service, sometimes it may costs more than 500ms. Like you say it blocked the event loop. Is there a good way to fix this problem?

**Comment by violetagg** [comment] 2020-03-19 09:15
@yechao4j Check this https://projectreactor.io/docs/core/release/reference/#faq.wrap-blocking

**Comment by yechao4j** [comment] 2020-03-19 09:18
@violetagg  Thanks very much, i try it first.

**Comment by yechao4j** [comment] 2020-03-19 10:07
@violetagg To use `Schedulers.boundedElastic()`, may i need to upgrade reactor-core version to 3.3.3.RELEASE？Cuurent is 3.2.11.RELEASE.

**Comment by violetagg** [comment] 2020-03-19 10:33
@yechao4j it is `Schedulers.elastic()` in the older versions without boundary

**Comment by violetagg** [comment] 2020-03-20 10:46
I'm closing this. If there is an issue in Reactor Netty we can reopen it.

**Closed by violetagg** 2020-03-20 10:46 UTC
Labels: for/stackoverflow
