### ISSUE TITLE
ByteBuf.release() - LEAK

### ISSUE THREAD

**Issue by itzikiusa** [reactor/reactor-netty#1178] opened 2020-06-24 07:04 UTC
Hi, 
i'm using Java 8
reactor netty v. 0.9.9.RELEASE
spring boot frame work v.2.3.1.RELEASE and spring cloud Hoxton.SR5
getting this error when trying to upload an image
under Ubuntu

```
2020-06-23 19:25:50.745 [ERROR] [reactor-http-epoll-2] [io.netty.util.ResourceLeakDetector:320] LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records:
Created at:
	io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:363)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
	io.netty.channel.unix.PreferredDirectByteBufAllocator.ioBuffer(PreferredDirectByteBufAllocator.java:53)
	io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
	io.netty.channel.epoll.EpollRecvByteAllocatorHandle.allocate(EpollRecvByteAllocatorHandle.java:75)
	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:777)
	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	java.lang.Thread.run(Thread.java:748)
2020-06-23 19:25:50.750 [ERROR] [reactor-http-epoll-2] [io.netty.util.ResourceLeakDetector:320] LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records:
Created at:
	io.netty.buffer.SimpleLeakAwareByteBuf.unwrappedDerived(SimpleLeakAwareByteBuf.java:143)
	io.netty.buffer.SimpleLeakAwareByteBuf.readRetainedSlice(SimpleLeakAwareByteBuf.java:67)
	io.netty.handler.codec.http.HttpObjectDecoder.decode(HttpObjectDecoder.java:292)
	io.netty.handler.codec.http.HttpServerCodec$HttpServerRequestDecoder.decode(HttpServerCodec.java:103)
	io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	java.lang.Thread.run(Thread.java:748)`

**Comment by violetagg** [comment] 2020-06-24 08:27
@itzikiusa Please run with `-Dio.netty.leakDetectionLevel=` and either `logging.level.reactor.netty=debug` or `logging.level.reactor.netty.channel.FluxReceive=debug` so that we will be able to see more information where exactly the problems appears.

**Comment by itzikiusa** [comment] 2020-06-24 09:08
will add this options and try to reproduce

**Comment by rstoyanchev** [comment] 2020-06-24 10:42
If you could also please use Spring Framework 5.2.8 snapshots as well to see if it helps.

**Comment by AndreasKl** [comment] 2020-06-24 12:27
Today we rolled back our cloud gateway dependency update due to a native memory leak (resulting in OOM kills). The working version was  Spring Cloud Gateway 2.2.2 with reactor-netty 0.9.7 when we switched to Spring Cloud Gateway 2.2.3 with reactor-netty 0.9.8 the pattern below started to happen. We will investigate what causes this native buffer leak, but maybe you are aware of a change that could have introduced this:

[memory issue](https://raw.githubusercontent.com/AndreasKl/pictures-and-images/master/Screenshot%20from%202020-06-24%2014-12-41.png "memory leak")

**Comment by itzikiusa** [comment] 2020-06-24 12:33
@AndreasKl 
version 0.9.8.RELEASE had connection leak

**Comment by violetagg** [comment] 2020-07-08 07:04
@itzikiusa I'll close this. If you are able to provide more information we can reopen the issue.

**Comment by itzikiusa** [comment] 2020-07-08 07:12
@violetagg 
the issue did not reoccur till yesterday

this is the stack trace(after adding the requested envars)

```2020-07-07 17:02:19.149 [DEBUG] [reactor-http-epoll-3] [reactor.netty.channel.FluxReceive:254] [id: 0xe0c75a41, L:/172.18.22.15:50582 - R:172.18.22.29/172.18.22.29:9000] Subscribing inbound receiver [pending: 0, cancelled:false, inboundDone: false]
2020-07-07 17:02:19.153 [ERROR] [reactor-http-epoll-3] [io.netty.util.ResourceLeakDetector:320] LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records:
#1:
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:285)
	io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
	io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollRdHupReady(AbstractEpollChannel.java:442)
	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:482)
	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	java.lang.Thread.run(Thread.java:748)
#2:
	io.netty.buffer.AdvancedLeakAwareByteBuf.forEachByte(AdvancedLeakAwareByteBuf.java:670)
	io.netty.handler.codec.http.HttpObjectDecoder$HeaderParser.parse(HttpObjectDecoder.java:872)
	io.netty.handler.codec.http.HttpObjectDecoder.readTrailingHeaders(HttpObjectDecoder.java:660)
	io.netty.handler.codec.http.HttpObjectDecoder.decode(HttpObjectDecoder.java:357)
	io.netty.handler.codec.http.HttpClientCodec$Decoder.decode(HttpClientCodec.java:202)
	io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
	io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollRdHupReady(AbstractEpollChannel.java:442)
	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:482)
	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	java.lang.Thread.run(Thread.java:748)
#3:
	io.netty.buffer.AdvancedLeakAwareByteBuf.forEachByte(AdvancedLeakAwareByteBuf.java:670)
	io.netty.handler.codec.http.HttpObjectDecoder$HeaderParser.parse(HttpObjectDecoder.java:872)
	io.netty.handler.codec.http.HttpObjectDecoder$LineParser.parse(HttpObjectDecoder.java:928)
	io.netty.handler.codec.http.HttpObjectDecoder.decode(HttpObjectDecoder.java:309)
	io.netty.handler.codec.http.HttpClientCodec$Decoder.decode(HttpClientCodec.java:202)
	io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
	io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollRdHupReady(AbstractEpollChannel.java:442)
	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:482)
	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	java.lang.Thread.run(Thread.java:748)
#4:
	Hint: 'reactor.left.httpCodec' will handle the message from this point.
	io.netty.channel.DefaultChannelPipeline.touch(DefaultChannelPipeline.java:116)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
	io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollRdHupReady(AbstractEpollChannel.java:442)
	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:482)
	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	java.lang.Thread.run(Thread.java:748)
#5:
	Hint: 'DefaultChannelPipeline$HeadContext#0' will handle the message from this point.
	io.netty.channel.DefaultChannelPipeline.touch(DefaultChannelPipeline.java:116)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
	io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollRdHupReady(AbstractEpollChannel.java:442)
	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:482)
	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	java.lang.Thread.run(Thread.java:748)
Created at:
	io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:363)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
	io.netty.channel.unix.PreferredDirectByteBufAllocator.ioBuffer(PreferredDirectByteBufAllocator.java:53)
	io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
	io.netty.channel.epoll.EpollRecvByteAllocatorHandle.allocate(EpollRecvByteAllocatorHandle.java:75)
	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:777)
	io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollRdHupReady(AbstractEpollChannel.java:442)
	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:482)
	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	java.lang.Thread.run(Thread.java:748)
: 4 leak records were discarded because the leak record count is targeted to 4. Use system property io.netty.leakDetection.targetRecords to increase the limit.
2020-07-07 17:02:20.252 [DEBUG] [reactor-http-epoll-3] [reactor.netty.channel.FluxReceive:254] [id: 0xfe1286c2, L:/172.18.22.15:9000 - R:/172.18.61.149:47806] Subscribing inbound receiver [pending: 0, cancelled:false, inboundDone: false]
2020-07-07 17:02:20.260 [DEBUG] [reactor-http-epoll-3] [reactor.netty.channel.FluxReceive:254] [id: 0x53a0aa3f, L:/172.18.22.15:47140 - R:172.18.20.27/172.18.20.27:9000] Subscribing inbound receiver [pending: 0, cancelled:false, inbo`

**Comment by violetagg** [comment] 2020-07-08 07:19
@itzikiusa And the versions for the components? (Reactor Netty/Netty, Spring Framework)
Also do you have more stacks because in this stack I see only Netty code.
You run with `-Dio.netty.leakDetectionLevel=paranoid` and `logging.level.reactor.netty=debug`, don't you?

**Comment by itzikiusa** [comment] 2020-07-08 07:22
@violetagg 
Spring boot version - 2.3.1.RELEASE
reactor-netty version - 0.9.9.RELEASE

this are the envars added -
```-Dio.netty.leakDetectionLevel=advanced -Dlogging.level.reactor.netty.channel.FluxReceive=debug`

**Comment by violetagg** [comment] 2020-07-08 07:26
@itzikiusa OK and is there some other stacks in the logs?

**Comment by itzikiusa** [comment] 2020-07-08 07:32
@violetagg no, around it there are only other incoming requests debug, like this:
```2020-07-07 17:02:20.252 [DEBUG] [reactor-http-epoll-3] [reactor.netty.channel.FluxReceive:254] [id: 0xfe1286c2, L:/172.18.22.15:9000 - R:/172.18.61.149:47806] Subscribing inbound receiver [pending: 0, cancelled:false, inboundDone: false]
`

**Comment by violetagg** [comment] 2020-07-08 07:42
@itzikiusa Then can you share at least more details about your scenario. You write that the error appears in scenario with uploading an image?

**Comment by itzikiusa** [comment] 2020-07-08 08:24
As far as i can see, this error came from simple GET request, not related to image upload
this is the request which came to server:
```[07/Jul/2020:17:02:19 +0000] "GET /games/koala/1.0.0/blocked/country/57/80100167/BE/UNKNOWN HTTP/1.1" 200 19 "-" "Apache-HttpClient/4.5.6 (Java/1.8.0_252)" 8ms`

**Comment by violetagg** [comment] 2020-07-09 18:41
@itzikiusa In the stack above I do not see Reactor Netty classes. This GET request above does not give much information as I don't have your application and cannot try to reproduce the problem or at least understand the scenario.

Either try to create some simple reproducible scenario or try to describe exactly what your application is doing.

**Comment by itzikiusa** [comment] 2020-07-10 19:14
it there any other log i can add to view the full trace?

**Comment by violetagg** [comment] 2020-07-13 13:14
@itzikiusa You already have this `-Dio.netty.leakDetectionLevel=advanced` `-Dlogging.level.reactor.netty.channel.FluxReceive=debug` and there is no Reactor Netty code in the stack.
I do not claim that the problem is not in Reactor Netty, but in order to proceed with the investigation we need somehow to try to reproduce this.

**Comment by violetagg** [comment] 2020-07-27 07:53
@itzikiusa I'm closing this. If there is more information how this can be reproduced we can reopen the issue.

**Closed by violetagg** 2020-07-27 07:53 UTC
Labels: for/user-attention, type/bug
