### ISSUE TITLE
HTTP client unable to specify which IP to bind to, what should I do?

### ISSUE THREAD

**Issue by weiyouren** [reactor/reactor-netty#3011] opened 2024-01-02 16:33 UTC
## Expected Behavior

bind network interface to http client

## Actual Behavior

i wan to bind network interface to http client, but it not work

## Steps to Reproduce

```java
public static WebClient getWebClient(String name) {
        var provider = ConnectionProvider
                .builder(name)
                .maxConnections(4096)
                .pendingAcquireMaxCount(4096)
                //.pendingAcquireTimeout(Duration.ofSeconds(60))
                .maxIdleTime(Duration.ofSeconds(30))
                //.maxLifeTime(Duration.ofMinutes(30))
                .evictInBackground(Duration.ofSeconds(10))
                .lifo()
                .build();

        var connector = new ReactorClientHttpConnector(HttpClient.create(provider)
                .compress(true)
                .bindAddress(() -> new InetSocketAddress("192.168.0.2", 0))//not working,why?
                .protocol(HttpProtocol.H2)
                .secure()
                .keepAlive(true));

        return WebClient.builder()
                .clientConnector(connector)
                .baseUrl(BASE_URL)
                .defaultHeader(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON_VALUE)
                .build();
    }
```

## Your Environment

* Reactor version(s) used: 1.1.10
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`java -version`):java 17.0.8 2023-07-18 LTS
* OS and version (eg. `uname -a`):centos 7 x64

**Comment by weiyouren** [comment] 2024-01-02 16:35
I have two network cards with different IP addresses，192.168.0.2 it's an example

**Comment by violetagg** [comment] 2024-01-03 09:22
@weiyouren Please provide the logs with the problem. I tried to bind the client, where the address was specific for my local machine, and there was no issues with binding.

**Comment by weiyouren** [comment] 2024-01-03 09:34
![1](https://github.com/reactor/reactor-netty/assets/3372167/c3118d8f-1b08-4455-b719-3f7a284c72fe)
I hava four network card，bindAddress(() -> new InetSocketAddress("172.31.108.179", 0))，I bind local address on eth2 ip address，but sending data is from eth3

**Comment by weiyouren** [comment] 2024-01-03 10:58
tcpdump -i eth2
<img width="1034" alt="4" src="https://github.com/reactor/reactor-netty/assets/3372167/0a2c0de8-737a-4049-8089-44ae2089a7f0">
tcpdump -i eth3
<img width="864" alt="5" src="https://github.com/reactor/reactor-netty/assets/3372167/b58ecd46-2353-43c2-a9ce-b9654c8cbbfe">

**Comment by violetagg** [comment] 2024-01-18 13:37
@weiyouren Can you provide also logs from the execution? You need to enable `wiretap(true)` on the `HttpClient` and also to enable logging for `reactor.netty` logger.

**Comment by violetagg** [comment] 2024-01-18 17:58
I cannot reproduce this issue with my setup.

**Comment by violetagg** [comment] 2024-01-29 13:32
@weiyouren I'm closing this with `cannot reproduce`. We can reopen the issue when you are able to provide the requested information.

**Closed by violetagg** 2024-01-29 13:32 UTC
Labels: type/bug, for/user-attention, status/cannot-reproduce
