### ISSUE TITLE
[Android] java.net.UnknownHostException after upgrading from v0.9.10.RELEASE to v1.0.2 

### ISSUE THREAD

**Issue by fbaierl** [reactor/reactor-netty#1447] opened 2020-12-29 14:44 UTC
I know that Android is not officially supported by this library, but I thought I'd report this error nevertheless. Basically, after upgrading reactor-netty from version 0.9.10.RELEASE to version 1.0.2, I am getting the following error message:

`java.net.UnknownHostException: failed to resolve 'api.jikan.moe' after 4 queries`

This only happens on my Android device and **does not happen during unit tests started directly from the IDE** (where everything works as expected and the call is correctly answered), which makes me believe this might be an Android compatibility issue.

## Steps to Reproduce

I am using the [reactive-jikan](https://github.com/SandroHc/reactive-jikan) library to make some API calls to the [JIKAN API](https://jikan.moe/) like this:

```java
    private final Jikan _jikan = new Jikan();

    // ... 

    public Optional<Schedule> getWeeklySchedule(){
        try {
            return Optional.ofNullable(_jikan.query().schedule()
                    .execute()
                    .doOnError(e -> Log.e(TAG, "Error loading weekly schedule." + e.toString()))
                    .block());
        } catch(Exception e){
            Log.e(TAG, "Unable to load weekly schedule.", e);
            return Optional.empty();
        }
    }
```

* JVM version (`java -version`): 1.8
* Device: Samsung Galaxy Note 10 Lite running Android 10

**Comment by violetagg** [comment] 2021-01-04 09:36
@fbaierl  Can you provide some reproducible example?
As a workaround you can switch to the blocking JVM built-in resolver. See here
https://projectreactor.io/docs/netty/snapshot/reference/index.html#_host_name_resolution_2

**Comment by violetagg** [comment] 2021-01-18 08:16
@fbaierl I'm closing this. If you can provide a reproducible example we can reopen it.

**Closed by violetagg** 2021-01-18 08:16 UTC
Labels: status/cannot-reproduce, type/bug

**Comment by fbaierl** [comment] 2021-01-18 09:07
I cannot provide a reproducable example at this moment, since it only seems to happen on Android 7.x devices (works in emulator).

**Comment by Hartigan** [comment] 2022-10-18 11:13
Hello, I reproduced problem and find out root cause.

Environment:
1. IPv4 network and android device with IPv6 support. Loopback network interface has 2 ips: IPv6 loobback address and IPv4 loopback address. Order is important.
2. `LOCALHOST` is IPv6 addr according this code: https://github.com/netty/netty/blob/netty-4.1.54.Final/common/src/main/java/io/netty/util/NetUtil.java#L146
3. Netty dns resolver select  IPv6 dns addresses according this code: https://github.com/netty/netty/blob/646934ef0abe9c2c0934ca24dfb66b7018a284d0/resolver-dns/src/main/java/io/netty/resolver/dns/DefaultDnsServerAddressStreamProvider.java#L87 
4. Therefore, `reactor-netty` trying to make dns request to IPv6 address on IPv4 network(SocketException: Network unreachable).

Workaround: pass custom `DnsServerAddressStreamProvider` with correct DNS servers.

**Comment by violetagg** [comment] 2022-10-18 14:02
@Hartigan I would recommend to upgrade. You might miss the fix for this issue #1568.

**Comment by Hartigan** [comment] 2022-10-18 14:34
@violetagg I reproduce it on `1.0.24` version. Netty uses only IPv4 or only IPv6 DNS servers on Android according to this code: https://github.com/netty/netty/blob/646934ef0abe9c2c0934ca24dfb66b7018a284d0/resolver-dns/src/main/java/io/netty/resolver/dns/DefaultDnsServerAddressStreamProvider.java#L87

Because `defaultNameServers` is empty for android devices

**Comment by violetagg** [comment] 2022-10-19 10:45
@Hartigan what happens if you set `-Djava.net.preferIPv6Addresses` and `-Djava.net.preferIPv4Stack` according to your environment?

**Comment by Hartigan** [comment] 2022-10-19 15:43
@violetagg  I'm not sure what I can do it  on Android. I tried use `System.setProperty("java.net.preferIPv4Stack", "true")` in static constructor, but `DefaultDnsServerAddressStreamProvider` can be inited before. I compiled library with IPv4 and IPv6 dns servers and it works. Also mobile devices with Android has dynamic network conditions: network can be changed from LTE with IPv6 network to Wi-Fi with IPv4 network. Therefore, I think library shouldn't force only one type of IPs by default based on localhost network interface

**Comment by violetagg** [comment] 2022-10-19 18:11
@Hartigan What is your proposal for Reactor Netty in order to be able to configure the the `DefaultDnsServerAddressStreamProvider`?

**Comment by Hartigan** [comment] 2022-10-21 09:27
@violetagg My proposals:
1. Make errors with dns more detailed: users will be able to quickly understand what the problem is, and they can create their own implementations of `DnsServerAddressStreamProvider`.
2. Update documentation for that case: I understand that there is no official support for android. But android really lacks asynchronous clients with non-blocking implementation. Popular http clients on android has asynchronous api, but they creates new threads per concurrent connections.
3. Maybe you can add a simple implementation with Google/Cloudflare DNS addresses or with addresses from constructor.

**Comment by violetagg** [comment] 2022-10-21 09:41
@Hartigan That's great proposals but I think they are more appropriate for Netty project as Reactor Netty only uses the functionality provided by Netty. What do you think?
