### ISSUE TITLE
reactor netty 0.9.10.RELEASE http-server hangs

### ISSUE THREAD

**Issue by chowtin** [reactor/reactor-netty#1363] opened 2020-11-04 09:00 UTC
reactor-netty http-server stop sending response to client.

Http-server is based on spring-cloud-gateway 2.2.4.RELEASE.
request is forward to one controller in-process.

Client side, implemented in C++.
Send thousands of message to http-server via a single TCP Connection 

## Expected Behavior

http-server should write all response to the wire instead of keeping response in memory.

## Actual Behavior

After http-server send back some responses, it stops writing response.
but from reactor-netty log, it shows response is kept in http-server side not sending those data out.

### Logs
2020-11-04 16:44:51,700 DEBUG r.n.h.s.HttpServer [reactor-http-nio-4] [id: 0xc36d50c0, L:/10.10.112.20:6060 - R:/10.10.112.65:52078] READ: 7B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 2e 32 30 0d 0a 0d 0a                            |.20....         |
+--------+-------------------------------------------------+----------------+
2020-11-04 16:44:51,701 DEBUG r.n.h.s.HttpServerOperations [reactor-http-nio-4] [id: 0xc36d50c0, L:/10.10.112.20:6060 - R:/10.10.112.65:52078] Increasing pending responses, now 5177
2020-11-04 16:44:51,701 DEBUG r.n.h.s.HttpServerOperations [reactor-http-nio-4] [id: 0xc36d50c0, L:/10.10.112.20:6060 - R:/10.10.112.65:52078] Buffering pipelined HTTP request, pending response count: 5177, queue: 10350
2020-11-04 16:44:51,701 DEBUG r.n.h.s.HttpServerOperations [reactor-http-nio-4] [id: 0xc36d50c0, L:/10.10.112.20:6060 - R:/10.10.112.65:52078] Buffering pipelined HTTP content, pending response count: 5177, pending pipeline:10351
2020-11-04 16:44:51,701 DEBUG r.n.h.s.HttpServer [reactor-http-nio-4] [id: 0xc36d50c0, L:/10.10.112.20:6060 - R:/10.10.112.65:52078] READ COMPLETE
2020-11-04 16:44:52,626 DEBUG r.n.h.s.HttpServer [reactor-http-nio-4] [id: 0xc36d50c0, L:/10.10.112.20:6060 - R:/10.10.112.65:52078] READ: 176B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 47 45 54 20 2f 74 6f 6b 65 6e 73 2f 70 69 6e 67 |GET /test/ping|
|00000010| 20 48 54 54 50 2f 31 2e 31 0d 0a 55 73 65 72 2d | HTTP/1.1..User-|
|00000020| 41 67 65 6e 74 3a 20 42 6f 6f 73 74 2e 42 65 61 |Agent: Boost.Bea|
|00000030| 73 74 2f 32 37 37 0d 0a 78 2d 70 68 65 6d 65 78 |st/277..x-testabc|
|00000040| 2d 72 65 71 75 65 73 74 2d 74 72 61 63 69 6e 67 |-request-tracing|
|00000050| 3a 20 30 0d 0a 78 2d 70 68 65 6d 65 78 2d 72 65 |: 0..x-testabc-re|
|00000060| 71 75 65 73 74 2d 74 72 61 63 69 6e 67 32 3a 20 |quest-tracing2: |
|00000070| 31 35 36 0d 0a 43 6f 6e 6e 65 63 74 69 6f 6e 3a |156..Connection:|
|00000080| 20 6b 65 65 70 2d 61 6c 69 76 65 0d 0a 41 63 63 | keep-alive..Acc|
|00000090| 65 70 74 3a 20 2a 2f 2a 0d 0a 48 4f 53 54 3a 20 |ept: */*..HOST: |
|000000a0| 31 30 2e 31 30 2e 31 31 32 2e 32 30 0d 0a 0d 0a |10.10.112.20....|
+--------+-------------------------------------------------+----------------+
2020-11-04 16:44:52,626 DEBUG r.n.h.s.HttpServerOperations [reactor-http-nio-4] [id: 0xc36d50c0, L:/10.10.112.20:6060 - R:/10.10.112.65:52078] Increasing pending responses, now 5178
2020-11-04 16:44:52,626 DEBUG r.n.h.s.HttpServerOperations [reactor-http-nio-4] [id: 0xc36d50c0, L:/10.10.112.20:6060 - R:/10.10.112.65:52078] Buffering pipelined HTTP request, pending response count: 5178, queue: 10352
2020-11-04 16:44:52,626 DEBUG r.n.h.s.HttpServerOperations [reactor-http-nio-4] [id: 0xc36d50c0, L:/10.10.112.20:6060 - R:/10.10.112.65:52078] Buffering pipelined HTTP content, pending response count: 5178, pending pipeline:10353
2020-11-04 16:44:52,626 DEBUG r.n.h.s.HttpServer [reactor-http-nio-4] [id: 0xc36d50c0, L:/10.10.112.20:6060 - R:/10.10.112.65:52078] READ COMPLETE

## Steps to Reproduce

send many thousands of http-request via a single tcp-connection to http-server.

```java
@Test
public void repoCase() {

}
```

## Your Environment

* Reactor version(s) used: 0.9.10.RELEASE
* Other relevant libraries versions (eg. `netty`, ...):  4.1.51.Final
* JVM version (`java -version`): 1.8.0_221
* OS and version (eg. `uname -a`): MacOs Catalina 10.5.2

Same issue on linux server

**Comment by violetagg** [comment] 2020-11-04 09:09
@chowtin Please provide a reproducible example.

**Comment by violetagg** [comment] 2020-11-08 10:06
@chowtin I found a regression in 0.9.10.RELEASE that can cause hanging.
Will you be able to check this PR #1371?

**Comment by violetagg** [comment] 2020-11-11 10:51
`0.9.14.RELEASE` is available and contains a fix for a problem that might be the cause for this issue.
I'm closing this issue. If it is not fixed we can reopen it.

**Comment by chowtin** [comment] 2020-11-11 12:11
Sure, you can close it now.

After this change, `HttpTrafficHandler::run` can be called, thus `pipeplined` request is processed.
this issue is resolved per the observation. 

Also tested with netty based single-tcp-connection http-client, Above issue was disappeared.

===

but single-tcp-connection http-client based on cpp-boost still have issues when requests bursts up to 100k. 
I 'm not sure whether this is related.
I'll update this issue once i 've further findings.

Thank you!

**Comment by violetagg** [comment] 2020-11-11 12:28
@chowtin thanks for testing it!

**Comment by chowtin** [comment] 2020-11-24 09:07
Tried 0.9.14.
CPP client send 500k message via a single tcp-connection,  reactor-netty based server acked ~ 36k messages.
All remaining messages are left in memory.  (from heapdump, io.netty.handler.codec.DefaultHeadersImpl keeps increasing.)

I suspect `HttpTrafficHandler::Queue<Object> pipelined` is not processed.

**Comment by violetagg** [comment] 2020-11-24 09:11
Can you provide some reproducible example?

**Comment by violetagg** [comment] 2020-12-11 07:29
@chowtin We will need some reproducible example in order to proceed with the investigation. I'm closing this issue. We can reopen it when we have more information how to reproduce this.

**Closed by violetagg** 2020-12-11 07:29 UTC
Labels: type/bug, warn/regression
