### ISSUE TITLE
Simple HTTP proxy test using Hoverfly hangs forever

### ISSUE THREAD

**Issue by ttiurani** [reactor/reactor-netty#159] opened 2017-09-05 06:05 UTC
### Expected behavior
When using a local Hoverfly proxy to mock a GET request to specific url, expect reactor-netty to return a similar value as when calling the url without the proxy.

### Actual behavior
Calling the actual service works, calling via mocking proxy hangs forever.

### Steps to reproduce
In my fork I have a commit https://github.com/ttiurani/reactor-netty/commit/790b82d59e1b9f31cb5db9c553a3906a5f2cfb9e which includes two tests: the first one tests calling http://time.jsontest.com directly, the second through a Hoverfly proxy that is started before running the test.

To get hoverfly running in the background, first install [hoverfly](https://hoverfly.io/), e.g. on OSX `brew install SpectoLabs/tap/hoverfly`, then, in the root directory run:

```
hoverctl start
hoverctl import src/test/resources/simulation.json
```

To verify that the mock works, use curl:

```
# curl --proxy http://localhost:8500 http://time.jsontest.com
{
   "time": "05:12:54 AM",
   "milliseconds_since_epoch": 1504588374036,
   "date": "09-05-2017"
}
```

After that, try out the test:

```
./gradlew test -i --tests reactor.ipc.netty.http.client.HttpClientTest.hoverflyProxy
```

and watch the test connect t o the proxy but hang forever, whereas the exact same test without the proxy:

```
./gradlew test -i --tests reactor.ipc.netty.http.client.HttpClientTest.jsonTime
```
works fine.

### Reactor Netty version
Current master (0.7.0.BUILD-SNAPSHOT)

### JVM version (e.g. `java -version`)
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

### OS version (e.g. `uname -a`)
Darwin MacBookPro 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

**Comment by violetagg** [comment] 2017-09-08 14:59
Hi,

When trying your test with Hoverfly I'm receiving the following report in the terminal:
```
2017/09/08 17:57:04 [001] WARN: Cannot handshake client time.jsontest.com:80 tls: first record does not look like a TLS handshake
```

I don't know why Hoverfly  expects TLS handshake as the client is configured with sslSupport disabled (this is the default behavior)

I tried your test with a real proxy and it works as expected.

Regards,
Violeta

**Comment by ttiurani** [comment] 2017-09-08 15:33
Thanks @violetagg for your testing! It does seem like something with the SSL requirements is wrong here, but it's hard to tell what component might be the culprit. I have managed to get this exact setup to work with Spring's RestTemplate and it also works with `curl`, so that's why I thought reactor-netty might be the problem.

I have also tried several tricks to get reactor-netty to use SSL but there doesn't seem to be a way to configure SSL for the proxy address – only the main connection. I tried several different likely and unlikely things with SSL config, but none of them worked.

Do you have an idea how I might be able to configure SSL for the proxy handshake?

**Comment by tommysitu** [comment] 2017-09-14 14:52
I think the problem is to do with the `io.netty.handler.proxy.HttpProxyHandler` always use CONNECT method(https://stackoverflow.com/questions/29446945/netty-httpproxyhandler-always-sends-a-connect), and therefore Go proxy (hoverfly is written in Go) tries to do a handshake with an HTTP request and fail.

**Comment by ttiurani** [comment] 2017-09-15 15:24
Thanks @tommysitu ! So if I understand correctly, HttpProxyHandler sending CONNECT without TLS should be fine, and Hoverfly should accept it? If that's the case, then this issue can indeed be closed.

**Comment by mogronalol** [comment] 2017-09-15 15:35
If I understand correctly, when using a proxy, HTTP requests should not use the CONNECT method. CONNECT is specifically for HTTPS tunnelling. Am I missing something?

**Comment by ttiurani** [comment] 2017-09-18 09:52
@mogronalol This issue discusses this design decision by Netty HttpProxyHandler:

https://github.com/netty/netty/issues/3634

It doesn't seem to be a violation of the HTTP protocol to send CONNECT the way Netty does it, and also some (most?) proxy servers do support it. I would say that because Netty is gaining popularity, it might be a good idea for Hoverfly to just support it as well? Even if in some ways Hoverfly might also be kind of justified in assuming TLS after CONNECT?

**Comment by violetagg** [comment] 2017-09-18 12:40
Closed as identified not an issue.

**Closed by violetagg** 2017-09-18 12:40 UTC

**Comment by mogronalol** [comment] 2017-09-19 14:39
Could somebody please direct me to where in the HTTP spec it states that CONNECT is _not_ specifically for HTTPS tunnelling? All I have been able to find is this:

https://tools.ietf.org/html/rfc2616#section-9.9

**Comment by violetagg** [comment] 2017-09-19 14:49
here it is
https://tools.ietf.org/html/rfc7231#section-4.3.6
