### ISSUE TITLE
Apple Silicon triggers Unable to load io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider

### ISSUE THREAD

**Issue by wleese** [reactor/reactor-netty#2440] opened 2022-08-19 12:11 UTC
When running Netty on Apple Silicon, this error is thrown:

```
i.n.r.d.DnsServerAddressStreamProviders  : Unable to load io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider, fallback to system defaults. This may result in incorrect DNS resolutions on MacOS.
```

In https://github.com/netty/netty/issues/11020 the solution is provided. Which is to add this dependency:

```
<dependency>
  <groupId>io.netty</groupId>
  <artifactId>netty-resolver-dns-native-macos</artifactId>
  <classifier>osx-aarch_64</classifier>
</dependency>
```

As a Spring Boot Webflux user, I see that reactor-netty-http pulls in io.netty:netty-resolver-dns-native-macos with classifier osx-x86_64. Reading the pom (https://search.maven.org/artifact/io.projectreactor.netty/reactor-netty-http/1.0.21/jar), this simply happens all the time, whatever arch you're on.

Reading `reactor-netty-core/build.gradle` however, I see some logic that tries to set this dynamically based on architecture.
It would seem however, that when the artifact is published to maven central, this logic is no longer present in the pom.

## Expected Behavior

Reactor-netty-http when included as a dependency in another project on a Apple Silicon machine, should pull in io.netty:netty-resolver-dns-native-macos with classifier osx-aarch_64.

## Actual Behavior

reactor-netty-http pulls in io.netty:netty-resolver-dns-native-macos with classifier osx-x86_64, no matter the actual architecture that's in use.

## Steps to Reproduce

The issue https://github.com/netty/netty/issues/11020 provides a repository and reproduction steps 

## Possible Solution

Include io.netty:netty-resolver-dns-native-macos both with classifier osx-x86_64 and osx-aarch_64.
It seems that including osx-x86_64 on an m1 doesn't do any harm, so I'm (possibly wrongly) assuming the reverse is also fine.

## Your Environment

Apple Silicon

* Reactor version(s) used: 1.0.21
* Other relevant libraries versions (eg. `netty`, ...): io.netty:netty-resolver-dns-classes-macos:jar:4.1.79.Final
* JVM version (`java -version`): openjdk 17.0.3
* OS and version (eg. `uname -a`): Darwin xxx 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 arm64 arm Darwin

**Comment by gmuth** [comment] 2022-08-19 12:54
I think the logic to choose the architecture should be moved from buildtime to runtime. The jar should include the binaries for both architectures. If java nativ interface supports universal or fat binaries for libraries that would be even better.

**Comment by violetagg** [comment] 2022-08-19 14:43
@wleese We don't want to have transitive dependencies to all arch that might be there in the future. For the current 1.0.x/1.1.x we cannot remove the existing transitive dependency as this will be kind of a backwards incompatible. For version 2.0.x we will remove all dependencies to the natives and leave the users to choose which one they want to use. Wdyt?

**Comment by violetagg** [comment] 2022-08-19 14:50
> I think the logic to choose the architecture should be moved from buildtime to runtime. The jar should include the binaries for both architectures. If java nativ interface supports universal or fat binaries for libraries that would be even better.

@gmuth We are not going to support fat jars. See #1140

**Comment by breun** [comment] 2022-08-23 20:41
Spring Boot developers have concluded in https://github.com/spring-projects/spring-boot/issues/29999 this cannot be handled by Spring Boot.

`reactor-netty-http:1.0.22` has a compile dependency on `netty-resolver-dns-native-macos` with classifier `osx-x86_64`, so using `reactor-netty-http` on an Apple Silicon machine will result in `DnsServerAddressStreamProviders` logging an error message. It looks like this can only be fixed in `reactor-netty-http` itself.

**Comment by violetagg** [comment] 2022-08-25 06:12
I proposed an improvement for the log message and this improvement will be in the next Netty 4.1.80.Final
https://github.com/netty/netty/pull/12732

**Comment by breun** [comment] 2022-08-25 08:28
Is adding a dependency on `netty-resolver-dns-native-macos` with classifier `osx-aarch64` a good workaround for now to avoid this error on an Apple Silicon machine, while also not breaking on x86_64? So, is it ok if both the `osx-x86_64` and `osx-aarch64` native dependencies are present?

Or would you recommend excluding `netty-resolver-dns-native-macos` with classifier `osx-x86_64` and not having any native Netty resolver DNS libs to teams that use both x86_64 and aarch64 Macs?

**Comment by violetagg** [comment] 2022-08-25 08:38
> Is adding a dependency on `netty-resolver-dns-native-macos` with classifier `osx-aarch64` a good workaround for now to avoid this error on an Apple Silicon machine, while also not breaking on x86_64? So, is it ok if both the `osx-x86_64` and `osx-aarch64` native dependencies are present?

Having in mind the Netty issue - it seems that there is no need to exclude the dependency with `x86_64`

> 
> Or would you recommend excluding `netty-resolver-dns-native-macos` with classifier `osx-x86_64` and not having any native Netty resolver DNS libs to teams that use both x86_64 and aarch64 Macs?

Fo build time you can always specify the correct classifier. For production I would say specify only the one that is needed.

**Comment by breun** [comment] 2022-08-25 08:58
We're a team with developers with both x86_64 and aarch64 Macs. I guess we could exclude the `osx-x86_64` dependency and add Maven profiles in our projects that add either the `osx-x86_64` or `osx-aarch64` dependency automatically depending on the OS and CPU architecture. However, if adding the `osx-aarch64` dependency by default doesn't cause issues that could be a non-breaking fix in `reactor-netty-http` 1.x, right? Would you consider that? For `reactor-netty-http` 2.x the default dependencies on native libs could be removed.

**Comment by violetagg** [comment] 2022-08-25 09:01
> We're a team with developers with both x86_64 and aarch64 Macs. I guess we could exclude the `osx-x86_64` dependency and add Maven profiles in our projects that add either the `osx-x86_64` or `osx-aarch64` dependency automatically depending on the OS and CPU architecture. However, if adding the `osx-aarch64` dependency by default doesn't cause issues that could be a non-breaking fix in `reactor-netty-http` 1.x, right? Would you consider that? For `reactor-netty-http` 2.x the default dependencies on native libs could be removed.

Please consider developers with Linux and Windows where these transitive dependencies are not needed. We had in the past request for excluding several transitive dependencies.

**Comment by breun** [comment] 2022-08-25 09:17
> Please consider developers with Linux and Windows where these transitive dependencies are not needed. We had in the past requests for excluding several transitive dependencies.

I did consider them, but as far as I can see adding the `osx-aarch_64` dependency to fix this error in `reactor-netty-http` 1.x for Apple Silicon users shouldn't affect non-macOS users, except for adding a 18 KB JAR with a single `jnilib` file, like what's already present for Intel Mac users.

**Comment by violetagg** [comment] 2022-08-25 09:47
Some of our users have strong requirements to not have unnecessary transitive dependencies so we are not going to add this additional dependency.

**Closed** 2022-08-25 11:59 UTC
Labels: type/enhancement

**Comment by shivrajgodle** [comment] 2024-03-25 18:47
ERROR 2481 --- [API-GATEWAY] [ender@6e0b642c}] [                                                 ] i.n.r.d.DnsServerAddressStreamProviders  : Unable to load io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider, fallback to system defaults. This may result in incorrect DNS resolutions on MacOS. Check whether you have a dependency on 'io.netty:netty-resolver-dns-native-macos'. Use DEBUG level to see the full stack: java.lang.UnsatisfiedLinkError: failed to load the required native library 

Getting the above error when i am using Spring Reactive Web dependancy on my spring boot microservice to create API-GATEWAY. I am using it on Macbook air M1 laptop. tried adding the following dependancy and other possible solutions like creating profile but it is not fixing my issue.  
<dependency>
  <groupId>io.netty</groupId>
  <artifactId>netty-resolver-dns-native-macos</artifactId>
  <classifier>osx-aarch_64</classifier>
</dependency> 

Please suggest me ,  how i can resolve this issue.

**Comment by violetagg** [comment] 2024-03-25 19:14
@shivrajgodle Please provide reproducible example. I cannot reproduce this when I add a dependency.

**Comment by shivrajgodle** [comment] 2024-03-26 04:07
@violetagg this is my project repo https://github.com/shivrajgodle/DCB-Microservices . in that there is a 'NewCloudGateway' service. in that i have used the Spring Reactive Web dependancy. 

Steps to Run this microservice. 

1. Create 3 databases in mysql as productdb , orderdb , paymentdb. 
2. Start all the services in the following manner check the video (video link:- https://drive.google.com/file/d/1q0r7m09bTn9uZYvXeT9-r0yQ-jsWqKom/view)
3. Use postman to call the api’s as shown in the video. (Video link:- https://drive.google.com/file/d/1IHKyWd7OQG5oJHW1LhAnl76vgJkTRpSN/view)

Now after calling api using API-GATEWAY port 9090 (http://localhost:9090/order/204). I am getting error mentioned previously. You can check the error in the video.

**Comment by murphy85** [comment] 2024-07-23 10:55
> Some of our users have strong requirements to not have unnecessary transitive dependencies so we are not going to add this additional dependency.

It depends on the individual setup. For me, the x86 dependency is unneccessary. For Linux users both are not needed. So ... maybe you better should include both or remove both to follow your explanation :-) In future there will not be any x86 macs anymore... I think there will be a time where you maybe need to think about switching x86 to aarch64.

**Comment by violetagg** [comment] 2024-07-23 11:09
@murphy85 yes see https://github.com/reactor/reactor-netty/issues/2440#issuecomment-1226819991, we removed the dependency for Reactor Netty version 2, unfortunately we cannot remove it for version 1 as this will be incompatible change.
