### ISSUE TITLE
Returning Mono.empty causes controller to halt

### ISSUE THREAD

**Issue by bazusaladra** [reactor/reactor-netty#518] opened 2018-11-21 09:23 UTC
The following code used to work on SpringBoot 2.0.2
```
    @GetMapping(path = "search")
    public Mono<String> search(@RequestParam(value = "query") String query) {
        if (Objects.isNull(query) || query.isEmpty()) {
            return Mono.empty();
        }
        return Mono.just("result: " + query);
    }
```
After upgrading to SpringBoot 2.1.0 calling
```
String actualEmptyResult = restTemplate.getForObject("/api/search?query=", String.class);
```
causes any subsequent requests to this endpoint to be stalled.
Please check out test `org.springtest.EmptyMonoFailureTest#testMono` in repository https://github.com/bazusaladra/spring-mono-test.
SpringBoot team advised this issue may be related to Reactor Netty: https://github.com/spring-projects/spring-boot/issues/15214

**Comment by rstoyanchev** [comment] 2018-11-21 13:35
This looks like the same issue as https://jira.spring.io/browse/SPR-17506. The fix on the WebFlux side, was to call `response.setComplete()` which completes without writing. Nevertheless there is a likely issue in Reactor Netty where writing with `Mono.empty()` never completes.

**Comment by bclozel** [comment] 2018-12-12 15:21
FYI I can't reproduce this issue anymore with Spring Boot 2.1.1.RELEASE, i.e. reactor netty 0.8.3.RELEASE (I can reproduce it with 2.1.0.RELEASE, i.e. 0.8.2.RELEASE).

**Comment by violetagg** [comment] 2018-12-12 15:49
@bclozel try with spring framework 5.1.2

**Comment by bclozel** [comment] 2018-12-13 10:17
You're right @violetagg, this was fixed in https://github.com/spring-projects/spring-framework/commit/abf9ce8a34

**Comment by rstoyanchev** [comment] 2018-12-18 20:06
This has been fixed in the Spring Framework. See https://jira.spring.io/browse/SPR-17609.

**Closed as completed** 2018-12-18 20:27 UTC
Labels: for/springframework

**Comment by giriganapathy** [comment] 2019-06-08 17:59
Hello Team,

I am new to Flux, and i am streaming the file using Flux, however, my subsequent requests from browser is getting stuck, and here is my code:

@RequestMapping (value="/downloadReactive", produces=MediaType.TEXT_EVENT_STREAM_VALUE)
	public Flux<DataBuffer> downloadReactiveWay(ServerHttpRequest  request, ServerHttpResponse response) throws Exception {
		
		Flux<DataBuffer> flux = null;		
		UrlResource urlResource = new UrlResource(FILE1);
		long totalSize = urlResource.contentLength();
		
		response.getHeaders().add("Content-Type", MediaType.APPLICATION_OCTET_STREAM_VALUE);
		response.getHeaders().add("Content-Disposition", "attachment; filename=\"app\"");		
		response.getHeaders().add("Content-Length", String.valueOf(totalSize));
		
		
		flux = DataBufferUtils.read(urlResource, new DefaultDataBufferFactory(), 1024);
		//https://github.com/spring-projects/spring-framework/commit/abf9ce8a34
		flux.switchIfEmpty(Flux.defer(()->{
			response.getHeaders().setContentLength(0);
			return response.setComplete().then(Mono.empty());
		}));
		
		
		return flux;		
	}

POM.xml:
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.1.5.RELEASE</version>
		<relativePath/> 
	</parent>
	<groupId>com.reactive</groupId>
	<artifactId>download_server</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>download_server</name>
	<description>Demo project for Spring Boot</description>

	<properties>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.projectreactor</groupId>
			<artifactId>reactor-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>

I am stuck here, It would be great, if someone shares the solution.
Thanks.

**Comment by giriganapathy** [comment] 2019-06-08 18:48
My issue is exactly same (Spring FrameworkSPR-17506).  Your quick reply is highly appreciated.
