### ISSUE TITLE
Connection prematurely closed BEFORE response

### ISSUE THREAD

**Issue by martinkrc** [reactor/reactor-netty#1296] opened 2020-08-31 12:06 UTC
We're experiencing the "Connections prematurely closed" error frequently in production - most of communication succeeds but some portion of requests fails with the mentioned error. 

## Expected Behavior
When a connection is successfully used to exchange request/response with the server, Reactor/Netty should not cause failures.

## Actual Behavior
As the situation appears to me, sometimes the server side initiates connection closing somewhere around the moment when the client acquires the pooled channel connection, but the connection is still successfully (?) used for request+response and closed at the end, however Reactor/Netty produces "Connection prematurely closed BEFORE response".

Observing from the logs, this is the rough process:
- Client creates a new connection with the server
- Client sends an HTTP request
- Client receives a response
- Client releases the channel (for later usage)
- Client acquires the channel for a new request
- (as per tcpdump) Client receives FIN segment from the server, meaning that the server closed the connection
- Client sends an HTTP request via the channel
- Client receives a response
- (as per tcpdump) Client closes its side of the connection, sending FIN segment to the server
- Client fails with "Connection prematurely closed BEFORE response"

Connection log:
![connection-lifecycle](https://user-images.githubusercontent.com/40795915/91717061-15fe6400-eb91-11ea-8ef5-96a3dd5341ed.png)

TCP dump:
![tcpdump](https://user-images.githubusercontent.com/40795915/91717086-20206280-eb91-11ea-9d86-135a3a558e83.png)

## Steps to Reproduce
We're unable to reproduce the situation in our test environment, it happens purely in production. However, I believe that the attached log and tcpdump will help with issue resolution from Reactor/Netty side.

This is how we create the Spring WebClient used for communication:
``` java
        SslContext sslContext = NettySslContext.initialize(/*...*/);
        HttpClient httpClient = HttpClient
                .create(ConnectionProvider.elastic(
                        "abcd", Duration.of(5000, ChronoUnit.MILLIS), Duration.of(5000, ChronoUnit.MILLIS))
                )
                .keepAlive(true)
                .secure(spec -> spec.sslContext(sslContext))
                .tcpConfiguration(tcpClient -> tcpClient.option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 15000)
        );

        return WebClient.builder()
                .clientConnector(new ReactorClientHttpConnector(httpClient))
                .baseUrl("https://some.host.cz:4001")
                .exchangeStrategies(exchangeStrategies)
                .build();
```

## Your Environment

* Spring Boot 2.2.7.RELEASE
* Spring Webflux 5.2.6.RELEASE
* Reactor Netty 0.9.7.RELEASE
* Reactor Core 3.3.5.RELEASE
* Netty 4.1.49.Final
* Java SE 1.8.0_161-b12
* Linux

**Comment by violetagg** [comment] 2020-08-31 12:12
@martinkrc Is it possible to try the latest releases?

**Comment by martinkrc** [comment] 2020-08-31 12:26
> @martinkrc Is it possible to try the latest releases?

Do you recommend any specific version? The trouble is that we already did an upgrade (from 0.8.8 to 0.9.7) recently hoping for improvements, but it didn't help and we don't want to waster release effort - the issue can't be reproduced in our test env. Do you see any ticket post 0.9.7 which could be fixing the problem?

**Comment by violetagg** [comment] 2020-09-01 05:52
@martinkrc 
I'm thinking about this
https://github.com/reactor/reactor-netty/issues/1165
https://github.com/reactor/reactor-netty/pull/1183
Although the root cause might be different in your case

The current releases are Reactor Netty 0.9.11, Spring Boot 2.3.3, Spring Framework 5.2.8

**Comment by violetagg** [comment] 2020-09-01 05:57
@martinkrc One additional question: Is there any kind of timeout on the target server?
keep alive timeout/idle timeout etc. that closes the connection when it was not used for a particular time?

**Comment by violetagg** [comment] 2020-09-08 07:05
@martinkrc Were you able to try the latest versions?

**Comment by martinkrc** [comment] 2020-09-08 08:45
@violetagg Need more time, I managed to reproduce the issue somehow locally, but not in a reliable way yet. Next steps would be trying a newer version, but don't have capacity for it at the moment.
Meanwhile we're trying to find out the answer for your additional question - about timeout on the target server.

**Comment by violetagg** [comment] 2020-09-23 07:24
@martinkrc I'm closing this, if you have additional information we can reopen it.

**Closed by violetagg** 2020-09-23 07:24 UTC
Labels: for/user-attention, type/bug
