### ISSUE TITLE
HTTP Client crashes when connection is closed

### ISSUE THREAD

**Issue by acogoluegnes** [reactor/reactor-netty#300] opened 2018-02-28 10:01 UTC
### Expected behavior

Should return the expected response (404 in this case).

### Actual behavior

HTTP Client crashes when connection is closed.

### Steps to reproduce

```
$ wget https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.7.4-rc.4/rabbitmq-server-generic-unix-3.7.4-rc.4.tar.xz
$ tar xf rabbitmq-server-generic-unix-3.7.4-rc.4.tar.xz
$ cd rabbitmq_server-3.7.4-rc.4/sbin
$ ./rabbitmq-plugins enable rabbitmq_management
$ ./rabbitmq-server -detached
```

Then clone https://github.com/acogoluegnes/rabbitmq-management-issue.git and launch the `RabbitMqManagementIssue` class. The last request tries to create a queue in a non-existing virtual host. The client should return a 404 but crashes abruptly instead.

### Reactor Netty version

0.7.4.RELEASE

### JVM version (e.g. `java -version`)

```
$ java -version
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
```

### OS version (e.g. `uname -a`)

```
$ uname -a
Linux acogoluegnes-xps 4.4.0-116-generic #140~14.04.1-Ubuntu SMP Fri Feb 16 09:25:20 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by acogoluegnes** [comment] 2018-02-28 10:08
This issue showed up in our Spring Reactive-based [HTTP client test suite](https://github.com/rabbitmq/hop/blob/a621848c0ed577338f1f839d41bdbbc1d39df9de/src/test/groovy/com/rabbitmq/http/client/ReactiveClientSpec.groovy#L1043-L1054), after [an upgrade of Cowboy](https://github.com/rabbitmq/rabbitmq-server/commit/7de6eabb0664adaa571de782fe0abe8479bf3052), the HTTP server used internally by RabbitMQ.
Here are @essen's thoughts (Cowboy creator):
> what happens is that the test does this PUT with a body using chunked transfer-encoding, and Cowboy reads the request headers, routes the request, gets a response immediately (before it could try reading the body), sends the response, and because it doesn't know what size the body is it decides to close the connection (without sending a connection:close because that decision is made after sending the response, but i'm not sure it would make a difference in this case anyway)
it worked before because Cowboy used to unconditionally skip chunked bodies (even really large ones) but that wasn't a good thing either
still i don't think the client should crash in this case (in HTTP/2 the same situation would result in the stream being reset for reason 'no_error' which is an acceptable way to indicate everything went fine but you don't care about the request body, unfortunately there's no equivalent in HTTP/1.1 other than skipping bodies or closing the connection)…

> the last paragraph of https://tools.ietf.org/html/rfc7230#section-6.5 speaks about this situation in the context of receiving a response with a close, but cowboy is not able to send a connection:close (in this version at least)

**Comment by michaelklishin** [comment] 2018-02-28 13:30
Note that you'll need [a recent version of Erlang](http://www.rabbitmq.com/which-erlang.html) in order to run RabbitMQ. It is also not really necessary to run it with `-detached` as long as you can open another terminal tab ;) If you do, then stopping the server with `./sbin/rabbitmqctl stop` will be necessary when you are done.

**Comment by violetagg** [comment] 2018-02-28 13:39
Hi,

What about handling this scenario on the client side?

```
        System.out.println(client.put("/api/queues/ghost_vhost/test", r -> {
            r.addHeader("Authorization", "Basic Z3Vlc3Q6Z3Vlc3Q=");
            return r.sendString(Mono.just("{\"auto_delete\":false,\"durable\":true,\"arguments\":{}}"));
        })
                .flatMap(res -> {
                    int status = res.status().code();
                    res.dispose();
                    return Mono.just(status);
                })
                .onErrorReturn(t -> "Connection closed prematurely".equals(t.getMessage()), 500)
                .block());
```

Also when you need just the status code without the response body you have to take care to dispose the response in order to release the resources.

Regards,
Violeta

**Comment by acogoluegnes** [comment] 2018-02-28 14:41
@violetagg Thanks for the suggestion, I used your approach in our test suite, it's much cleaner than before.

**Comment by violetagg** [comment] 2018-02-28 15:32
That's great

Just to clarify here: We are not able to return 404 as you suggested because the server closes the connection and we do not know what the problem is. Because of this we return an exception so that user can decide how to interpret it. For example the code above (that I suggested) interpret it as 500 Internal Server Error.

I'm closing the issue.

**Closed by violetagg** 2018-02-28 15:32 UTC
