### ISSUE TITLE
Netty OutOfDirectMemoryError: failed to allocate direct memory

### ISSUE THREAD

**Issue by hamadodene** [reactor/reactor-netty#2061] opened 2022-02-28 16:17 UTC
reactor version: 1.0.15

We are experiencing several OOMs in our production system.
Looking at the direct memory graphs we see that direct memory never seems to decline but always increases.

We have a direct memory allocated of about 14gb. We have 10gb dedicated to a cache (separated from reactor-netty).
We expected that for the netty it would use the remaining , but that the memory management would be handled by the JVM anyway and that it would be released by Netty if there was not enough to allocate more.

Is there a way to better manage direct memory management for netty so that we avoid these OOMs?

Our JVM configuration:

JAVA_OPTS="-XX:+UseG1GC -Xmx6g -Xms6g  -XX:MaxDirectMemorySize=14g

```
Feb 28, 2022 4:58:01 PM reactor.util.Loggers$Slf4JLogger error
SEVERE: [90bde180, L:/10.219.105.156:4089 ! R:/93.34.80.42:13591] onUncaughtException(SimpleConnection{channel=[id: 0x90bde180, L:/10.219.105.156:4089 ! R:/93.34.80.42:13591]})
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 15015608327, max: 15032385536)
        at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:802)
        at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:731)
        at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:648)
        at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:623)
        at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:202)
        at io.netty.buffer.PoolArena.tcacheAllocateSmall(PoolArena.java:172)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:134)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:126)
        at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:395)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:188)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179)
        at io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:116)
        at io.netty.handler.ssl.SslClientHelloHandler.decode(SslClientHelloHandler.java:132)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:404)
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:371)
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:831)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:832)

```

![image](https://user-images.githubusercontent.com/43852233/156018013-79efc584-ceab-401c-bd70-dc2655c4c641.png)

**Comment by hamadodene** [comment] 2022-02-28 16:20
Another note is that we already have a limitation on the use of direct cache (set to 10gb).
During the OOM, we see that the cache was using max 6gb:

![image](https://user-images.githubusercontent.com/43852233/156018882-85cf3cff-e036-4fed-892f-badbc2e3dd1d.png)

**Comment by hamadodene** [comment] 2022-03-01 10:09
Does someone have some info to debug and fix this issue?

**Comment by pderop** [comment] 2022-03-02 14:33
Another thing which I forgot to mention: when buffers are allocated outside of netty event loops, a lot of memory is used because by default, netty uses a thread local cache for all threads. In this case (when buffers may be allocated/released outside of event loops), then setting the following system property to false may reduce memory usage:

-Dio.netty.allocator.useCacheForAllThreads=false

Setting the above property disable thread local caching (see https://github.com/netty/netty/pull/12109)

**Comment by hamadodene** [comment] 2022-03-03 08:45
Thanks @pderop  for the info. the problem occurred in the production environment. We have reverted to the previous version of our application.
We are therefore trying to reproduce the problem in a development environment.
However, we did analyze the dumps that we were able to do. While non-heap memory is not included, we have seen that there are a lot of DefaultChannelHandlerContext: 

![image](https://user-images.githubusercontent.com/43852233/156527261-96fd6a75-39dc-4692-8d14-8ed9c9de4cb6.png)


![image](https://user-images.githubusercontent.com/43852233/156527346-3559c934-2307-4d69-a9c4-b669cafa1bed.png)

The info on use Cache For All Threads sounds very interesting. In fact we see from the graphs a strange curve of the old gen G1:
02/28 is the day we did the update with the package that gave us problems:
![image](https://user-images.githubusercontent.com/43852233/156527933-0fab4ef8-2a7e-45e8-b282-cd689a7ecdd0.png)

We see the same strange curve also in the development of the old gen .. But as there is little load we never went to OOM:

![image](https://user-images.githubusercontent.com/43852233/156528400-a54515ad-7a4d-46e0-8e8b-47327024dc41.png)


The curve is always growing .. And I think it's not normal.
We are trying to set Dio.netty.allocator.useCacheForAllThreads = false in development to see how the curve of the G1 Old gen changes

**Comment by hamadodene** [comment] 2022-03-07 15:10
@pderop 
We have set up the new metrics and we see that reactor netty's direct memory allocator is always growing.
We're trying to figure out if it's a bug on our side.
The system properties to detect the leak detection is not logging anything in our case.
useCache For All Threads = false also did not have a positive impact.

![image](https://user-images.githubusercontent.com/43852233/157060487-818821e7-0917-48fb-9e66-f45ebf4082f7.png)

**Comment by pderop** [comment] 2022-03-10 11:26
Hi @hamadodene ,

so let's summarize:

- using the memory leak detector (from [memory leak faq](https://projectreactor.io/docs/netty/release/reference/index.html#faq.memory-leaks) and [netty Reference counted objects link referenced in our faq](https://github.com/netty/netty/wiki/Reference-counted-objects)), you did not observe any traces (I assume that you used the PARANOID leak level detection)
- and using io.netty.allocator.useCacheForAllThreads = false does not help
- using the reactor metrics, you observe that direct used memory is growing

so, at this stage it's still hard to help, because we don't have any ideas of the real use case.

more specifically, we wonder the following:

- can you tell us more about your use case ?
- if the max used direct memory is reached, are you sure it's a memory leak ? i mean, maybe you just need more memory ? 
- what is your dedicated cache (separated from reactor-netty) ?
- is there a way to reproduce the problem without the cache ?
- are you getting the OOM when you are using reactor netty http client or are you running as a server ?
- did you try to use the 1.0.16 reactor-netty version ?

**Comment by hamadodene** [comment] 2022-03-11 15:44
@pderop 

1. can you tell us more about your use case ?
We use reactor netty within our open source Carapace Proxy project. Carapace is a distributed reverse proxy written in java. The repo: https://github.com/diennea/carapaceproxy

2. if the max used direct memory is reached, are you sure it's a memory leak ? i mean, maybe you just need more memory ?
Using leak detection nothing has emerged, so it is likely that it is not a netty-side leak.

3. what is your dedicated cache (separated from reactor-netty) ?
As a cache we use caffeine cache.

4. is there a way to reproduce the problem without the cache ?
On this point, after many investigations we have noticed that we actually have the problem only with the active cache. Which assumes the leak is on the cache side.
We noticed some strange behavior when using retain ().
This is what we do:
```
 return client.request(request.getMethod())
                    .uri(request.getUri())
                    .send(request.getRequestData()) // client request body
                    .response((resp, flux) -> { // endpoint response
                        request.setResponseStatus(resp.status());
                        request.setResponseHeaders(resp.responseHeaders().copy()); // headers from endpoint to client
                        if (cacheReceiver != null && parent.getCache().isCacheable(resp) && cacheReceiver.receivedFromRemote(resp)) {
                            addCachedResponseHeaders(request);
                        } else {
                            cacheReceiver = null;
                        }
                        addCustomResponseHeaders(request, request.getAction().customHeaders);
                        request.setResponseCookies(resp.cookies().values().stream() // cookies from endpoint to client
                                .flatMap(Collection::stream)
                                .collect(Collectors.toList())
                        );
                        return request.sendResponseData(flux.retain().doOnNext(data -> { // response data
                            request.setLastActivity(System.currentTimeMillis());
                            endpointStats.getLastActivity().set(System.currentTimeMillis());
                            if (cacheReceiver != null) {
                                cacheReceiver.receivedFromRemote(data);
                            }
                        }).doOnComplete(() -> parent.getCache().cacheContent(cacheReceiver)));
```
When we do sendResponseData (), at that point if it's a cacheable resource, we need to save the chunk:
```
  if (cacheReceiver != null) {
      cacheReceiver.receivedFromRemote(data);
  }
```
In receivedFromRemote (data) we call an addChunk() function to keep track of the chunks in a list.
Since it is an object that we want not to be automatically deallocated, we make a copy of the original object on which we retain().
However, we noticed that when we released these chunks, they weren't deallocated because the rfCnt was at 2 and calling release passed to 1.
```
 private void addChunk(ByteBuf chunk) {
      chunks.add(chunk.copy().retain());
      if (chunk.isDirect()) {
          directSize += chunk.capacity();
      } else {
          heapSize += chunk.capacity();
      }
  }
```
We have tried to fix this point using retainedDuplicated() instead of copy().retain() and it seems to be working. 
https://github.com/diennea/carapaceproxy/pull/328


We have seen that Netty by default uses all direct memory configured in -XX: MaxDirectMemorySize.
However, having the cache also acting on the same parameter, perhaps we need to find a way to explicitly set a maximum limit for netty. Is there a property that can help us with this?

With the cache we already have a setting that limits the maximum usable direct size. When it has reached the limit, the cache is invalidated and all its objects released.

**Comment by pderop** [comment] 2022-03-11 18:11
hi @hamadodene,

so, i assume here that when the chunk is evicted by the cache, then chunk.release() will be called, right ?

in this case, if you store in the cache a retained copy like:
```
private void addChunk(ByteBuf chunk) {
      chunks.add(chunk.copy().retain());
      ...
}
```
then if I'm correct, I think the chunk can't be released when you call "chunk.release", because you have first copied it, second you have retained it, and that's probably the cause of the memory leak. Doing the following would also resolve the issue I think:
```
private void addChunk(ByteBuf chunk) {
      chunks.add(chunk.copy());
      ...
}
```

now, if you don't need to copy the chunk, then your solution works better: just use retainedDuplicate():

```
private void addChunk(ByteBuf chunk) {
      chunks.add(chunk.retainedDuplicate());
      ...
}
```

Actually, retainedDuplicate() is similar to "duplicate().retain()", and avoid to copy the content of the buffer.

To configure the max size of the netty bytebuf allocator, I think you can adjust some system properties, but there are many, like allocator.chunkSize, io.netty.allocator.smallCacheSize, etc... 
please have a look at [netty PooledByteBufAllocator](https://github.com/netty/netty/blob/4.1/buffer/src/main/java/io/netty/buffer/PooledByteBufAllocator.java#L154-L176),

**Comment by pderop** [comment] 2022-03-11 18:11
I'm closing this issue, please reopen it if necessary ! 
thanks.

**Closed by pderop** 2022-03-11 18:11 UTC
Labels: type/bug, for/user-attention

**Comment by hamadodene** [comment] 2022-03-11 22:16
@pderop 

All clear. The only thing that is not very clear to me is how to limit the direct used by netty.
That is, if I configure XX-MaxDirectMemorySize = 14g and I want netty to use a maximum of 7gb, is this possible?
I saw that there is the sys prop io.netty.maxDirectMemory. I'll try to figure out if it's right for us or if I need to set other sys props.

As for doing chunk.copy() only, we noticed this was causing problems. This is because making a simple copy without retain() does not disable the cleaner. So it happened that the object was deallocated automatically and we got the exception: IllegalReferenceCountException: refCnt: 0, decrement: 1.
when we tried to release the object calling release().

Thanks for all your info. They have been really useful to us. If you have more info on point 1 it would be great.

**Comment by pderop** [comment] 2022-03-15 09:30
Hi @hamadodene ,

I don't know about your last question, but I double checked the _io.netty.maxDirectMemory_, and indeed, it sounds like this property is what you need: this property seems to take precedence over the MaxDirectMemorySize. So, if you set io.netty.maxDirectMemory, then it will be used instead of the MaxDirectMemorySize.

See [this](https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/internal/PlatformDependent.java#L160-L168): if you use the property, then it will be used instead of MAX_DIRECT_MEMORY, which is initialized with MaxDirectMemorySize (see estimateMaxDirectMemory method).
