### ISSUE TITLE
ServerWebExchange-object.getRequest().getURI().getPort() is returning 80 when an https end point is invoked

### ISSUE THREAD

**Issue by svankamamidi** [reactor/reactor-netty#2788] opened 2023-04-27 10:47 UTC
ServerWebExchange exchange
exchange.getRequest().getURI().getPort() is returning 80 when an https end point is invoked.  I am using via Spring Gateway in Cloud Foundry.

application.yml has 
  forward-headers-strategy: framework

Gateway sent request header includes: x_forwarded_proto:"https"

## Expected Behavior
ServerWebExchange-object.getRequest().getURI().getPort() should return 443.

## Actual Behavior
ServerWebExchange-object.getRequest().getURI().getPort() returning 80

## Steps to Reproduce
My controller is as follows:
```java
@RequestMapping(value = { "/myUri" })
public myController(ServerWebExchange exchange){
  log.info("Port " + exchange.getRequest().getURI().getPort());
}

```

## Your Environment
Cloud Foundry

* Reactor version(s) used:
* Spring boot 2.7.11:
* JVM version (`java -version`): 11
* OS and version (eg. `uname -a`): CF

**Comment by sven-tsi** [comment] 2023-04-27 11:01
we have the same issue. only with spring cloud gateway and only on Cloud Foundry. local everything is fine.

**Comment by pderop** [comment] 2023-04-27 11:37
I will wait for the http request logs, but it would be great if you could test the reactor netty 1.0.32-SNAPSHOT, because we have just merged the PR #2773 for the issue #2771 , and this might be related.

**Comment by svankamamidi** [comment] 2023-04-27 13:18
@pderop I already include the req header entry in my issue description. Sorry my company policy does not allow to use snapshots.

**Comment by Subrhamanya** [comment] 2023-04-27 23:30
@pderop any idea when1.0.32 is gonna release? Our releases are getting blocked by this issue.

**Comment by pderop** [comment] 2023-04-28 07:00
I need a reproducer, because I cannot reproduce this problem.
I have attached my own [reproducer.tgz](https://github.com/reactor/reactor-netty/files/11350752/reproducer.tgz), will you be able to modify it in order to show the problem ? or please provide your own one ?

Now, it is likely that this is the same issue from #2771 (the fix is already merged and will be included in the next Reactor Netty release for the next release is May 9th). So, with the attached reproducer, you will find:

- gateway/ -> the spring cloud gateway, configured with https, on port 443: it will forward requests to localhost:80 in plain http text. the gateway is configured to forward the X-Forwarded-Proto header (see application.yml)
- backend/ -> the backend server listening on port 80 in plain http (not https). the "/print-uri" request will return the URI path, as well as the port number obtained from `exchange.getRequest().getURI().getPort()`. Also, in the application.yml, the `forward-headers-strategy` is configured to `framework`

to test:

1) start the gateway : 
```
cd gateway
mvn clean package
java -jar target/spring-cloud-gateway-0.0.1-SNAPSHOT.jar
```

2) start the backend on the host:
```
cd backend
./gradlew bootRun
```

and type this curl command to the GW:
```
curl -k -v https://localhost/print-uri
```

the curl command will return:
```
URI = https://localhost/print-uri, port=-1
```

So, with forward-headers-strategy=framework, the problem is not reproduced: the request URI does not contain port 80 and `exchange.getRequest().getURI().getPort()` returns -1 but it seems fine, because if I'm correct the contract of the java.net.URI.getPort() method says that -1 is returned in case the port number is not defined in the request URI.


**now, please note the following important thing:**

The problem will be reproduced if you change in the backend application.yml the forward-headers-strategy property to `native`:

1) update backend/src/main/resources/application.yml with forward-headers-strategy: native

2) restart the backend

3) retype the curl command, and you will this time reproduce the problem:

```
URI = https://localhost:80/print-uri, port=80
```

And now, if you update the backend in order to use the patch that is already available in the snapshot repository (reactor-netty 1.0.32-SNAPSHOT), then the problem will be resolved:

1) update backend/build.gradle and uncomment the first two dependencies to 1.0.32-SNAPSHOT snapshot:
```text
dependencies {
	implementation 'io.projectreactor.netty:reactor-netty-core:1.0.32-SNAPSHOT'
	Implementation 'io.projectreactor.netty:reactor-netty-http:1.0.32-SNAPSHOT'
	implementation 'org.springframework.boot:spring-boot-starter-webflux'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'io.projectreactor:reactor-test'
}
```

2) restart the backend

3) and this time, the problem is fixed, and we have the same result as when we use `forward-headers-strategy=framework`:
```
URI = https://localhost/print-uri, port=-1
```

let me know, thanks.

**Comment by svankamamidi** [comment] 2023-05-02 05:42
@pderop I can confirm that 'io.projectreactor.netty:reactor-netty-core:1.0.32-SNAPSHOT'
 and 'io.projectreactor.netty:reactor-netty-http:1.0.32-SNAPSHOT' resolved our issue. Where as setting server.forward-headers-strategy: framework did not addressed all scenario's. Especially ServerWebExchange.getRequest().getURI().getPort() is returning 80 when an https end point is invoked.

**Comment by pderop** [comment] 2023-05-02 09:23
@svankamamidi ,

I'm under the impression that the 1.0.32-SNAPSHOT resolves some of your issues, but not all ? please clarify ?
So, using the patch,  does the `ServerWebExchange.getRequest().getURI().getPort()` still return 80 with `headers-strategy: framework` ? If so, then can you provide:

- an ethereal trace of the http request that is received by your application in CF ?
- the content of your application's `application.yml` ? (you can mask some sensitive informations from it, if necessary).

thank you

**Comment by pderop** [comment] 2023-05-02 11:51
thanks for the clarification.
I'm closing this one as a duplicate for #2773

**Closed by pderop** 2023-05-02 11:51 UTC
Labels: status/duplicate
