### ISSUE TITLE
Default ChannelPool is unbounded, and leaks memory on a per-URL basis

### ISSUE THREAD

**Issue by ccrolf** [reactor/reactor-netty#379] opened 2018-06-29 01:02 UTC
### Expected behavior
Not running out of memory after calling 10k+ different host URLs when using default config

### Actual behavior
Application eventually crashes, as `DefaultPoolResources.channelPools` has grown to over 10k entries. Exacerbated when stack traces are enabled for Monos/Fluxes as each value in the `ConcurrentMap` is ~80kb.

### Workaround
Use:
```kotlin
    HttpClient.create({ opt ->
            //disable pooling, cause it leaks memory on a per-URL basis
            opt.disablePool()
```

### Suggested fixes
1. Make pooling/caching opt-in instead of opt-out
2. Always prefer fixed-size pooling/caching as the default
3. Use weak/soft references for all pooling/caches
4. All of the above

### Steps to reproduce
Use wiremock to call `127.[0-255].[0-255].[0-255]` and watch the `ConcurrentMap` grow until the heap is full.

### Reactor Netty version
0.7.8.RELEASE

### JVM version (e.g. `java -version`)
https://github.com/docker-library/openjdk/blob/a5cc95a14480e9b30c674aa72257f6e4cf032b8d/8/jdk/slim/Dockerfile

### OS version (e.g. `uname -a`)
https://github.com/docker-library/openjdk/blob/a5cc95a14480e9b30c674aa72257f6e4cf032b8d/8/jdk/slim/Dockerfile

**Comment by smaldini** [comment] 2018-06-29 05:06
Good points, I don't think the default should change to no-pooling as the vast majority of use cases seems to target a specific domain. However all your other suggestions (2,3, and 2+3) make totally sense. We should enforce a high upper limit such as 1000, problem being right now we use Netty provided pool facilities which we want to change for 0.8 into our own pooling infrastructure. This will help in adding things like max idle time (which right now is a problem when we limit a pool in some situations). Let's see what can be done for 0.7.x and do better in 0.8.

**Comment by dave-fl** [comment] 2018-08-22 06:49
Is this 10k limit per host or per URL?

**Comment by violetagg** [comment] 2019-11-26 07:38
Just an update here:
For version 0.9.x the connection pool is fixed by default + there is a configuration allowing to setup max idle time for a connection.

**Comment by violetagg** [comment] 2020-01-24 19:29
@ccrolf Can you elaborate more about this

> Not running out of memory after calling 10k+ different host URLs when using default config
> Application eventually crashes, as DefaultPoolResources.channelPools has grown to over 10k entries. Exacerbated when stack traces are enabled for Monos/Fluxes as each value in the ConcurrentMap is ~80kb.

The current implementation (0.9.x) runs by default with:
- 500 max connections per connection pool where a connection pool corresponds to a remote host and NOT URL
- `DefaultPoolResources.channelPools` holds the different connection pools, which means with just 20 different remote hosts and load that keeps every pool to a maximum connections you will achieve 10k connections. Depending on the OS configuration you will achieve `SocketException` sooner than OOM caused by the `DefaultPoolResources.channelPools`.

**Comment by violetagg** [comment] 2020-02-20 17:10
Connection pool configuration per remote host is added #973

**Closed by violetagg** 2020-02-20 17:10 UTC
Labels: type/bug, type/enhancement
