### ISSUE TITLE
[spring cloud gateway] Connection has been closed BEFORE response, while sending request body when uploading large file[16MB,]

### ISSUE THREAD

**Issue by kiwi-field** [reactor/reactor-netty#1062] opened 2020-04-10 13:28 UTC
The connection has been closed before response, while sending request body when uploading large file appears when accessing the upload file interface of the project through spring cloud gateway.

spring boot version:2.0.5.RELEASE
jdk:1.8

my project application.yml
![image](https://user-images.githubusercontent.com/30741355/78994275-3857fc80-7b72-11ea-9c92-99003a0a555c.png)

**Comment by kiwi-field** [comment] 2020-04-10 13:29
if My parameters are set to
Servlet.Multipart.max-file-size:2MB
Servlet.Multipart.max-request-size: 2MB
Connection has been closed before response does not appear

**Comment by kiwi-field** [comment] 2020-04-10 13:31
When my parameter is set to this
Servlet.Multipart.max-file-size:10MB
Servlet.Multipart.max-request-size: 10MB
my upload file size I upload is 16MB，
Connection has been closed before response will appear

**Comment by kiwi-field** [comment] 2020-04-10 13:33
![image](https://user-images.githubusercontent.com/30741355/78994515-dc41a800-7b72-11ea-9f83-f66921e63faf.png)

**Comment by kiwi-field** [comment] 2020-04-10 13:33
![image](https://user-images.githubusercontent.com/30741355/78994542-ef547800-7b72-11ea-88a0-27931a8becf9.png)

**Comment by violetagg** [comment] 2020-04-10 14:50
> spring boot version:2.0.5.RELEASE

This version is too old, please upgrade 
https://github.com/spring-projects/spring-boot/releases/tag/v2.0.5.RELEASE

**Comment by kiwi-field** [comment] 2020-04-11 01:06
Now my microservice version is spring boot version:2.0.5.RELEASE

**Comment by kiwi-field** [comment] 2020-04-11 01:07
It should be a gateway problem

**Comment by kiwi-field** [comment] 2020-04-11 01:34
Do I need to upgrade my gateway and service's spring boot version to 2.2. X

**Comment by violetagg** [comment] 2020-04-11 12:11
@kiwi-field it is better to update both

**Comment by violetagg** [comment] 2020-04-20 14:44
I'm closing this issue, we can reopen it if it is needed.

**Closed by violetagg** 2020-04-20 14:44 UTC
Labels: for/user-attention, type/bug

**Comment by kiwi-field** [comment] 2020-04-21 01:12
ok，thanks

**Comment by ryzencool** [comment] 2020-08-28 02:44
Did you solve this problem? @kiwi-field, I upgrade version to latest, but still throw this exception.

**Comment by qimeinajie** [comment] 2021-01-26 10:03
@kiwi-field I have the same problem, may I ask how to solve it

**Comment by qimeinajie** [comment] 2021-01-26 10:07
@kiwi-field 帅哥帅哥，请问下最后是如何解决的，升级版本就可以了么？我升级到2.2.X之后又有其他的问题

**Comment by qimeinajie** [comment] 2021-01-26 10:15
@violetagg I have the same problem, may I ask how to solve it

**Comment by qimeinajie** [comment] 2021-01-26 10:20
@violetagg The problem is that a client request is content-type multipart/form-data and contains files. When forwarded to an upstream service, the server returns a status code of 400, while Springcloud-gateway returns a status code of 500

**Comment by violetagg** [comment] 2021-01-26 10:21
@qimeinajie Please create a new issue and describe the problem there.

**Comment by jinliang9780** [comment] 2021-09-06 05:59
@kiwi-field 请问你解决了吗?我spring boot更新到2.3.12,spring cloud 2.2.9还是报Connection has been closed BEFORE response, while sending request body

**Comment by maregeo** [comment] 2024-04-26 05:05
@violetagg yes you are right
