### ISSUE TITLE
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer

### ISSUE THREAD

**Issue by rishuzz** [reactor/reactor-netty#1469] opened 2021-01-19 05:19 UTC
**We are using Spring Cloud gateway (Hoxton.SR8) which internally using Netty (0.9.6.RELEASE) 
In commercial environments we are seeing below issue when spring cloud gateway proxying request to target system**

_2021-01-19 05:11:16.803 DEBUG 1 --- [or-http-epoll-2] o.s.c.g.h.RoutePredicateHandlerMapping : Route matched: SG-test-controller
2021-01-19 05:11:16.803 DEBUG 1 --- [or-http-epoll-2] o.s.c.g.h.RoutePredicateHandlerMapping : Mapping [Exchange: GET https://***URL****/test-controller/test/import/] to Route{id='SG-test-controller', uri=http://*******HOST************:8081/, order=3, predicate=Paths: [/test-controller/**], match trailing slash: true, gatewayFilters=[com.test.gateway2.config.filters.GlobalPreFilter@5e05874c, com.test.gateway2.config.filters.JwtCheckFilter@224bff6], metadata={}}
2021-01-19 05:11:16.803 DEBUG 1 --- [or-http-epoll-2] o.s.c.g.h.RoutePredicateHandlerMapping : [0d3a74f8-23] Mapped to org.springframework.cloud.gateway.handler.FilteringWebHandler@507a53b6
2021-01-19 05:11:16.804 DEBUG 1 --- [or-http-epoll-2] o.s.c.g.handler.FilteringWebHandler : Sorted gatewayFilterFactories: [[GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.RemoveCachedBodyFilter@a9c923f}, order = -2147483648], com.ot.gateway.config.filters.GlobalPreFilter@5e05874c, com.ot.gateway.config.filters.JwtCheckFilter@224bff6, [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.AdaptCachedBodyGlobalFilter@17f2e01d}, order = -2147482648], [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.NettyWriteResponseFilter@7f14bdd1}, order = -1], [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.ForwardPathFilter@2abb4810}, order = 0], [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.RouteToRequestUrlFilter@70e966a5}, order = 10000], [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.WebsocketRoutingFilter@1e954b94}, order = 2147483646], [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.NettyRoutingFilter@18c49ecb}, order = 2147483647], [GatewayFilterAdapter{delegate=org.springframework.cloud.gateway.filter.ForwardRoutingFilter@2ac9b75c}, order = 2147483647]]
2021-01-19 05:11:16.804 INFO 1 --- [or-http-epoll-2] c.o.g.config.filters.GlobalPreFilter : SG-GATEWAY:: GlobalPreFilter:: REFERER :: [https://***URL****/supportgrid-portal/]
2021-01-19 05:11:16.804 INFO 1 --- [or-http-epoll-2] c.o.g.config.filters.GlobalPreFilter : SG-GATEWAY:: GlobalPreFilter:: PATH :: /test-controller/test/import/
2021-01-19 05:11:16.804 INFO 1 --- [or-http-epoll-2] c.o.g.config.filters.GlobalPreFilter : SG-GATEWAY:: GlobalPreFilter:: incoming request protocol :: https
2021-01-19 05:11:16.804 INFO 1 --- [or-http-epoll-2] com.ot.gateway.utils.ApplicationHelper : SG-GATEWAY ApplicationHelper request Headers : gateway-redirected-origin , 2021-01-19T05:11:16.804453 , ***URL****
2021-01-19 05:11:16.804 INFO 1 --- [or-http-epoll-2] c.o.g.config.filters.JwtCheckFilter : SG-GATEWAY:: JwtCheckFilter:: Base URL for application :: test-controller
2021-01-19 05:11:17.047 DEBUG 1 --- [or-http-epoll-2] r.netty.http.client.HttpClientConnect : [id: 0x0d10a4ca, L:/*******IP Address ************:43998 - R:*******HOST************/*******IP Address ************:8081] Handler is being applied: {uri=http://*******HOST************:8081/test-controller/test/import/, method=GET}
2021-01-19 05:11:17.049 DEBUG 1 --- [or-http-epoll-2] r.netty.http.client.HttpClientConnect : [id: 0x0d10a4ca, L:/*******IP Address ************:43998 - R:*******HOST************/*******IP Address ************:8081] The connection observed an error, the request will be retried

io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer

2021-01-19 05:11:17.087 DEBUG 1 --- [or-http-epoll-2] r.netty.http.client.HttpClientConnect : [id: 0xb85aee86, L:/*******IP Address ************:44002 - R:*******HOST************/*******IP Address ************:8081] Handler is being applied: {uri=http://*******HOST************:8081/test-controller/test/import/, method=GET}
2021-01-19 05:11:17.089 WARN 1 --- [or-http-epoll-2] r.netty.http.client.HttpClientConnect : [id: 0xb85aee86, L:/*******IP Address ************:44002 - R:*******HOST************/*******IP Address ************:8081] The connection observed an error

io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer

2021-01-19 05:11:17.089 ERROR 1 --- [or-http-epoll-2] o.s.w.s.adapter.HttpWebHandlerAdapter : [0d3a74f8-23] 500 Server Error for HTTP GET "/test-controller/test/import/"

**io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
|_ checkpoint ? org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
|_ checkpoint ? HTTP GET "/test-controller/test/import/" [ExceptionHandlingWebHandler]
Stack trace:_**

**Comment by violetagg** [comment] 2021-01-19 08:13
@rishuzz Reactor Netty 0.9.6.RELEASE is almost a year old. Please upgrade to the latest releases for Spring Gateway/Reactor Netty

**Comment by dandamudi1414** [comment] 2021-01-19 09:50
Hi @violetagg  , 

is there a known bug in this version  **0.9.6.RELEASE** ??

**Comment by violetagg** [comment] 2021-01-19 10:26
@dandamudi1414 We have fixes related to connection closed prematurely although I cannot claim that they will solve the issue above as the report contains only exception and not reproducible scenario.

**Comment by dandamudi1414** [comment] 2021-01-19 10:58
@violetagg  - thanks for the reply and can you please let us know which version having the above fix? Or I need to use latest only and not sure Spring cloud gateway using latest

**Comment by violetagg** [comment] 2021-01-19 11:09
@dandamudi1414 I would recommend to update to the latest Spring Gateway/Spring Boot

**Comment by rishuzz** [comment] 2021-01-20 08:18
@violetagg Thank you for the reply,  We tried upgrading SCG to v2.4.2 and that updated Netty dependencies to :

- **reactor-netty-core** : 1.0.3
- **io.netty** : 3.10.6.FINAL
- **spring-boot-starter-reactor-netty**: 2.4.2

but we are still seeing exactly same error, Do we need upgrade to some specific version of SCG ?

**Comment by violetagg** [comment] 2021-01-20 08:25
@rishuzz

> io.netty : 3.10.6.FINAL

We do not support Netty version 3. Why do you specify this version?

> Do we need upgrade to some specific version of SCG?

It is always better to use the dependency specified by SCG instead of updating only some dependencies

**Comment by rishuzz** [comment] 2021-01-20 08:29
@violetagg  I updated  SCG to v2.4.2 internally that updated all Netty dependencies, I didn't update Netty dependecies specifically.

**Comment by violetagg** [comment] 2021-01-20 08:49
@rishuzz Then please check your dependencies for mismatch. `Spring Boot`  version `2.4.2` comes with `Reactor Netty` `1.0.3` and `Netty` version `4.1.58.Final`

https://github.com/spring-projects/spring-boot/releases/tag/v2.4.2

```
Upgrade to Netty 4.1.58.Final #24828
...
Upgrade to Reactor 2020.0.3 #24698
```

**Comment by rishuzz** [comment] 2021-01-20 10:14
@violetagg I updated the POM, and below is dependency tree for Netty in my project , and that issue still exist with these dependencies too.

[INFO] |     +- org.springframework.boot:spring-boot-starter-reactor-netty:jar:2.4.2:compile
[INFO] |     |  \- io.projectreactor.netty:reactor-netty-http:jar:1.0.3:compile
[INFO] |     |     +- io.netty:netty-codec-http:jar:4.1.58.Final:compile
[INFO] |     |     |  +- io.netty:netty-common:jar:4.1.58.Final:compile
[INFO] |     |     |  +- io.netty:netty-buffer:jar:4.1.58.Final:compile
[INFO] |     |     |  +- io.netty:netty-transport:jar:4.1.58.Final:compile
[INFO] |     |     |  +- io.netty:netty-codec:jar:4.1.58.Final:compile
[INFO] |     |     |  \- io.netty:netty-handler:jar:4.1.58.Final:compile
[INFO] |     |     +- io.netty:netty-codec-http2:jar:4.1.58.Final:compile
[INFO] |     |     +- io.netty:netty-resolver-dns:jar:4.1.58.Final:compile
[INFO] |     |     |  +- io.netty:netty-resolver:jar:4.1.58.Final:compile
[INFO] |     |     |  \- io.netty:netty-codec-dns:jar:4.1.58.Final:compile
[INFO] |     |     +- io.netty:netty-resolver-dns-native-macos:jar:osx-x86_64:4.1.58.Final:compile
[INFO] |     |     |  \- io.netty:netty-transport-native-unix-common:jar:4.1.58.Final:compile
[INFO] |     |     +- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.58.Final:compile
[INFO] |     |     \- io.projectreactor.netty:reactor-netty-core:jar:1.0.3:compile
[INFO] |     |        \- io.netty:netty-handler-proxy:jar:4.1.58.Final:compile
[INFO] |     |           \- io.netty:netty-codec-socks:jar:4.1.58.Final:compile
[INFO] |     +- org.springframework:spring-web:jar:5.3.3:compile
[INFO] |     \- org.springframework:spring-webflux:jar:5.3.3:compile

**Comment by violetagg** [comment] 2021-01-20 10:46
@rishuzz OK can you describe your scenario or add some reproducible example?

**Comment by rishuzz** [comment] 2021-01-20 12:44
Hi  @violetagg , The issue is SCG trying to reach out to a route ( target tomcat) and it's failing with the above error ( connection reset by peer) but when we check connectivity it's fine between the systems ..!

It working fine in the lower environments ( dev and QA )

**Comment by violetagg** [comment] 2021-01-20 12:51
@rishuzz `Connection reset by peer` means the remote peer closes the connection for some reason.
You wrote:

> It working fine in the lower environments ( dev and QA )
 
When you face this issue what are the logs on the remote peer?
If you cannot provide example can you at least provide tcp dump?

**Comment by rishuzz** [comment] 2021-01-20 13:11
@violetagg  below is excerpt of tcp dump, we are seeing **flag[R]** from target system, this might be the cause of issue ?
but ping to target url happening successfully 
 
***target-IP*** > ***src-IP***: **Flags [R]**, cksum 0x9099833 (correct), seq 1169897592, win 0, length 0

**Comment by violetagg** [comment] 2021-01-20 13:16
> @violetagg below is excerpt of tcp dump, we are seeing **flag[R]** from target system, this might be the cause of issue ?
> but ping to target url happening successfully
> 
> _**target-IP**_ > _**src-IP**_: **Flags [R]**, cksum 0x9099833 (correct), seq 1169897592, win 0, length 0

Yes this definitely is the reason for the `connection reset by peer`. Did you check the logs on the remote peer?

**Comment by rishuzz** [comment] 2021-01-20 13:23
@violetagg Actually we did , but it seems requests are not reaching to target tomcat.. might be firewall issue ? 
we are looking into it, will post our findings here.
Thank you @violetagg

**Comment by violetagg** [comment] 2021-01-26 09:43
@rishuzz Were you able to verify whether it is an issue with the firewall?

**Comment by dandamudi1414** [comment] 2021-01-27 05:05
@violetagg  - Yes and our network team is checking on this and seems to be an issue with the firewall 
Thank you once again

**Comment by violetagg** [comment] 2021-01-27 06:22
@dandamudi1414 Thanks. Let me close this, if it is needed we can reopen it.

**Closed by violetagg** 2021-01-27 06:22 UTC
Labels: for/user-attention, type/bug
